- .eslintrc.js
- .gitignore
- README.md
- adr/2020_04_06_javascript_framework_choice.md
- adr/2020_05_28_test_framework.md
- buildspec.yml
- cypress.json
- cypress/TESTING.md
- cypress/fixtures/example.json
- cypress/integration/numberUtils_spec.js
- cypress/integration/zoom_spec.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- package.json
- src/main.js
- src/modules/map/components/OpenlayersMap.vue
- src/modules/store/README.md
- src/modules/store/index.js
- src/modules/store/modules/position.js
- src/modules/store/plugins/vuex-url-search-params.js
- src/modules/toolbox/components/ZoomButtons.vue
- src/numberUtils.js
URL to state (and vice-versa) is functional for zoom level
We need some deployment to see how things are working, might be our next step?
> Adding Cypress.io for Unit testing and Integration tests

- CONTRIBUTING.md
- README.md
- ROADMAP.md
Adding badges for build status
Adding contribution documentation
> Splitting doc in multiple files

- src/api/layers.api.js
- src/modules/map/components/Footer.vue
- src/modules/map/components/OpenlayersMap.vue
- src/modules/map/store/map.store.js
- src/modules/store/index.js
- src/modules/store/modules/geolocation.store.js
- src/modules/store/modules/position.store.js
- src/modules/store/plugins/geolocation-management.plugin.js
- src/modules/store/plugins/geolocation-refresh.plugin.js
- src/modules/toolbox/ToolboxModule.vue
- src/modules/toolbox/components/BackgroundSelectorButton.vue
- src/modules/toolbox/components/GeolocButton.vue
- src/numberUtils.js
- src/scss/variables.scss
- tests/e2e/specs/deployScript_spec.js
- tests/e2e/specs/headerBar_spec.js
- tests/e2e/specs/legacyParamImport_spec.js
- tests/unit/layer.api.spec.js
- tests/unit/numberUtils.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/feature_BGDIINF_SB-1437_geolocation/index.html)
> Adding geolocation button

- .github/workflows/main.yml
updated github action to  add semver tags to the latest version (related to https://github.com/geoadmin/doc-guidelines/pull/65)
> BGDIINF_SB-1497 update github tagging action

- src/api/layers.api.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix_BGDIINF_SB-1688/index.html)
Example : _ch.swisstopo-vd.geometa-gemeinde_
> Add tooltip/identify support for aggregate layers

- .github/workflows/add-testlink-to-pr.yml
[Test link](https://web-mapviewer.dev.bgdi.ch/add_github_actions_for_pr/index.html)
> Automaticaly create test links for PR

- .gitignore
- adr/2021_03_16_url_param_structure.md
This PR adds the decision about the new format for URL parameters.
> BGDIINF_SB-1675 add ADR about URL param structure

- src/modules/menu/MenuModule.vue
- src/modules/menu/components/header/HeaderLoadingBar.vue
- src/scss/variables.scss
Also make it smaller, and with a new loading animation that goes ping pong red/transparent
[Test link](https://web-mapviewer.dev.bgdi.ch/fix_BGDIINF_SB-1416/index.html)
> Move loading bar at the top

- package-lock.json
- package.json
- src/modules/map/components/openlayers/OpenLayersMap.vue
Small simplification found by playing with paperjs
[Test link](https://web-mapviewer.dev.bgdi.ch/misc/index.html)
> Miscellaneous code simplification

- src/modules/menu/components/activeLayers/MenuActiveLayersLegendPopup.vue
- src/modules/overlay/components/ModalWithOverlay.vue
- src/modules/tooltip/components/TooltipBox.vue
- src/setup-fontawesome.js
- src/utils/print.js
[Test link](https://web-mapviewer.dev.bgdi.ch/feature_BGDIINF_SB-1701/index.html)
> Add print button for tooltip/legend popup

- adr/2021_04_14_drawing_library.md
[Test link](https://web-mapviewer.dev.bgdi.ch/add_adr_for_drawing/index.html)
> Adding architectural decision regarding drawing library/module

- package-lock.json
- package.json
- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/modules/store/modules/layers.store.js
- tests/e2e/fixtures/layers.fixture.json
- tests/e2e/specs/layers.spec.js
based on https://github.com/geoadmin/web-mapviewer/pull/48
[Test link](https://web-mapviewer.dev.bgdi.ch/feature_bgdiinf_sb-1507/index.html)
> Add timestamp selector in layer menu

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/README.md
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/DrawingToolboxButton.vue
- src/modules/map/MapModule.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/menu/components/MenuSection.vue
- src/modules/menu/components/MenuTray.vue
- src/modules/overlay/store/overlay.store.js
- src/modules/store/index.js
- src/modules/store/modules/drawing.store.js
- src/modules/store/modules/ui.store.js
- src/modules/store/plugins/click-on-map-management.plugin.js
- src/modules/store/plugins/drawing-overlay-menu-management.plugin.js
- src/modules/toolbox/ToolboxModule.vue
- src/setup-fontawesome.js
- src/views/MapView.vue
Injecting/providing OpenLayers instance into the drawing module
[Test link](https://web-mapviewer.dev.bgdi.ch/feature_bgdiinf_sb-1774/index.html)
> Preparing base drawing module

- package-lock.json
- src/modules/menu/components/MenuSection.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/modules/menu/components/topics/MenuTopicSelectionPopup.vue
- src/modules/menu/scss/menu-items.scss
- src/modules/menu/scss/topics-image.scss
- src/modules/overlay/components/ModalWithOverlay.vue
- src/modules/toolbox/components/BackgroundSelectorButton.vue
- src/modules/toolbox/components/GeolocButton.vue
- src/modules/toolbox/components/ZoomButtons.vue
Added the cursor pointer where needed.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix_bgdiinf_sb-1786_wrong_cursor/index.html)
> BGDIINF_SB-1786: Add cursor pointer

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingStylePopup.vue
- src/modules/store/modules/drawing.store.js
- src/setup-fontawesome.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1777_styling_popup/index.html)
> Styling popup

- package.json
- src/api/files.api.js
- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingStylePopup.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/DrawingToolboxButton.vue
- src/modules/drawing/components/GeometryMeasure.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/drawing/lib/drawingUtils.js
- src/modules/drawing/lib/style.js
- src/modules/menu/components/MenuTray.vue
- src/modules/store/modules/drawing.store.js
- src/setup-fontawesome.js
- tests/e2e/specs/drawing.spec.js
- tests/unit/drawingUtils.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1775/index.html)
> Add DrawingManager

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingStylePopup.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/drawing/lib/drawingUtils.js
- tests/e2e/specs/drawing.spec.js
- tests/unit/drawingUtils.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1777_styling_popup/index.html)
> Improve drawn feature popup

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingStylePopup.vue
- src/modules/drawing/components/GeometryMeasure.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/drawing/lib/drawingUtils.js
- src/modules/store/modules/drawing.store.js
- tests/e2e/specs/drawing.spec.js
- tests/e2e/support/commands.js
- tests/unit/drawingUtils.spec.js
- only store GeoJSON in the store when drawing is done
[Test link](https://web-mapviewer.dev.bgdi.ch/refactor_drawing_bgdiinf_sb-1832/index.html)
> Refactor drawing

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingStylePopup.vue
- src/modules/drawing/components/TextStylePopup.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/drawing/lib/style.js
- src/setup-fontawesome.js
- tests/e2e/specs/drawing.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1807/index.html)
> BGDIINF_SB-1807 Add styling popup and capabilities for text

- LICENSE.md
[Test link](https://web-mapviewer.dev.bgdi.ch/update_licence_font_awesome/index.html)
> Update licence to integrate font-awesome

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/Color.vue
- src/modules/drawing/components/DrawingStylePopup.vue
- src/modules/drawing/components/LineStylePopup.vue
- src/modules/drawing/components/MarkerStylePopup.vue
- src/setup-fontawesome.js
- tests/e2e/specs/drawing.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/lines_bgdiinf_sb-1806/index.html)
TODO:
-  [x] rebase on develop when #72  is merged;
-  [x] add tests.
> Style lines

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/drawing/lib/style.js
- tests/e2e/specs/drawing.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1822/index.html)
> Create a polygon only when the first point is clicked

- package-lock.json
- package.json
- src/api/profile.api.js
- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/MarkerStylePopup.vue
- src/modules/drawing/components/ProfilePopup.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/drawing/lib/ProfileChart.js
- src/modules/drawing/lib/drawingUtils.js
- src/modules/drawing/lib/profileUtils.js
- src/modules/drawing/lib/style.js
- src/setup-fontawesome.js
- tests/e2e/specs/drawing.linepoly.spec.js
- tests/e2e/specs/profile.spec.js
- tests/unit/drawingUtils.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1805/index.html)
> BGDIINF_SB-1805 & BGDIINF_SB-1849: Show / update profile

- src/api/icon.api.js
- src/modules/drawing/components/MarkerStylePopup.vue
- src/modules/drawing/lib/style.js
- tests/e2e/support/commands.js
[Test link](https://web-mapviewer.dev.bgdi.ch/fix_icon_retrieval_issues_bgdiinf_sb-1779/index.html)
> Fix icons retrieval issues

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingStylePopup.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/drawing/lib/MeasureManager.js
- src/modules/drawing/lib/drawingUtils.js
- src/modules/drawing/lib/style.js
- tests/e2e/specs/measure.spec.js
- tests/unit/drawingUtils.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1804/index.html)
> BGDIINF_SB-1804 Adapt Line/Polygon with Measurement style

- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/OpenLayersMousePosition.vue
- src/utils/militaryGridProjection.js
- src/utils/numberUtils.js
- tests/e2e/specs/mouseposition.spec.js
- tests/unit/utils/numberUtils.spec.js
Display mouse position in status bar with a projection switch
See https://jira.swisstopo.ch/browse/BGDIINF_SB-1436
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1436_display_coordinates_in_statusbar/index.html)
> adding a mouse position

- src/api/features.api.js
- src/api/topics.api.js
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- src/modules/store/modules/layers.store.js
- src/modules/toolbox/components/BackgroundSelectorButton.vue
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/LayerParamConfig.class.js
- src/utils/legacyLayerParamUtils.js
- tests/e2e/specs/legacyParamImport.spec.js
- tests/unit/utils/legacyLayerParamUtils.spec.js
Also fix legacy layers import (if you copy paste a map.geo.admin.ch URLs with all param, layers were not showing up correctly)
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1878/index.html)
> Fix background disapearance

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/lib/DrawingManager.js
- tests/e2e/specs/exportDrawing.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1801_gpx_export/index.html)
> BGDIINF_SB-1801 Export drawing as GPX

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/helperComponents/ConfirmationModal.vue
- tests/e2e/specs/drawing.actions.spec.js
- tests/e2e/support/commands.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1803/index.html)
> BGDIINF_SB-1803 Delete drawing

- .env.development
- .env.production
- src/api/files.api.js
- src/config.js
- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/ShareForm.vue
- src/modules/drawing/components/TextStylePopup.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/helperComponents/ConfigurableModal.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/menu/components/MenuTray.vue
- src/modules/store/modules/drawing.store.js
- src/router/storeSync/AdminLayerParamConfig.class.js
- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/storeSync.config.js
- tests/e2e/specs/drawing.actions.spec.js
- tests/e2e/support/commands.js
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb-1846/index.html)
> BGDIINF_SB-1846: Share button

- .env.development
- src/modules/drawing/DrawingModule.vue
[Test link](https://web-mapviewer.dev.bgdi.ch/minor_fixes/index.html)
> Some minor fixes

- cypress.json
- src/modules/menu/components/MenuSection.vue
- src/modules/menu/components/MenuTray.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- src/modules/menu/components/topics/MenuTopicTreeItem.vue
- src/modules/store/modules/topics.store.js
- src/modules/store/plugins/topic-change-management.plugin.js
- tests/e2e/specs/topics.spec.js
- tests/e2e/support/commands.js
[Test link](https://web-mapviewer.dev.bgdi.ch/feature_bgdiinf_sb-1705_leave_menu_open_when_topic_is_switched/index.html)
> BGDIINF_SB-1705: Leave menu open when topic is switched

- tests/e2e/specs/drawing/drawing-layer.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/e2e_test_for_drawing_layer/index.html)
> Adding a e2e test checking the creation of the drawing layer at the end of a drawing session

- package-lock.json
- src/modules/menu/components/MenuTray.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- tests/e2e/specs/layers.spec.js
[Test link](https://web-mapviewer.dev.bgdi.ch/feature_bgdiinf_sb-1787_display_hyphen_when_no_layer_is_selected/index.html)
> BGDIINF SB-1787: Display `-` (hyphen) when no layer is selected

- .eslintrc.js
- scripts/file-utils.js
- scripts/generate-i18n-files.js
- scripts/s3-utils.js
- src/api/search.api.js
- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/ProfilePopup.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/drawing/lib/drawingUtils.js
- src/modules/drawing/lib/style.js
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/store/modules/ui.store.js
- src/modules/tooltip/components/SwipableBottomSheet.vue
- src/router/index.js
- src/utils/coordinateUtils.js
- tests/e2e/specs/drawing/marker-text.spec.js
- tests/e2e/support/drawing.js
[Test link](https://web-mapviewer.dev.bgdi.ch/feat-code-style/index.html)
> Code style: Require Following Curly Brace Conventions

- src/api/layers/KMLLayer.class.js
[Test link](https://web-mapviewer.dev.bgdi.ch/feat-bgdiinf_sb-2097-kml-redirect/index.html)
> BGDIINF_SB-2097: Added comment about KML files location

- tests/e2e/specs/drawing/marker-text.spec.js
According to the ticket the colors didn't load correctly during testing.
The underlying problem seems to have been fixed by another change as all
the tests worked out of the box. So, this change focuses on re-enabling
all the tests and some minor refactoring.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2157-e2e-drawing-marker/index.html)
> BGDIINF_SB-2157: Re-enabled all failing e2e tests

- cypress.json
- tests/e2e/specs/drawing/export.spec.js
- tests/e2e/specs/drawing/kml.spec.js
- tests/e2e/specs/drawing/marker-text.spec.js
- tests/e2e/support/commands.js
- tests/e2e/support/drawing.js
and remove any specific value previously set in tests that doesn't exceed the new default values
[Test link](https://web-mapviewer.dev.bgdi.ch/feat-bgdiinf_sb-2180_raise_e2e_timeout_value/index.html)
> BGDIINF_SB-2180: raise e2e timeout globally

- src/modules/map/components/footer/MapFooter.vue
- src/modules/map/components/footer/MapFooterMousePosition.vue
- src/modules/map/components/footer/MapFooterProjection.vue
- src/modules/map/components/footer/MapFooterScale.vue
- src/modules/map/store/map.store.js
- src/utils/coordinateUtils.js
- tests/e2e/specs/mouseposition.spec.js
As we now have many retries (set globally), this should now pass after a couple retries
[Test link](https://web-mapviewer.dev.bgdi.ch/feat-jira-bgdiinf_sb-2140_reactivate_mouse_position_tests/index.html)
Or not 😜 looks like it requires more work
> BGDIINF_SB-2140: reactivating mouse tests

- package-lock.json
- package.json
- src/modules/map/components/LocationPopup.vue
- tests/e2e/specs/mouseposition.spec.js
We recently fixed a bug that went unnoticed for a while.
This adds a test so that this doesn't happen again.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2239-e2e-qr-code-url/index.html)
> BGDIINF_SB-2239: Added e2e test for the QR code

- src/modules/i18n/index.js
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/openlayers/OpenLayersAccuracyCircle.vue
- src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
- src/modules/map/components/openlayers/utils/addLayerToMap-mixins.js
I'm not 100% sure about the `getMap` commit. But I think we can get rid of the if-clauses.
And the rest is more style than substance :smile:
What do you think?
[Test link](https://web-mapviewer.dev.bgdi.ch/refactor-20220302/index.html)
> Miscellaneous refactoring

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingExporter.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/lib/ProfileChart.js
- src/modules/store/plugins/drawing-layer-management.plugin.js
- tests/e2e/specs/drawing/delete.spec.js
- tests/e2e/specs/drawing/drawing-layer.spec.js
- tests/e2e/specs/drawing/export.spec.js
- tests/e2e/specs/drawing/kml.spec.js
- tests/e2e/specs/drawing/line-polygon.spec.js
- tests/e2e/specs/drawing/marker-text.spec.js
- tests/e2e/specs/drawing/profile.spec.js
- tests/e2e/support/drawing.js
This fixes most of the drawing e2e tests except:
* export
* marker-text
* profile
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-e2e-after-rewrite/index.html)
> Fixed some of the e2e tests after the rewrite

- src/modules/drawing/lib/export-utils.js
- tests/e2e/plugins/index.js
- tests/e2e/specs/drawing/export.spec.js
- tests/e2e/support/drawing.js
This fixes a few bugs from the recent refactoring and also
one in the GPX export that seems to have been there before.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2358-e2e-export/index.html)
> BGDIINF_SB-2358: Fixed drawing export e2e tests

- src/modules/drawing/components/ProfilePopupPlot.vue
- src/modules/drawing/lib/ProfileChart.js
The link was made clickable and was moved out of the graph in the upper margin
[Test link](https://web-mapviewer.dev.bgdi.ch/feat-2390-refractor-drawing-update-altitude-plot-source-link/index.html)
> BGDIINF_SB-2390: update altitude plot source link

- src/config.js
- src/modules/map/components/footer/MapFooterAppVersion.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
Added a global constant so that the app version and dev disclaimer will always be shown based on the same if condition
[Test link](https://sys-map.dev.bgdi.ch/feat-2438-only-show-version-when-dev-disclaimer-is-shown/index.html)
> App version is only shown when also the dev disclaimer is shown.

- src/scss/webmapviewer-bootstrap-theme.scss
Adding a shadow box on all inputs that contains text, so that the user can more easily follow where his focus is.
[Test link](https://sys-map.dev.bgdi.ch/feat_bgdiinf_sb-2436_bigger_input_focus_feedback/index.html)
> Bigger input focus feedback

- src/modules/menu/components/share/MenuShareSection.vue
[Test link](https://sys-map.dev.bgdi.ch/feat-2598-deactivate-embed-in-share-menu/index.html)
> Deactivated "embedding" part of share menu for MVP

- .prettierignore
- src/modules/drawing/lib/modifyInteraction.js
Also added a ".prettierignore", as we want to keep the formatting of the modify interaction.
No review is needed for the PR, as the file added is simply a verbatim copy of the modify interaction from openlayers.
[Test link](https://sys-map.dev.bgdi.ch/bugfix-2211-add-clean-copy-of-modifyinteraction/index.html)
> Added clean copy of the modify Interaction from openlayers

- src/modules/i18n/components/LangSwitchToolbar.vue
- src/modules/menu/components/menu/MenuSettings.vue
- src/scss/variables.scss
Now we use the btn-light and btn-primary for the button for a better nice looking
and also for ui consistency accross other buttons.
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2509-lang-menu-style/index.html)
> BGDIINF_SB-2509: Improve configuration menu (lang and ui mode)

- src/modules/infobox/components/styling/DrawingStyleColorSelector.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
- src/scss/webmapviewer-bootstrap-theme.scss
Made some button smaller (icons and color selections) and reduce the size of
the overlay header.
[Test link](https://sys-map.dev.bgdi.ch/feat-resize-drawing/index.html)
> Resize the drawing tool overlay

- src/modules/menu/components/search/SearchBar.vue
Debounce the search bar input keys.
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2476-search-bar/index.html)
> BGDIINF_SB-2476: Debounce the search bar

- src/modules/menu/components/share/MenuShareSocialNetworks.vue
Use the same CSS class for regular stand alone buttons (like in drawing menu).
[Test link](https://sys-map.dev.bgdi.ch/feat-harmonize-buttons/index.html)
> Harmonize share icons

- src/modules/i18n/components/LangSwitchToolbar.vue
- src/modules/infobox/components/FeatureProfile.vue
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/menu/components/menu/MenuSettings.vue
- src/modules/menu/components/share/MenuShareSocialNetworks.vue
- src/scss/variables.scss
- src/scss/webmapviewer-bootstrap-theme.scss
Use a global variable to add space between adjacent buttons.
Also removed useless legacy css code in FeatureStyleEdit.
[Test link](https://sys-map.dev.bgdi.ch/feat-design-tune/index.html)
> Harmonize button spacer and remove duplicate delete button in drawing

- buildspec.yml
- package.json
- vite-plugins/generate-build-info.js
- vite.config.ts
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2671-artifact-bucket/index.html)
> BGDIINF_SB-2671: Upload build artifacts to S3

- src/modules/drawing/components/DrawingExporter.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/modules/menu/components/menu/MenuSettings.vue
- src/scss/webmapviewer-bootstrap-theme.scss
- src/utils/ButtonWithIcon.vue
- src/utils/ModalWithBackdrop.vue
- src/utils/PopoverButton.vue
Removed the top corner of the open/close menu button and increase a bit spaces.
[Test link](https://sys-map.dev.bgdi.ch/feat-menu-button-look/index.html)
> Improved look and feel of menu button

- buildspec.yml
[Test link](https://sys-map.dev.bgdi.ch/bug-bgdiinf_sb-2671-stagings-build/index.html)
> BGDIINF_SB-2671: Fixed second artifact build

- package.json
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2671-deploy-int/index.html)
> BGDIINF_SB-2671: Fixed test:e2e:ci:int

- package.json
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/LocationPopupCopyInput.vue
- src/modules/map/components/LocationPopupCopySlot.vue
- tests/e2e-cypress/integration/mouseposition.cy.js
Set fallback to non short url in case the backend service is not available.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2662-shortlink-position-popup/index.html)
> BGDIINF_SB-2662: Use shortlink for position popup url

- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/SharePopup.vue
- tests/e2e-cypress/integration/drawing/share.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2661-shortlink-kml/index.html)
> BGDIINF_SB-2661: Use shortlink to share kml drawings

- src/modules/map/components/openlayers/OpenLayersPopover.vue
- src/utils/print.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2708-html-print/index.html)
> BGDIINF_SB-2708: Fixed map popover printing.

- src/modules/drawing/components/SharePopup.vue
- src/modules/menu/components/BlackBackdrop.vue
- src/utils/ModalWithBackdrop.vue
- tests/e2e-cypress/integration/drawing/share.cy.js
The modal view with the black drop did not took the whole screen but only the
size of the modal window. Also improved padding and margin for modal window
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2695-black-backdrop/index.html)
> BGDIINF_SB-2695: Fixed modal black drop

- src/modules/map/components/LocationPopupCopySlot.vue
This allow more place for the data and avoid truncating the what3words.
Please give your feedback on the copy icon in the position popup, use the test link below and compare it to the current version in https://sys-map.dev.bgdi.ch
[Test link](https://sys-map.dev.bgdi.ch/preview/copy-icon/index.html)
> Use copy icon for coordinates in position popup

- src/config.js
- src/store/modules/ui.store.js
Removed comment probably added for local testing.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2678-banner/index.html)
> BGDIINF_SB-2678: Banner bug

- README.md
Check the [README.md](https://github.com/geoadmin/web-mapviewer/blob/bug_update_doc_regarding_deploy/README.md)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_update_doc_regarding_deploy/index.html)
> Updating doc regarding app deployment

- src/modules/infobox/components/SwipableBottomSheet.vue
- src/modules/map/components/WarningRibbon.vue
- src/modules/map/components/footer/MapFooterBackgroundSelector.vue
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/topics/MenuTopicTreeItem.vue
- src/utils/LoadingBar.vue
Mainly we use 2 red colors, the primary (admin red) and the danger (for error
and dangerous actions).
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-look-and-feel/index.html)
> Menu shadow and corrected the red colors

- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
Based on post review of #339, updating vector features might be an issue as
well as deserializing features more than once.
Therefore we clear the features and re-add them. We also make sure to only
deserialize the features once.
[Test link with legacy drawing](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2728-legacy-drawing-2/index.html#/map?layers=KML|https://sys-public.dev.bgdi.ch/api/kml/files/oo-VqoIzRv20NewKZEaGBg|Dessin,,1)
[Test link with legacy drawing with icons](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2728-legacy-drawing-2/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.astra.wanderland-sperrungen_umleitungen,KML%7C%7Ch …
> BGDIINF_SB-2728: Fixed possible issues with KML

- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
The crash could occure if the load kml failed or if the load kml results
arrive once the kml layer has been removed from the map (drawing mode open).
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-kml-crash/index.html)
> Avoid crash in openlayers in case of load kml failure

- src/modules/drawing/components/SharePopup.vue
- src/modules/map/components/LocationPopup.vue
- src/router/index.js
- src/utils/__tests__/urlQuery.spec.js
- src/utils/url.js
See https://jira.swisstopo.ch/browse/BGDIINF_SB-2750
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2750-url-encoding-2/index.html)
> BGDIINF_SB-2750: Encode `|` in url

- README.md
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-anchor-in-doc/index.html)
> fixing trivial link error in doc

- src/modules/drawing/components/DrawingToolbox.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-2772_delete_last_point_style/index.html)
> BGDIINF_SB-2772 : add styling back to delete last point button

- src/modules/menu/components/header/HeaderWithSearch.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2755_search_text/index.html)
> Updating translations for search bar 

- ROADMAP.md
@pakb pls review
[Test link](https://sys-map.dev.bgdi.ch/preview/davidoesch-mvp-update/index.html)
> Updated  post MVP

- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/search/SearchBar.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-2756_search_font_size/index.html)
> try to us the same font size as in the current UI

- src/modules/menu/components/topics/MenuTopicSection.vue
- src/modules/menu/components/topics/MenuTopicSelectionPopup.vue
- src/modules/menu/scss/topics-image.scss
- src/utils/ModalWithBackdrop.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-bgdiinf_sb-2748-add-selection-feedback-in-topics/index.html)
> BGDIINF_SB-2748: Add selection feedback in topics.

- src/modules/menu/components/search/SearchBar.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2754_expand_search_bar/index.html)
> BGDIINF_SB-2754: Expand searchbar on mobile when focused

- src/modules/menu/components/menu/MenuSection.vue
- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/share/MenuShareEmbed.vue
- src/modules/menu/components/share/MenuShareSection.vue
- src/modules/menu/components/share/MenuShareShortLinkInput.vue
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/share.store.js
- src/store/modules/ui.store.js
- src/views/LoadingView.vue
- src/views/MapView.vue
- tests/e2e-cypress/integration/shareShortLink.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-1856_iframe-generator/index.html)
> BGDIINF_SB-1856 : share - iframe code snippet generator

- scripts/generate-i18n-files.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/menu/components/share/MenuShareEmbed.vue
- tests/e2e-cypress/integration/shareShortLink.cy.js
so that the generated code can be a fluid iframe (meaning it takes 100% of the width of its container)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2429_full_width_embed_snippet/index.html)
> BGDIINF_SB-2429 : add a full-width checkbox to the embed code generator

- package-lock.json
- package.json
- src/modules/map/components/cesium/CesiumMap.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/update_cesium/index.html)
> Update cesium to 1.107, use baseLayer instead of imageryProvider

- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/constants.js
- src/modules/map/components/cesium/utils/cameraUtils.js
- tests/e2e-cypress/integration/3d/navigation.cy.js
- tests/e2e-cypress/support/commands.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2982-limit-cesium-camera/index.html)
> BGDIINF_SB-2982: limit camera height

- cypress.config.ts
- src/modules/drawing/DrawingModule.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/router/storeSync/LayerParamConfig.class.js
- src/store/modules/drawing.store.js
- tests/e2e-cypress/integration/3d/navigation.cy.js
- tests/e2e-cypress/integration/3d/transitionTo3d.cy.js
- tests/e2e-cypress/integration/drawing/geodesicDrawing.cy.js
- tests/e2e-cypress/integration/drawing/kml.cy.js
- tests/e2e-cypress/integration/geolocation.cy.js
- tests/e2e-cypress/integration/header.cy.js
- tests/e2e-cypress/integration/infobox.cy.js
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/integration/legacyParamImport.cy.js
- tests/e2e-cypress/integration/menuTray.cy.js
- tests/e2e-cypress/integration/mouseposition.cy.js
- tests/e2e-cypress/integration/search/search-results.cy.js
- tests/e2e-cypress/integration/timeSlider.cy.js
- tests/e2e-cypress/integration/topics.cy.js
- tests/e2e-cypress/support/commands.js
- tests/e2e-cypress/support/drawing.js
Also containing :
- Simplification of utils function in e2e test
- Simplification of KML loading with AdminID
- using URLs from the config for Cesium optimization (instead of hardcoding them)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-3008_check_camera_param_at_startup/index.html)
> BGDIINF_SB-3008 : check camera param at startup

- src/modules/map/components/cesium/CesiumMap.vue
- tests/e2e-cypress/integration/3d/click.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3006-3d-click-to-store/index.html)
> BGDIINF_SB-3006: Send click on the 3D map to the store

- src/modules/infobox/FeatureElevationProfilePlotCesiumBridge.vue
- src/modules/infobox/components/FeatureElevationProfilePlot.vue
- src/modules/map/components/MapPopover.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumPopover.vue
- src/modules/map/components/cesium/constants.js
- src/modules/map/components/cesium/utils/highlightUtils.js
- src/modules/map/components/cesium/utils/primitiveLayerUtils.js
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
- src/utils/coordinateUtils.js
- src/utils/layerUtils.js
- tests/e2e-cypress/integration/infobox.cy.js
- tests/e2e-cypress/support/commands.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3009_floating_tolltip/index.html)
> BGDIINF_SB-3009: Create a floating tooltip for Cesium (+ BGDIINF_SB-2977 Create a profile position tracker for Cesium)

- src/modules/menu/components/share/MenuShareEmbed.vue
- src/modules/menu/components/share/MenuShareInputCopyButton.vue
- src/modules/menu/components/share/MenuShareSection.vue
- src/modules/menu/components/share/MenuShareShortLinkInput.vue
- src/setup-fontawesome.js
- tests/e2e-cypress/integration/shareShortLink.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2430-share-menu/index.html)
> BGDIINF_SB-2430: Improved sharing embed previzualization

- src/config.js
- src/modules/drawing/components/DrawingMeasureInteraction.vue
- src/modules/infobox/components/FeatureElevationProfile.vue
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
- src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/map/components/openlayers/OpenLayersMouseTracker.vue
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
- src/store/modules/position.store.js
wherever component were not linked to the store yet. For others (those who already use the store) this will come later when the projection is in the store
> BGDIINF_SB-2890 : add projection as props for all mapping components

- src/modules/drawing/components/DrawingMeasureInteraction.vue
- src/modules/map/components/MapPopover.vue
We could not move the drawing component due to the arrow of the tooltip that
overtook the pointer event instead of passing them to open layer.
> BGDIINF_SB-2890: Fixed drawing moving component

- .prettierrc
- src/api/layers/ExternalGroupOfLayers.class.js
- src/api/layers/GeoAdminWMSLayer.class.js
- src/api/search.api.js
- src/modules/map/components/cesium/CesiumPopover.vue
- src/modules/map/components/cesium/utils/primitiveLayerUtils.js
- src/modules/menu/components/share/MenuShareInputCopyButton.vue
- src/router/storeSync/QueryToStoreOnlyParamConfig.class.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/layers.store.js
- src/utils/layerUtils.js
- src/utils/numberUtils.js
and run a subsequent npm run format
[Test link](https://sys-map.dev.bgdi.ch/preview/reactivate_prettier_for_jsdoc/index.html)
> re-activate JSDoc format with Prettier

- src/modules/menu/MenuModule.vue
- src/modules/menu/scss/toolbox-buttons.scss
The geolocation, 3d, time slider and reproject  button make no sense in
drawing mode and they would not work anyway therefore remove them.
> BGDIINF_SB-2890: Deactivate some tools in drawing mode

- .github/workflows/add-testlink-to-pr.yml
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-test-link/index.html)
> Add test link to PR to `develop-*` branches

- src/modules/map/components/cesium/CesiumMap.vue
We still have an issue with the zoom level, but this might be solved by #471
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2890-3d-2-2d/index.html)
> BGDIINF_SB-2890: Fixed 3d to 2d center of map

- cypress.config.ts
- src/store/modules/position.store.js
- tests/e2e-cypress/integration/drawing/geodesicDrawing.cy.js
- tests/e2e-cypress/support/commands.js
See commit messages
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2890-drawing-layer-e2e-2/index.html)
> BGDIINF_SB-2890: Fixing geodesie tests

- cypress.config.ts
- tests/e2e-cypress/integration/infobox.cy.js
- tests/e2e-cypress/integration/mouseposition.cy.js
- tests/e2e-cypress/support/commands.js
Reduced the timeout in order to speed tests when they are failings
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-ci-timeout-retry/index.html)
> Updated timeout in Cypress config

- src/modules/drawing/lib/__tests__/drawingUtils.spec.js
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/utils/setupProj4.js
- tests/e2e-cypress/integration/3d/navigation.cy.js
- tests/e2e-cypress/integration/3d/transitionTo3d.cy.js
- tests/e2e-cypress/integration/drawing/kml.cy.js
- tests/e2e-cypress/integration/drawing/marker-text.cy.js
- tests/e2e-cypress/integration/drawing/share.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-2890_fix_e2e_tests/index.html)
> BGDIINF_SB-2890 : fix some e2e tests

- src/api/layers/ExternalGroupOfLayers.class.js
- src/api/layers/ExternalLayer.class.js
- src/api/layers/ExternalWMSLayer.class.js
- src/api/layers/ExternalWMTSLayer.class.js
- src/modules/infobox/InfoboxModule.vue
- src/modules/infobox/components/ImportContent.vue
- src/modules/infobox/components/ImportContentResultItem.vue
- src/modules/infobox/components/ImportContentResultList.vue
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- src/setup-fontawesome.js
- src/store/modules/__tests__/layers.store.spec.js
- src/store/modules/layers.store.js
- src/utils/file.js
- tests/e2e-cypress/integration/infobox.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3084-import-result-list/index.html)
> BGDIINF_SB-3084 : GUI for import results

- src/utils/file.js
Some external WMS GetCap might list several bounding box using different projection.
That was the case with https://wms.geo.ag.ch/ where the first bounding box
in the list was CRS:84. Currently we don't support this projection which is
similar to ESPG:4326 but has an inversed axis order (lat/long instead of long/lat).
However in this use case the second bounding box was in LV95 which is supported.
So now instead of taking the first bounding box and doing a reproject, we
test simply over all bounding box and only try to re-project the one that we
support, otherwise we don't set the extent if the boundingbox is not found or
of an unsupported projection.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-3071-import-tool/index.html)
> BGDIINF_SB-3071: Fixed bug in import tool for extent projection

- src/modules/menu/MenuModule.vue
- src/modules/menu/components/debug/DebugToolbar.vue
- src/scss/webmapviewer-bootstrap-theme.scss
This was making the drawing e2e tests failing.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2890-drawing-share-e2e/index.html)
> BGDIINF_SB-2890: Moved the debug tool bar to avoid overlapping infobox on mobile

- src/modules/infobox/components/ImportContent.vue
- src/modules/infobox/components/ImportContentResultItem.vue
- src/modules/menu/components/search/SearchBar.vue
- src/modules/menu/components/search/SearchResultCategory.vue
- src/modules/menu/components/search/SearchResultList.vue
- src/modules/menu/components/search/SearchResultListEntry.vue
- src/scss/webmapviewer-bootstrap-theme.scss
@pakb if you agree I would change the hover list item background color of other component to the new variable `$hover-selection` created here ?
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-search-ui/index.html)
> Fixed search bar category background

- src/modules/map/MapModule.vue
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumPopover.vue
Right click on the 3D map now shows the same location popup as in 2D (and it is correctly clamped/anchored to where the click happened)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-3059_location_popup_in_3d/index.html)
> BGDIINF_SB-3059 : add location popup for 3D

- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/utils/militaryGridProjection.js
- tests/e2e-cypress/integration/mouseposition.cy.js
- tests/e2e-cypress/support/commands.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-3161_consrtaint_view_to_lv95/index.html)
> BGDIINF_SB-3161 : constrains OL to only show map in LV95 extent

- src/modules/infobox/components/ImportContent.vue
- src/modules/infobox/components/ImportContentResultList.vue
- tests/e2e-cypress/integration/importTool.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3172-local-file-import-ui/index.html)
> BGDIINF_SB-3172 : Add local file import UI

- src/api/layers/GeoAdminAggregateLayer.class.js
- src/api/layers/GeoAdminWMSLayer.class.js
- src/api/layers/GeoAdminWMTSLayer.class.js
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-3197_wms_layer_issues/index.html)
> BGDIINF_SB-3197 : fix issue with serverLayerId being not used correctly

- src/api/layers/AbstractLayer.class.js
- src/api/layers/ExternalGroupOfLayers.class.js
- src/api/layers/ExternalLayer.class.js
- src/api/layers/ExternalWMSLayer.class.js
- src/api/layers/ExternalWMTSLayer.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/WMTSCapabilitiesParser.class.js
- src/api/layers/layers-external.api.js
- src/api/layers/wms-capabilities.class.js
- src/api/layers/wmts-capabilities.class.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/infobox/utils/external-provider-parsers.js
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/__tests__/LayerParamConfig.class.spec.js
- src/store/index.js
- src/store/modules/__tests__/layers.store.spec.js
- src/store/modules/layers.store.js
- src/store/plugins/external-layers.plugin.js
- src/utils/__tests__/legacyLayerParamUtils.spec.js
- src/utils/legacyLayerParamUtils.js
- tests/e2e-cypress/integration/legacyParamImport.cy.js
TODO in follow up PRs:
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3180-ext-layers/index.html)
> BGDIINF_SB-3180: External Layer refresh attributes on reload

- src/api/layers/__tests__/WMSCapabitliesParser.class.spec.js
- src/api/layers/__tests__/WMTSCapabitliesParser.class.spec.js
- src/api/layers/__tests__/wms-geoadmin-sample.xml
- src/api/layers/__tests__/wmts-ogc-sample.xml
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3180-ext-layers-tests/index.html)
> BGDIINF_SB-3180: Added unit tests for external WMTS and WMS parsing

- src/modules/map/components/footer/backgroundSelector/BackgroundSelectorSquared.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_replace_deprecated_sass/index.html)
> replace soon-to-be-deprecated division by a function in Sass

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/menu/components/advancedTools/ImportFile/ImportFile.vue
- src/modules/menu/components/advancedTools/ImportFile/ImportFileButtons.vue
- src/modules/menu/components/advancedTools/ImportFile/ImportFileLocalTab.vue
- src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
- src/modules/menu/components/advancedTools/ImportFile/utils.js
- src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
- src/modules/menu/components/advancedTools/MenuAdvancedToolsListItem.vue
- src/modules/menu/components/advancedTools/importButton.js
- src/scss/webmapviewer-bootstrap-theme.scss
- src/store/modules/ui.store.js
- src/utils/utils.js
- tests/e2e-cypress/integration/importTool.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3194-import-tool-ui-p2/index.html)
> BGDIINF_SB-3194: Implement new UI for import external KML/GPX file.

- src/modules/menu/components/LayerCatalogue.vue
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- tests/e2e-cypress/integration/header.cy.js
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/integration/topics.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3194-import-tool-ui-p4/index.html)
> BGDIINF_SB-3194: Renaming generic catalogue from `topic` to `catalogue`

- README.md
- tests/README.md
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3186-cy-cloud-docu/index.html)
> BGDIINF_SB-3186: Updated cypress cloud documentation

- scripts/generate-i18n-files.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/menu/components/LayerCatalogue.vue
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/advancedTools/ImportCatalogue/ProviderList.vue
- src/modules/menu/components/advancedTools/ImportCatalogue/useProviders.js
- src/modules/menu/components/menu/MenuSection.vue
- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- src/utils/TextSearchMarker.vue
- src/utils/utils.js
Now we have a search bar for the geocatalog.
Also improved menu items colors
The active layers and geocatalog menu were always white which make it hard
to differentiate the menu title from the menu content.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-73-search-geo-catalogue/index.html)
> PB-73: Added geo catalogue and import tool search bar

- src/modules/menu/components/LayerCatalogue.vue
This commit has been forgotten in the merge of #590
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-73-search-geo-catalogue/index.html)
> PB-73: code improvement from review of #590

- src/modules/menu/components/share/MenuShareSocialNetworks.vue
- src/setup-fontawesome.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-xitter/index.html)
> Changing the twitter logo from bird to X

- src/modules/infobox/InfoboxModule.vue
Cleaned up some left over of the import overlay.
Fixed the pointer on the infobox bar which react on click.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-95-infobox-cleanup/index.html)
> PB-95: Clean up infobox

- src/modules/menu/components/search/SearchResultListEntry.vue
- src/utils/components/TextSearchMarker.vue
- tests/cypress/tests-e2e/search/search-results.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-116-search-bar-emphasize/index.html)
> PB-116: Added text emphasize in search bar results

- src/modules/map/components/cesium/CesiumMap.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-150_3d_shadows_on_buildings/index.html)
> PB-150 : add shadows on 3D buildings

- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/menu/components/advancedTools/ImportCatalogue/ProviderUrl.vue
- src/store/modules/layers.store.js
- tests/cypress/fixtures/import-tool/wmts-geo-admin-get-capabilities.xml
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
- tests/cypress/tests-e2e/layers.cy.js
Follow up of #615 
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-88-import-e2e-2/index.html)
> PB-88: Completed E2E tests for external WMS/WMTS layers

- src/utils/__tests__/kmlUtils.spec.js
- src/utils/kmlUtils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-114-kml-5/index.html)
> PB-114: Added kml utils unit tests and fix small edge case issues

- adr/2024_01_31_drawing_icon_size.md
Based on discussion with @boecklic  and @pakb 
Work is done in #641 
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-114-icon-size/index.html)
> PB-266: Added ADR about drawing text and icon size

- src/modules/map/components/LocationPopupCopySlot.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-248-position_popup_copy_button_issue/index.html)
> PB-248: Fix Clipboard update issue for position popup

- src/modules/menu/components/menu/MenuTray.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-prod-menu/index.html)
> Added menu advanced tool on prod and remove print menu on prod

- src/modules/infobox/components/FeatureDetail.vue
- src/modules/infobox/components/FeatureList.vue
- src/modules/map/components/WarningRibbon.vue
- src/modules/map/components/footer/MapFooterAppCopyright.vue
- src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
- src/modules/map/components/openlayers/utils/markerStyle.js
- src/scss/variables-admin.module.scss
- src/scss/webmapviewer-bootstrap-theme.scss
- src/store/modules/features.store.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-123_change_color_hovered_feature/index.html)
> PB-123 : Change color of hovered feature

- package-lock.json
- package.json
- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- src/modules/menu/scss/menu-items.scss
- src/store/modules/__tests__/layers.store.spec.js
- src/store/modules/layers.store.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/layers.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-238_drag_drop_layer_ordering/index.html)
> PB-238 : drag&drop reordering of active layers

- src/api/topics.api.js
- src/store/plugins/load-layersconfig-on-lang-change.js
Load the topics in parallel with layer config
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-259-performance-config-topic/index.html)
> PB-259: Improve topic parsing at startup

- src/modules/menu/components/share/MenuShareSocialNetworks.vue
- src/setup-fontawesome.js
- tests/cypress/tests-e2e/mouseposition.cy.js
- tests/cypress/tests-e2e/shareShortLink.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-282-location_share_whats_app/index.html)
> PB-282: Location share Whats App

- src/main.js
- src/modules/menu/components/topics/MenuTopicSection.vue
- vite.config.mts
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-259-topics-composition/index.html)
> PB-259: Converted topic section into composition API

- tests/cypress/tests-e2e/layers.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_try_fix_drag_drop_test/index.html)
> Skip flaky drag&drop e2e test

- src/modules/map/components/cesium/CesiumToolbox.vue
- src/views/MapView.vue
- vite.config.mts
Before
```
dist/production/v1.8.0-beta.4/assets/OpenLayersMap-G4yf78Ek.css                                 1.24 kB │ gzip:   0.51 kB
dist/production/v1.8.0-beta.4/assets/CesiumMap-rSwnPDY_.css                                    27.58 kB │ gzip:   6.10 kB
dist/production/v1.8.0-beta.4/assets/index-fIQOV_l-.css                                     1,816.31 kB │ gzip: 174.01 kB
dist/production/v1.8.0-beta.4/assets/__vite-browser-external-YvMT15k-.js                        0.03 kB │ gzip:   0.05 kB
dist/production/v1.8.0-beta.4/assets/identifyOnVectorLayer-2QNEbx8e.js                         10.01 kB │ gzip:   3.71 kB
dist/production/v1.8.0-beta.4/assets/OpenLayersMap-D4ysht83.js                                906.42 kB │ gzip: 251.63 kB
dist/production/v1.8.0-beta.4/assets/index-aHcbgfme.js …
```
> PB-259: Manual chunks for better startup performance

- src/modules/infobox/InfoboxModule.vue
As a preliminary work for the showtooltip implementation, we have refactored the Infobox Module to the composition API. 
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-190-showtooltip-implementation/index.html)
> PB-190: Refactor Infobox Module for Composition API

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/useKmlDataManagement.composable.js
When exiting the drawing, we could have a race condition between the closing
save and pending debounced save. Sometimes a pending debounce save, not started
was started after the closing and closing save, which saved an empty kml because
the drawing layer would have been removed.
This was making some test failing time to time and could also have been an
issue for a real user if he would close the drawing too quickly.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-save-drawing/index.html)
> Fix save drawing race condition

- src/modules/infobox/components/FeatureDetail.vue
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/map/components/LocationPopupPosition.vue
- src/modules/map/components/LocationPopupShare.vue
- src/utils/components/CoordinateCopySlot.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-244-coordinate-display-typing-issue/index.html)
> PB-244: Fix typing issues of props

- src/modules/infobox/components/FeatureDetail.vue
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/map/components/LocationPopup.vue
- src/utils/components/CoordinateCopySlot.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-244-coordinate-display-css-styling-and-text-selectability/index.html)
> PB-244: Coordinate display css styling and text selectability

- src/api/features/features.api.js
- src/router/storeSync/LayerParamConfig.class.js
- src/store/modules/position.store.js
- src/utils/geoJsonUtils.js
- tests/cypress/fixtures/layers.fixture.json
- tests/cypress/support/utils.js
- tests/cypress/tests-e2e/featurePreSelection.cy.js
We added an additional possible custom parameter which allows to select features which IDS are known from the URL, like the old {bod-layer-id} parameter.
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-190_implement-preselectedfeature-feature/index.html)
> PB-190 : Implement feature pre selection

- src/modules/infobox/InfoboxModule.vue
- src/modules/map/MapModule.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/footer/MapFooter.vue
- src/modules/map/components/footer/MapFooterAppCopyright.vue
- src/modules/map/components/footer/MapFooterAppVersion.vue
- src/modules/menu/MenuModule.vue
- src/views/EmbedView.vue
- src/views/MapView.vue
- tests/cypress/tests-e2e/embed.cy.js
[Test link /embed](https://sys-map.dev.bgdi.ch/preview/feat-pb-316-embed-footer/index.html#/embed)
[Test link /map](https://sys-map.dev.bgdi.ch/preview/feat-pb-316-embed-footer/index.html)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-316-embed-footer/index.html)
> PB-316: Implemented correct map footer for /embed view

- src/modules/map/components/footer/MapFooterAppVersion.vue
- src/store/modules/ui.store.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-version/index.html)
> Made the version more visible on test sites and made it invisible on prod site

- src/modules/menu/components/share/MenuShareEmbed.vue
Use the same style as for the other menu list items.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-315-embed-share/index.html)
> PB-315: Normalized the share embed button

- src/modules/map/components/openlayers/OpenLayersMouseTracker.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-325-draw_rectangle_when_shift_select/index.html)
> PB-325: Add styling to openlayers drag zoom

- src/modules/map/components/toolbox/FullScreenButton.vue
- src/modules/map/components/toolbox/GeolocButton.vue
- src/modules/map/components/toolbox/TimeSliderButton.vue
- src/modules/map/components/toolbox/Toggle3dButton.vue
- src/modules/map/components/toolbox/ZoomButtons.vue
- src/utils/useTippyTooltip.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-315-toolbox-tooltip/index.html)
> PB-315: Normalized the toolbox right tooltips

- src/api/layers/ExternalGroupOfLayers.class.js
- src/api/layers/ExternalLayer.class.js
- src/api/layers/ExternalWMSLayer.class.js
- src/api/layers/ExternalWMTSLayer.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/router/storeSync/storeSync.config.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-103_getfeatureinfo_cap_parsing/index.html)
> PB-103 : add parsing of getFeatureInfo capabilities for external layers

- package-lock.json
- package.json
- src/modules/drawing/components/useModifyInteraction.composable.js
- src/modules/infobox/components/FeatureAreaInfo.vue
- src/modules/infobox/components/FeatureDetail.vue
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/map/components/common/mouse-click.composable.js
- src/store/modules/features.store.js
- tests/cypress/tests-e2e/drawing.cy.js
And use turfJS instead of OL to calculate the area of the geometry
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-74_geometry_as_input/index.html)
> Change FeatreAreaInfo to accept geom as input

- package-lock.json
- package.json
- src/utils/extentUtils.js
- src/utils/geoJsonUtils.js
An extent utils to create some arbitrary sized extent around a given coordinate A GeoJSON utils that extract a single coordinate from any type of feature (to position the tooltip correctly)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-103_add_two_utils/index.html)
> PB-103 : adding two new utils to help create getFeatureInfo requests

- .gitignore
- src/api/layers/LayerTimeConfig.class.js
- src/modules/drawing/useKmlDataManagement.composable.js
- src/modules/menu/components/LayerCatalogue.vue
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/modules/menu/components/advancedTools/ImportFile/utils.js
- src/router/storeSync/LayerParamConfig.class.js
- src/store/modules/__tests__/layers.store.spec.js
- src/store/modules/layers.store.js
- src/store/modules/search.store.js
- src/store/plugins/load-geojson-style-and-data.plugin.js
- src/store/plugins/load-gpx-data.plugin.js
- src/store/plugins/load-kml-data.plugin.js
- src/utils/legacyLayerParamUtils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-332-duplicate-layer/index.html)
> PB-332: Allow duplicate layers in layer list

- src/utils/kmlUtils.js
External KML don't have the `type` property and we should not add the
editable feature for those otherwise we breaks their styling.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-external-kml/index.html)
> PB-359: Fix external KML rendering.

- package-lock.json
- package.json
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/utils/useTippyTooltip.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/3d/layers.cy.js
- tests/cypress/tests-e2e/compareSlider.cy.js
- tests/cypress/tests-e2e/drawing.cy.js
- tests/cypress/tests-e2e/importToolFile.cy.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
- tests/cypress/tests-e2e/layers.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-332-duplicate-layer-button/index.html)
> PB-332: Added duplicate layer button to time series layers

- src/api/features/features.api.js
- src/store/plugins/click-on-map-management.plugin.js
- tests/cypress/fixtures/external-wms-getcap-1.fixture.xml
- tests/cypress/fixtures/external-wms-getcap-2.fixture.xml
- tests/cypress/tests-e2e/layers.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-103_identify_external_layers/index.html)
> PB-103 : identify on external layers

- src/modules/menu/components/LayerCatalogue.vue
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/utils/components/TextSearchMarker.vue
- src/utils/components/TextTruncate.vue
- tests/cypress/fixtures/layers.fixture.json
- tests/cypress/tests-component/TextTruncate.cy.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
- tests/cypress/tests-e2e/layers.cy.js
On the external layer catalogue as well as the geo catalogue, long entry list
where not truncated and no tippy was added.
Also changed this tippy theme to use the default one and put it on the right.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-divers-ui/index.html)
> Divers UI bugs and improvments

- src/api/layers/AbstractLayer.class.js
- src/api/layers/ExternalLayer.class.js
- src/api/layers/GPXLayer.class.js
- src/api/layers/GeoAdminLayer.class.js
- src/api/layers/KMLLayer.class.js
- src/api/layers/__tests__/KMLLayer.class.spec.js
- src/api/layers/__tests__/WMSCapabitliesParser.class.spec.js
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-324-show-layer-info-button-without-legend/index.html)
> PB-324: Show layer info button without legend

- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/print/MenuPrintSection.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-281-print-enum/index.html)
> PB-281: Removed print layout enumaration and removed dev site guard on the menu

- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- tests/cypress/support/drawing.js
- tests/cypress/tests-e2e/drawing.cy.js
simplifying in the process the code of FeatureStyleEdit and removing all "Cypress only" code here
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_add_retryability_drawing_test/index.html)
> Add retryabiity for drawing test

- src/modules/map/components/toolbox/TimeSlider.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/scss/webmapviewer-bootstrap-theme.scss
- src/store/modules/layers.store.js
- src/utils/layerUtils.js
We : 
- Allow users to use the time slider across the whole slider bar, even if there is no data
- Add a specific styling for years with incomplete data
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-318-timeslider-over-incomplete-data/index.html)
> PB-318: feature : timeslider over incomplete data

- src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-358-complex-geometry-feature-infobox-default-display/index.html)
> PB-358: Fix Complex geometry feature infobox default display

- package-lock.json
- package.json
Our CI image has updated its NPM version "silently" and we should also be moving to the newest version sooner than later
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_update_npm_to_v10/index.html)
> Update project requirement, now needing NPM v10

- src/modules/menu/components/share/MenuShareEmbed.vue
- Moved the code to composition api.
- Added copy button to copy the content of the iframe example
- On input click select the whole input, which make easier to copy
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-393-embed-iframe-web/index.html)
> PB-393: Added copy button for embed iframe example

- src/modules/map/components/cesium/CesiumMap.vue
- src/store/modules/cesium.store.js
- tests/cypress/tests-e2e/3d/layers.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/data-bgdidic-2749-poc-master-tileset/index.html)
> BGDIDIC-2749: poc with a master tileset for the vegetation

- src/api/print.api.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-397-tempo-print-int-backend-revert/index.html)
> PB-397: Revert back print backend to correct staging on DEV

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/map/components/toolbox/TimeSlider.vue
- tests/cypress/tests-e2e/timeSlider.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-424-time-slider-year-entry-button/index.html)
> PB-424: Time slider year entry button

- src/store/modules/search.store.js
Some layers id might be of 3 words separated by dot (e.g. ch.bfe.energieforschung)
which could also be a valid what3words address, therefore we need a fallback
to service search.
Of course now we still the issue if a valid what3words is also a valid layer
ID, the search will always jump to the what3words location, but hopefully this
is quite un-probable.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-426-search/index.html)
> PB-426: Fallback to service search for invalid what3words

- src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-408-wms-endpoint-bl/index.html)
> PB-408: Add wms endpoint of BL to external provider list

- src/modules/menu/components/LayerDescriptionPopup.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-432-layer-legend-2/index.html)
> PB-432: Allow text selection in layer info popup

- src/api/features/EditableFeature.class.js
- src/api/icon.api.js
- src/modules/drawing/components/DrawingMarkerInteraction.vue
- src/modules/drawing/components/DrawingSelectInteraction.vue
- src/modules/drawing/components/useDrawingModeInteraction.composable.js
- src/modules/drawing/lib/export-utils.js
- src/modules/drawing/useKmlDataManagement.composable.js
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/map/components/cesium/CesiumKMLLayer.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/store/modules/features.store.js
- src/utils/__tests__/kmlUtils.spec.js
- src/utils/__tests__/legacyKmlUtils.spec.js
- src/utils/__tests__/webmapviewerOffsetTestKml.kml
- src/utils/featureStyleUtils.js
- src/utils/kmlUtils.js
- tests/cypress/tests-e2e/drawing.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-414-marker-overlapping-title/index.html)
> PB-414: marker overlapping title

- src/modules/menu/components/settings/HelpLink.vue
- src/modules/menu/components/settings/LinksToolbar.vue
- vite.config.mts
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-435-help/index.html)
> PB-435: Added help link

- src/api/layers/GeoAdmin3DLayer.class.js
- src/api/layers/GeoAdminAggregateLayer.class.js
- src/api/layers/GeoAdminGeoJsonLayer.class.js
- src/api/layers/GeoAdminGroupOfLayers.class.js
- src/api/layers/GeoAdminLayer.class.js
- src/api/layers/GeoAdminVectorLayer.class.js
- src/api/layers/GeoAdminWMSLayer.class.js
- src/api/layers/GeoAdminWMTSLayer.class.js
- src/api/layers/layers.api.js
- src/modules/map/components/cesium/CesiumInternalLayer.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/router/storeSync/__tests__/layersParamParser.spec.js
- src/store/modules/__tests__/layers.store.spec.js
- src/store/plugins/load-layersconfig-on-lang-change.js
- src/utils/__tests__/legacyLayerParamUtils.spec.js
- src/utils/layerUtils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-425-3d-external-layer/index.html)
> PB-425: Implement external WMS external layer in 3D

- src/modules/i18n/components/LangButton.vue
- src/modules/i18n/components/LangSwitchToolbar.vue
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/LocationPopupPosition.vue
- src/modules/map/components/LocationPopupShare.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/settings/HelpLink.vue
- src/modules/menu/components/settings/MenuLangSelector.vue
- src/modules/menu/components/settings/MoreInfo.vue
- src/modules/menu/components/settings/ReportProblemButton.vue
- src/modules/menu/components/settings/feedback/FeedbackButton.vue
- src/modules/menu/components/share/MenuShareSection.vue
- src/modules/menu/components/share/MenuShareSocialNetworks.vue
- src/scss/variables.module.scss
- src/utils/components/CoordinateCopySlot.vue
- Location popup improvement and size fix, it is a bit less condense but it improves the click and text selection on mobile device
- Before
- After
- Language selector and report a problem
- Before
- After
- Input buttons on mobile are now a bit bigger easing their click on touch 
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-icon-size-mobile/index.html)
> PB-503: Several UI in menu improvements, especially on mobile

- src/modules/menu/components/settings/ReportProblemButton.vue
- src/modules/menu/components/settings/feedback/FeedbackButton.vue
- src/utils/components/SimpleWindow.vue
- src/utils/composables/useFieldValidation.js
- tests/cypress/tests-e2e/feedback.cy.js
- tests/cypress/tests-e2e/reportProblem.cy.js
The issue with the modal is that the user loose its content when clicking outside
of the modal !
Once the PR #815 is done we can make the window movable.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-449-modal/index.html)
> PB-449: Removed the modal for report a problem and give feedback

- src/api/layers/AbstractLayer.class.js
- src/api/layers/ExternalLayer.class.js
- src/api/layers/ExternalWMTSLayer.class.js
- src/api/layers/GeoAdminLayer.class.js
- src/api/layers/LayerTimeConfig.class.js
- src/api/layers/LayerTimeConfigEntry.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/WMTSCapabilitiesParser.class.js
- src/api/layers/__tests__/WMTSCapabitliesParser.class.spec.js
- src/api/layers/__tests__/wmts-ogc-sample.xml
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
- src/router/storeSync/LayerParamConfig.class.js
- src/store/plugins/external-layers.plugin.js
- src/utils/__tests__/numberUtils.spec.js
- src/utils/layerUtils.js
- src/utils/numberUtils.js
- tests/cypress/fixtures/import-tool/wmts-geo-admin-get-capabilities.xml
- tests/cypress/tests-e2e/importToolMaps.cy.js
TODO in separate PR:
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-496-external-wmts-3d/index.html)
> PB-496: External WMTS layer in 3d

- src/api/layers/AbstractLayer.class.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/cesium/utils/addImageryLayer-mixins.js
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/store/modules/layers.store.js
- src/store/plugins/external-layers.plugin.js
- src/store/plugins/load-geojson-style-and-data.plugin.js
- src/store/plugins/load-gpx-data.plugin.js
- src/store/plugins/load-kml-data.plugin.js
For this I needed to be able to add/remove errors per layer as this error is
only for 3D.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-505-projection-error/index.html)
> PB-505: Added error when external WMTS layer don't support WGS84

- src/modules/map/components/cesium/CesiumPopover.vue
a little omission on my part, the tooltip wasn't working since last changes made on the floating tooltip
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-471_fix_3d_location_popup/index.html)
> PB-471 : fix 3D location popup

- src/modules/map/components/cesium/CesiumGeolocationFeedback.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/openlayers/OpenLayersAccuracyCircle.vue
- src/utils/styleUtils.js
There's still issues when keeping the geolocation active and swapping between 2D and 3D, but we might be able to "live with it" and have a ticket to fix that after go-live (ticket [here](https://jira.swisstopo.ch/browse/PB-559))
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-521_3d_geoloc_feedback/index.html)
> PB-521 : add geolocation feedback on Cesium

- src/store/plugins/geolocation-management.plugin.js
While testing geolocation it often results to really poor accuracy, sometimes
up to several kilometers !
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-521-goelocation-high-precision/index.html)
> PB-521: Enabled geolocation high accuracy

- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
Issue: The transparency slider did not change the opacity in real time when users were moving the slider, only applying the changes when it was released
Fix: When clicking on the slider, it sets an interval which updates the opacity as long as we're handling the slider. This interval is set to 100ms, which allows to see the changes happen often enough to work, without burdening the backend with too much commits. We also reduce the number of commits by never committing the same value as the one stored.
If this puts too much strain on the backend, we can wait until post prod to find a more elegant solution.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-534-real-time-opacity-change/index.html)
> PB-534: transparency slider works in real time

- src/modules/map/components/MapPopover.vue
- src/modules/map/components/toolbox/TimeSlider.vue
- src/scss/exports.js
- src/scss/variables.module.scss
- src/utils/geoJsonUtils.js
- tests/cypress/tests-e2e/timeSlider.cy.js
- Fixed issue that features with a geometry collection could not caclulate the popver location which would thus not show
- Fixed issue that timeslider / dropdown height was not accounted for for initial positioning of infobox
- Replace time slider with dropdown on phones
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-575-html-popup-tooltip-issues/index.html)
> PB-575: Html popup tooltip issues

- src/modules/menu/components/settings/ReportProblemButton.vue
- src/modules/menu/components/settings/feedback/FeedbackButton.vue
- src/store/modules/ui.store.js
- src/utils/components/SimpleWindow.vue
- tests/cypress/tests-e2e/feedback.cy.js
- tests/cypress/tests-e2e/reportProblem.cy.js
The first idea was to use movable but this cause trouble with the content of
the window not being at a fix size like for the tooltip but dependent on the
window content.
As simpler alternative I added the minimize button which let the user minimize
the window which is for the use case good enough.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-449-move-window/index.html)
> PB-449: Add a minimize button to give feedback and report problem

- src/modules/infobox/InfoboxModule.vue
- src/utils/components/ZoomToExtentButton.vue
The infobox only had the profile title but not on object or in drawing.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-infobox-title/index.html)
> Add title to infobox

- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
Layer that are telling, with a label at bottom, when was their last update weren't displayed in a manner that permit this label to be shown (it was out of scope of the map viewport with how the request was built)
This fixes two things :
- Limits the request to our own WMS to LV95 extent
- Tells OpenLayers to not request extra information around (gutter) but keep a ratio of 1:1 when requesting a WMS (this way the update label can be inside the viewport)
Good candidate to test : `ch.bazl.luftfahrthindernis`
[Test link with layer](https://sys-map.dev.bgdi.ch/preview/bug_pb-589_no_last_update_wms_label/index.html?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch. …
> PB-589 : limit WMS request to LV95 extent

- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
- src/modules/menu/components/settings/HelpLink.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-546-print-overlay/index.html)
> PB-546: Put print overlay always on top

- src/modules/menu/components/settings/HelpLink.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-help-links/index.html)
> Updated the help link to the new help from the goe.admin.ch CMS

- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
- src/modules/menu/components/settings/HelpLink.vue
This include the correct help link to the new help page
[Test link](https://sys-map.int.bgdi.ch/preview/develop/index.html)
> New Release v1.26.0 - #minor

- index.html
- src/modules/map/components/toolbox/TimeSlider.vue
- src/modules/map/components/toolbox/TimeSliderButton.vue
The key press is only effective when the map is in focus or the time slider
button or the timeslisder play button. This ensure that the key press doesn't
interfere with other UI component like the search input field for example.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-643-timeslider-keyboard/index.html)
> PB-643: Implement left/right key press to move time slider

- src/modules/map/components/openlayers/utils/styleFromLiterals.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-646-symbolizaion-geojson/index.html)
[Test link with snow layer](https://sys-s.dev.bgdi.ch/6y26qfj3ehyu)
Sample:
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-646-symbolizaion-geojson/index.html)
> PB-646: Fix logic to set value in style from literal.

- src/router/storeSync/LayerParamConfig.class.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-default-opacity/index.html)
> Fix default opacity for external WMS/WMTS layer

- src/api/features/features.api.js
looping on sub-layers and bunching together any fulfilled getFeatureInfo requests.
[Test link with functioning group of layers (AG)](https://sys-map.dev.bgdi.ch/preview/bug_pb-681_identify_on_external_group_of_layers/index.html?lang=de&center=2648755.62,1247152.76&z=3&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f;ch.bav.haltestellen-oev,f;ch.swisstopo.swisstlm3d-wanderwege,f;ch.vbs.schiessanzeigen,f;ch.astra.wanderland-sperrungen_umleitungen,f;WMS|https://wms.geo.ag.ch/public/ows?SERVICE=WMS%26|ch_ag_geo_alg_amphibien92&featureInfo=default)
[Test link with non-functioning (bad response) layer from ticket (geodienste)](https://sys-map.dev.bgdi.ch/preview/bug_pb-681_identify_on_external_group_of_layers/index.htm …
> PB-681 : add support for group of external layers getFeatureInfo

- src/modules/map/components/footer/MapFooterAppVersion.vue
This helps to know when the deployment is done as it provide a easy visual feedback.
[Test link](https://sys-map.int.bgdi.ch/preview/feat-version/index.html)
> Display also the version on prod staging - #patch

- src/api/feedback.api.js
[Test link](https://sys-map.int.bgdi.ch/preview/fix-742-use-permalink/index.html)
> PB-742: Use permalink on report problem email - #patch

- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
- src/store/modules/ui.store.js
- src/utils/components/DragDropOverlay.vue
- src/views/MapView.vue
- tests/cypress/tests-e2e/featureSelection.cy.js
[Test link](https://sys-map.int.bgdi.ch/preview/pb-495-drag-and-drop-files/index.html)
> PB-495 : drag and drop KML files - #patch

- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/toolbox/MapToolbox.vue
- tests/cypress/tests-e2e/toolboxRight.cy.js
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-723-full-screen/index.html)
> PB-723: Keep toolbox buttons in full screen mode - #patch

- src/router/storeSync/storeSync.routerPlugin.js
During the startup if the app.isReady was set too early, the initial URL parsing
was not done which would have left the application blank.
We observed such behavior on the prod deployment which was only randomly reproducable.
I suspect that this was the issue but cannot tell for sure.
I also improved logging of the startup procedure.
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-747-logs/index.html)
> PB-747: Fix potential startup race condition - #patch

- src/utils/logging.js
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-747-logs-2/index.html)
> PB-747: Enabled logs on PROD to try to understand the blank screen issue - #patch

- src/modules/map/components/CompareSlider.vue
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-775-compared-layer-name/index.html)
> PB-775 : show compared layer name when slider is hovered/used - #patch

- src/modules/drawing/lib/export-utils.js
- src/utils/kmlUtils.js
- src/utils/ol/format/KML.js
a fix has been published on OL repo here  : https://github.com/openlayers/openlayers/pull/15964
While waiting for the process of merging/release, I've added a copy of the file I fixed on our repo.
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-753-kml-no-labels/index.html)
> PB-753 : fix an issue in OL with KML placemark with an icon scale of 0 - #patch

- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
[Test link](https://sys-map.int.bgdi.ch/preview/pb-846-printarea-unchanged/index.html)
> PB-486: Update print area when print layout changed. - #minor

- src/modules/infobox/components/styling/FeatureStyleEdit.vue
[Test link](https://sys-map.int.bgdi.ch/preview/pb-857-delete-key-to-delete/index.html)
> PB-857: Enable Delete key to delete drawing. - #minor

- src/api/print.api.js
- src/modules/map/components/openlayers/utils/usePrint.composable.js
- src/modules/menu/components/print/MenuPrintSection.vue
[Test link](https://sys-map.int.bgdi.ch/preview/pb-805-better-error-message-too-big-print-spec/index.html)
- Add more specific error message based on the error
[Test link](https://sys-map.int.bgdi.ch/preview/pb-805-better-error-message-too-big-print-spec/index.html)
> PB-805: Add error message for failed printing. - #minor

- src/scss/diemo.scss
- src/scss/webmapviewer-bootstrap-theme.scss
so that electric car charging location can be styled like they were on mf-geoadmin3
[Test link with diemo layer](https://sys-map.int.bgdi.ch/preview/fix-pb-830-diemo-popup/index.html?layers=ch.bfe.ladestellen-elektromobilitaet)
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-830-diemo-popup/index.html)
> PB-830 : add specific (S)CSS for Diemo popup - #patch

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/map/components/footer/MapFooterAppCopyright.vue
[Test link](https://sys-map.int.bgdi.ch/preview/feat-pb-898-impressum/index.html)
> PB-898 Add a legal notice link to the footer - #minor

- src/api/print.api.js
[Test link](https://sys-map.int.bgdi.ch/preview/fix-error-print-user-draw/index.html)
> Add replacer on JSON.stringify on checking print spec size. - #patch

- package-lock.json
- package.json
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/modules/map/components/footer/backgroundSelector/BackgroundSelectorSquared.vue
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/LayerCatalogueItem.vue
- src/scss/main.scss
- src/utils/components/ErrorWindow.vue
- src/utils/components/ModalWithBackdrop.vue
- src/utils/components/SimpleWindow.vue
- src/utils/components/WarningWindow.vue
- tests/cypress/tests-e2e/reportProblem.cy.js
Our code is ready for SASS 1.77.8 and the new rule https://sass-lang.com/d/mixed-decls Bootstrap isn't, so while waiting for them to update their SASS code, I've reverted SASS to 1.77.6, just prior to the rule being added
[Test link](https://sys-map.int.bgdi.ch/preview/fix-sass-warnings/index.html)
> Fix SASS warning from code and revert to 1.77.6 waiting on bootstrap - #patch

- src/api/file-proxy.api.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-735-dropbox-url/index.html)
> PB-735: Replace dl=0 to dl=1 for dropbox direct download

- src/modules/infobox/components/FeatureAreaInfo.vue
- src/utils/geodesicManager.js
- tests/cypress/tests-e2e/drawing.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-869-different-area-calculation/index.html)
> PB-859: Use the same approach to compute polygon area.

- src/api/search.api.js
- src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
- src/modules/map/components/openlayers/OpenLayersMarker.vue
- src/modules/map/components/openlayers/OpenLayersPinnedLocation.vue
- src/modules/map/components/openlayers/utils/useVectorLayer.composable.js
- src/store/modules/search.store.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-773-auto-select-feature-from-search/index.html)
> PB-773: Auto select the feature from search result.

- src/api/file-proxy.api.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1017-linting/index.html)
> PB-1017 : use of camelCase (and not snake_case)

- src/router/legacyPermalinkManagement.routerPlugin.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-742-malformed-link/index.html)
> PB-742: Do not decodeURI twice.

- src/modules/map/components/cesium/CesiumMap.vue
- src/scss/main.scss
that fixes the issues we had with touch device navigation in 3D
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-722-cesium-touch/index.html)
> PB-722 : import cesium CSS globally

- src/api/search.api.js
- src/store/modules/features.store.js
- src/store/modules/search.store.js
- tests/cypress/tests-e2e/importToolFile.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1023-enable-search-inside-kml/index.html)
> PB-1023: enable search inside kml

- package-lock.json
- package.json
- src/modules/map/components/openlayers/utils/useDragBoxSelect.composable.js
- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
- src/utils/identifyOnVectorLayer.js
- src/utils/layerUtils.js
- tests/cypress/tests-e2e/featureSelection.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-875-ctrl-right-click-select-multiple-features/index.html)
> PB-875: CTRL-Left click selection features for vector (KML/GPX/GeoJSON) and multiple elements

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/map/components/footer/MapFooter.vue
- src/modules/map/components/toolbox/FullScreenButton.vue
- tests/cypress/tests-e2e/toolboxRight.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-423-full-screen-esc-to-leave/index.html)
> PB-423: full screen esc to leave

- src/modules/menu/components/search/SearchBar.vue
- src/router/storeSync/SearchParamConfig.class.js
- src/router/storeSync/abstractParamConfig.class.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/search.store.js
- tests/cypress/tests-e2e/featureSelection.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
- tests/cypress/tests-e2e/search/search-results.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-951-not-store-swisssearch/index.html)
> PB-951: do not store swisssearch param in url

- src/store/modules/ui.store.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1066-duplicated-error/index.html)
> PB-1066: Fix Duplicated Error

- src/modules/drawing/components/DrawingTooltip.vue
- src/modules/drawing/lib/drawingUtils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-603-balloon-drawing-drag-mouse-hover/index.html)
> PB-603: fix hover selected vertex and feature

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1046-update-warning-message/index.html)
> PB-1046: Update warning message.

- src/modules/map/components/CompareSlider.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-789-compare-slider-description-cut-off/index.html)
> PB-789: fix compare slider description cut off

- src/modules/infobox/components/FeatureList.vue
- src/store/index.js
- src/store/modules/features.store.js
- src/store/plugins/update-selected-features.plugin.js
- tests/cypress/tests-e2e/featureSelection.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-623-sync-layer-selected-feature/index.html)
> PB-623: sync features when layers are updated

- src/store/modules/layers.store.js
- tests/cypress/tests-e2e/layers.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1128-permalink-problem/index.html)
> PB-1128: fix permalink custom attributes

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/menu/components/help/MoreInfo.vue
- tests/cypress/tests-e2e/header.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1042-replace-more-information-with-news/index.html)
> PB-1042: replace more information with news

- src/modules/menu/components/header/HeaderWithSearch.vue
- tests/cypress/fixtures/topics.fixture.json
- tests/cypress/tests-e2e/header.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-774-do-not-reset-bg-layer/index.html)
> PB-774: Reset to default background layer when clicking on the logo

- src/utils/components/PrintButton.vue
- tests/cypress/tests-e2e/featureSelection.cy.js
- tests/cypress/tests-e2e/print.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1190-print-feature/index.html)
> PB-1190: print feature

- src/modules/map/components/cesium/CesiumInteractions.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/common/useDragFileOverlay.composable.js
- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1295-3d-drag-n-drop/index.html)
> PB-1295 : add drag&drop support for 3D viewer

- tests/cypress/fixtures/html-popup.fixture.html
- tests/cypress/fixtures/infobox.fixture.html
- tests/cypress/tests-e2e/infobox.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1223-add-test-more-information-feature-info/index.html)
> PB-1223: add test more information feature info

- tests/cypress/tests-e2e/print.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1195-test-external-layer-printing/index.html)
> PB-1195: Add test for printing WMS and WMTS layers.

- src/modules/map/components/CompareSlider.vue
- tests/cypress/tests-e2e/timeCompareSlider.cy.js
- tests/cypress/tests-e2e/timeSlider.cy.js
- tests/cypress/tests-e2e/utils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1197-timeslider-and-compare-slider-test/index.html)
> PB-1196, PB-1197: timeslider and compare slider test

- src/modules/drawing/components/DrawingInteractions.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1213-fix-unhandled-null/index.html)
> PB-1213: Fix unhandled null.

- src/modules/i18n/index.js
- src/store/plugins/geolocation-management.plugin.js
- src/utils/components/FeedbackPopup.vue
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/geolocation.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1187-geolocation-test/index.html)
> PB-1187: Add more geolocation test

- src/modules/infobox/components/FeatureElevationProfilePlot.vue
Issue : FeatureElevationProfilePlot component was still in option API
Fix : we refactor the component to the composition API
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-composition-api-for-profile-component/index.html)
> PB-1151: refactor feature Elevation component

- tests/cypress/tests-e2e/search/search-results.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-400-test-search-result-is-hidden/index.html)
> PB-400: Add test for hiding the dropdown adter selecting a search result

- src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1349-add-new-layers-geodienste-ch/index.html)
> PB-1349: new layers geodienste.ch

- src/modules/map/components/CompareSlider.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1322-compare-slider-external-layer-cut/index.html)
> PB-1322: Compare slider external layer not correctly cut after reloading

- package-lock.json
- package.json
- packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- packages/mapviewer/src/utils/composables/useTippyTooltip.js
- packages/mapviewer/tests/cypress/support/commands.js
- packages/mapviewer/tests/cypress/tests-e2e/layers.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/print.cy.js
Mostly work for fixing some tests.
- Install Cypress manually
- Improve the tooltip composable, allowing for lazy referencing the DOM elements. This fixes a bug in the menu layer items where there were too many tooltips instantiated
- Added some more log output in the cypress commands
- Fixed the url transformation in the e2e tests that resulted in `feature=[object Object]` URLs
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1384-profile-npm-modules-lthee/index.html)
> PB-1384 Contributing to the modularization

- packages/mapviewer/src/modules/map/components/cesium/CesiumCamera.vue
- packages/mapviewer/src/modules/map/components/toolbox/GeolocButton.vue
- packages/mapviewer/src/store/plugins/geolocation-management.plugin.js
- packages/mapviewer/src/store/plugins/sync-camera-lonlatzoom.js
- packages/mapviewer/tests/cypress/support/commands.js
- packages/mapviewer/tests/cypress/tests-e2e/3d/geolocation.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/geolocation.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/legacyParamImport.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/utils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1200-geolocation-test-3d/index.html)
Can I someone check that the geolocation in 3D works fine inside Switzerland? @pakb @hansmannj or @ltkum 
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1200-geolocation-test-3d/index.html)
> PB-1200: Add Geolocation Test in 3D Map

- packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1456-duplicated-layer-when-dragging/index.html)
> PB-1456: Fix drag layer issue

- packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
[Test link](https://sys-map.int.bgdi.ch/preview/develop/index.html)
> New Release v1.53.2 - #patch

- packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- packages/mapviewer/src/modules/menu/components/header/ConfederationFullLogo.vue
[Test link](https://sys-map.int.bgdi.ch/preview/develop/index.html)
> New Release v1.53.3 - #patch

- packages/mapviewer/src/modules/infobox/components/FeatureDetail.vue
- packages/mapviewer/tests/cypress/fixtures/import-tool/iframe-test.kml
- packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1539-sms-protocol-external-kml-blocked/index.html)
> PB-1539: Allow SMS URI in the external KML

- packages/mapviewer/src/modules/map/components/openlayers/utils/useViewBasedOnProjection.composable.js
- packages/mapviewer/tests/cypress/tests-e2e/mouseposition.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1368-round-zoom-double-tap-mobile/index.html)
> PB-1368: round zoom on double tap

- packages/mapviewer/src/api/features/LayerFeature.class.js
- packages/mapviewer/src/api/features/features.api.js
- packages/mapviewer/src/modules/map/components/cesium/CesiumHighlightedFeatures.vue
- packages/mapviewer/src/modules/map/components/cesium/CesiumInteractions.vue
- packages/mapviewer/src/modules/map/components/cesium/CesiumMouseTracker.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- packages/mapviewer/src/store/modules/search.store.js
- packages/mapviewer/src/store/plugins/reproject-selected-features-on-projection-change.plugin.js
- packages/mapviewer/src/utils/layerUtils.js
- packages/mapviewer/tests/cypress/tests-e2e/3d/layers.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1576-switching-to-3d-with-selected-feature-breaks-3d-viewer/index.html)
> PB-1576: switching to 3D with selected features breaks the 3D viewer

- packages/mapviewer/src/modules/drawing/components/DrawingExporter.vue
- packages/mapviewer/src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- packages/mapviewer/src/modules/infobox/components/styling/DrawingStyleSizeSelector.vue
- packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- packages/mapviewer/src/modules/menu/components/help/ReportProblemButton.vue
- packages/mapviewer/src/modules/menu/components/print/MenuPrintSection.vue
- packages/mapviewer/src/utils/components/DropdownButton.vue
- packages/mapviewer/src/utils/components/DropdownButtonItem.vue
- packages/mapviewer/tests/cypress/tests-e2e/print.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1048-harmonize-dropdown-button/index.html)
> PB-1048-harmonize dropdown buttons

- packages/mapviewer/src/utils/components/ModalPrintWithBackdrop.vue
One typo to ruin them all :rofl: *and it was hard to find it 
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1563-blank-print-elevation-profile-layer-description/index.html)
> PB-1563: Fix tailwindcss typo to fix the print bug.

- packages/mapviewer/src/modules/i18n/locales/de.json
- packages/mapviewer/src/modules/i18n/locales/en.json
- packages/mapviewer/src/modules/i18n/locales/fr.json
- packages/mapviewer/src/modules/i18n/locales/it.json
- packages/mapviewer/src/modules/i18n/locales/rm.json
- packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/parser/KMLParser.class.js
- packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/useImportFile.composable.js
- packages/mapviewer/src/utils/__tests__/kmlUtils.spec.js
- packages/mapviewer/src/utils/__tests__/kml_feature_error.kml
- packages/mapviewer/src/utils/kmlUtils.js
- packages/mapviewer/tests/cypress/fixtures/import-tool/kml_feature_error.kml
- packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1471-kml-validation/index.html)
> PB-1471: kml validation

- packages/mapviewer/src/modules/i18n/locales/de.json
- packages/mapviewer/src/modules/i18n/locales/en.json
- packages/mapviewer/src/modules/i18n/locales/fr.json
- packages/mapviewer/src/modules/i18n/locales/it.json
- packages/mapviewer/src/modules/i18n/locales/rm.json
- packages/mapviewer/src/utils/components/FeedbackPopup.vue
- packages/mapviewer/src/views/MapView.vue
This reverts commit 5dd68961d8059e2f60b0fe3c0c2a352c4d953c3a.
[Test link](https://sys-map.int.bgdi.ch/preview/remove-outage-banner/index.html)
> Revert "Showing a banner informing our users about the current outage" - #patch

- packages/mapviewer/src/modules/infobox/components/InfoboxContent.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
- packages/mapviewer/src/modules/map/components/openlayers/utils/markerStyle.js
- packages/mapviewer/src/store/modules/profile.store.js
- packages/mapviewer/tests/cypress/fixtures/import-tool/external-gpx-file-multi-separated-segment.gpx
- packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
[Test link with segments](https://sys-map.dev.bgdi.ch/preview/feat-pb-1179-highlight-current-segment-multi-line-profile/index.html#/map?lang=fr&center=2630392.31,1169264.07&z=10.617&topic=ech&layers=ch.astra.veloland@features=8.02:9.04&bgLayer=ch.swisstopo.pixelkarte-farbe&featureInfo=default)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1179-highlight-current-segment-multi-line-profile/index.html)
> PB-1179: highlight current segment multi line profile

- packages/mapviewer/src/modules/infobox/InfoboxModule.vue
- packages/mapviewer/src/modules/infobox/components/InfoboxContent.vue
- packages/mapviewer/src/store/modules/profile.store.js
and not on the whole profile feature, when there's more than one segment
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1179-zoom-extent-profile-segment/index.html)
> PB-1179: Zoom-to-extent zooms on current profile segment

- packages/geoadmin-tooltip/src/GeoadminTooltip.vue
- packages/mapviewer/src/modules/map/components/toolbox/GeolocButton.vue
- packages/mapviewer/src/modules/map/components/toolbox/Toggle3dButton.vue
- packages/mapviewer/src/modules/map/components/toolbox/ZoomButtons.vue
- packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
- packages/mapviewer/src/modules/menu/components/share/MenuShareInputCopyButton.vue
- packages/mapviewer/src/utils/components/ExtLayerInfoButton.vue
- packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/layers.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/mouseposition.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/shareShortLink.cy.js
The geolocation button has a "linking background" with the compass button (which isn't visible when pointing north).
Since modularization, this background is swelling under the button
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1674-tooltip-height-issue/index.html)
> PB-1674: Fix tooltip creating too much height with map buttons

- packages/mapviewer/src/modules/map/components/CompareSlider.vue
- Issue : When starting the application with the compare slider active, sometimes the rendering event would not be instantiated, meaning the compare slider would not work.
- Reason: When instantiating the compare slider, we used to add a once trigger on precompose if there were no layers ready on the map, but there were layers in the store. precompose is only fired with vector layers (webGL context). This means that, in this case where we had WMS layers which used the canvas context, the event was never fired.
- Fix: We use a rendercomplete event instead and ask for a new render.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1685-compare-same-external-layer/index.html)
> PB-1685: duplicate COG layers from WMS can't be compared

- packages/mapviewer/src/modules/infobox/components/FeatureDetail.vue
- packages/mapviewer/src/modules/map/components/cesium/CesiumInteractions.vue
- packages/mapviewer/src/modules/map/components/cesium/CesiumKMLLayer.vue
- packages/mapviewer/src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
- packages/mapviewer/src/store/plugins/reproject-layers-on-projection-change.plugin.js
- packages/mapviewer/src/utils/kmlUtils.js
- packages/mapviewer/src/utils/layerUtils.js
- packages/mapviewer/tests/cypress/tests-e2e/3d/featureSelection.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1300-kml-feature-selection-3d/index.html)
> PB-1300: KML feature selection 3D

- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1257-add-cog-tile-debug/index.html)
> PB-1257: add tile debug for COGs

- packages/mapviewer/src/modules/map/components/CompareSlider.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1679-local-cog-compare/index.html)
> PB-1679: fix local cog file compare

- packages/mapviewer/src/api/layers/WMSCapabilitiesParser.class.js
- packages/mapviewer/src/api/layers/__tests__/WMSCapabitliesParser.class.spec.js
- packages/mapviewer/src/api/layers/__tests__/wms-geoadmin-sample-sld-enabled.xml
- packages/mapviewer/tests/cypress/fixtures/import-tool/wms-geo-admin-get-capabilities_sld_enabled.xml
- pnpm-lock.yaml
- pnpm-workspace.yaml
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1220-allow-sld-legends-parsing/index.html)
> PB-1220: Allow SLD enabled WMS to display aggregate legends

- packages/viewer/tests/cypress/support/drawing.ts
- handle plain KML
credit: @sommerfe 
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1383-fix-drawing-test/index.html)
> PB-1383: Fix Drawing Test
