geoadmin/web-mapviewer

- src/config.js
- src/modules/menu/MenuModule.vue
- vue.config.js
some kind of end-of-line issue in `vue.config.js`, maybe I pushed it last time with Window carriage return... This time I fixed it with `ESLint` so it should not change like that anymore
[Test link](https://web-mapviewer.dev.bgdi.ch/feature_BGDIINF_SB-1501/index.html)
> Show app version in footer on DEV envs

- buildspec.yml
Removing everything `apt-get` as it's not required for Cypress to run properly (and it makes the CI fail)
[Test link](https://web-mapviewer.dev.bgdi.ch/try_latest_codebuild_image/index.html)
> Prepare buildspec.yml for latest AWS Codebuild image

- scripts/deploy.js
as the GitHub action that creates the test link lowers the branch name while generating the URL.
It doesn't work well when we uses Jira numbers that contains uppercase characters.
I've also linted the file in the first commit, so look at the second for the real change.
[Test link](https://web-mapviewer.dev.bgdi.ch/fix_deploy_script/index.html)
> Lower branch name in deploy script

- vue.config.js
as they are deployed as lower case path by the deploy script
[Test link](https://web-mapviewer.dev.bgdi.ch/fix_uppercase_path_on_s3/index.html)
> Set paths on S3 to lowercase

- .browserslistrc
- public/index.html
It looks like current version of browserlist includes the not supported IE11.
Here is a proposition of update:
```bash
node_modules/.bin/browserslist 
and_chr 89
and_ff 86
and_qq 10.4
and_uc 12.12
android 89
baidu 7.12
chrome 89
chrome 88
chrome 87
edge 89
edge 88
firefox 86
firefox 85
firefox 78
ios_saf 14.0-14.5
ios_saf 13.4-13.7
kaios 2.5
op_mini all
op_mob 62
opera 73
opera 72
safari 14
safari 13.1
samsung 13.0
samsung 12.0
```
[Test link](https://web-mapviewer.dev.bgdi.ch/browserlist_update/index.html)
> Browserlist proposition

- src/modules/menu/components/MenuSettings.vue
- src/modules/menu/components/MenuTray.vue
- tests/e2e/specs/header.spec.js
Issue : We wanted the language selection to be part of a settings section
Fix : We created a settings sections and placed the language selection within it.
We added some tests to make sure the settings section is closed on opening the menu, that it opens on clicking on it and it closes on clicking again.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature_lang_selection_in_settings_menu/index.html)
> Feature BGDIINF_SB-1704: transferring lang selection to settings section

- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- tests/e2e/specs/layers.spec.js
Issue : The layer ordering arrows buttons were not disabled when the layer was already at the top or the bottom of the list and the arrow became useless.
Fix : 
Adding a new property to check if we should disable the button
e2e tests.
[Test link](https://web-mapviewer.dev.bgdi.ch/issue_1788/index.html)
> BGDIING_SB-1788: BUGFIX - ordering arrows not disabled when useless

- buildspec.yml
The bucket for dev is now hosted in another account, hence the CI needs to do a little bit of logic regarding staging before publishing the code on a bucket
> Change account the CI uses for DEV

- .env.development
- .env.production
- src/api/icon.api.js
- src/config.js
- src/modules/drawing/DrawingModule.vue
- tests/e2e/fixtures/service-icons/set-default.fixture.json
- tests/e2e/fixtures/service-icons/set-second.fixture.json
- tests/e2e/fixtures/service-icons/sets.fixture.json
- tests/e2e/specs/drawing/marker-text.spec.js
- tests/e2e/support/drawing.js
Service Icons is being transitioned into the sys-map nomenclature. This is to be merged when the changes have been made in the service itself and has been deployed again. 
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-bgdiinf_sb-2059/index.html)
> BGDIINF_SB-2059: Using new sys- nomenclature for service icons

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/SharePopup.vue
- src/modules/drawing/components/styling/DrawingStyleColorSelector.vue
- src/modules/overlay/components/ModalWithOverlay.vue
So, I was on the disclaimer branch while working on this, thus I think it's better to merge this in the disclaimer branch, then merge the full drawing module.
Issue: drawing module CSS did not display cursors correctly
Fix: removed the css scope from the drawing module css definition
Also added a functionality where users clicking the link in the drawing sharing popup will copy the link to the clipboard and select the whole link at the same time.
[Test link](https://web-mapviewer.dev.bgdi.ch/bgdiinf_sb_2023/index.html)
> BGDIINF_SB-2023: bugfix ; applying drawing module css correctly

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/lib/MeasureManager.js
The drawing measurement click and double click action were not
triggered, which means that we could not end the measurement drawing
tool nor add subsequent measurement point.
This was due to the fact that the measurement tooltip was over the
drawing measurement and that this overlay did not pass the click event
futher. Moving the tooltip away from the measurement line would also
have fixed the issue but the display wouldn't have been niche (also not
sure if this would have worked on a touch display).
Also center the measurement tooltip on the line, it was one pixel off.
[Test link](https://web-mapviewer.dev.bgdi.ch/bug-bgdiinf_sb-2089-drawing-ruler/index.html)
> BGDIINF_SB-2089: Fixed drawing measurement

- src/api/files.api.js
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/utils/legacyLayerParamUtils.js
- tests/e2e/specs/legacyParamImport.spec.js
The legacy URL for KML admin was as follow:
?adminid=ADMIN_ID
And now this needs to be transformed to
?layers=KML|https://public.geo.admin.ch/api/kml/files/KML_ID@adminid=ADMIN_ID
Also reorganized the code for a better readability.
And finally fixed a bug in the store sync.
> BGDIINF_SB-1993: Added support for legacy KML adminid query parameter

- package-lock.json
- src/App.vue
- src/modules/drawing/components/ProfilePopup.vue
- src/modules/drawing/components/styling/DrawingStyleColorSelector.vue
- src/modules/drawing/components/styling/DrawingStyleIconSelector.vue
- src/modules/map/MapModule.vue
- src/modules/map/components/Footer.vue
- src/modules/map/components/openlayers/VisibleLayersCopyrights.vue
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/modules/menu/components/header/HeaderLoadingBar.vue
- src/modules/menu/components/header/SwissFlag.vue
- src/modules/menu/components/topics/MenuTopicTreeItem.vue
- src/modules/search/components/SearchBar.vue
- src/modules/search/components/SearchResultCategory.vue
- src/modules/search/components/SearchResultListEntry.vue
- src/modules/toolbox/ToolboxModule.vue
- src/modules/toolbox/components/BackgroundSelectorButton.vue
- src/modules/toolbox/components/GeolocButton.vue
- src/modules/toolbox/components/ZoomButtons.vue
- src/modules/tooltip/components/SwipableBottomSheet.vue
- src/scss/bootstrap-theme.scss
- src/scss/media-query.mixin.scss
- src/scss/webmapviewer-bootstrap-theme.scss
- src/utils/ButtonWithIcon.vue
- src/views/LoadingView.vue
- vue.config.js
Only import the lib once, import only variable in other places when they were needed
Replace @extends by using the wanted classes directly in the template
Changing the webpack config Vue's using so that we may later more easily add monitoring tools (such as 'speed-measure-webpack-plugin')
[Test link](https://web-mapviewer.dev.bgdi.ch/fix_bootstrap_import/index.html)
> Fix bootstrap import

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/store/index.js
- src/modules/store/plugins/drawing-layer-management.plugin.js
- tests/e2e/specs/drawing/drawing-layer.spec.js
When removing a drawing layer, the drawing is cleared allow the creation
of a new drawing. Note the actual drawing file on the backend is not
touched ! This only clear the drawing from the frontend module and the
drawing can still be retrieved via its ID from the backend.
For this I needed to add a new event in the drawing manager to
differenciate the clear event from other change event. The clear event
would then only trigger a kml update when the drawing mode is active
(drawing menu open). This avoid creating empty kml by removing a drawing
layer.
[Test link](https://web-mapviewer.dev.bgdi.ch/bug-bgdiinf_sb-2021-remove-kml-layer/index.html)
> BGDIINF_SB-2021: Clear the drawing on removing the layer

- package-lock.json
- package.json
- src/modules/store/modules/position.store.js
We bundled the Turf.js library to make just one calculation.
While there's nothing wrong with the library it seemed overkill to include it for a single use. Especially as the calculation is rather trivial.
This hard-codes the necessary part directly where it is needed to generate as little overhead as possible.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2137-remove-turf/index.html)
> BGDIINF_SB-2137: Removed Turf.js

- src/modules/map/components/openlayers/OpenLayersMap.vue
- tests/e2e/specs/footer.spec.js
If the initial zoom was below the threshold set in the template,
the scale-line would not show after zooming in past the threshold.
It seems as if a portal-target with multiple portals combined with
the lazy nature of v-if causes the target to get confused and mix
the markup/DOM of the different portals.
Using v-show instead of v-if fixes the issue.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2120-scale-line-not-showing/index.html)
> BGDIINF_SB-2120: Fixed scale-line not showing

- src/router/stringifyQuery.js
The new vue-router v4 stringifyQuery behavior has changed and this
method should not add the ? to the query.
[Test link](https://web-mapviewer.dev.bgdi.ch/feat-bgdiinf_sb-2143-double-question-mark/index.html)
> BGDIINF_SB-2143: Removed double ?? in query param

- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- src/modules/overlay/components/LayerLegendPopup.vue
- src/modules/search/components/SearchResultCategory.vue
- src/modules/search/components/SearchResultList.vue
- src/modules/search/components/SearchResultListEntry.vue
- tests/e2e/specs/search.spec.js
We allow the user to add some layers through the search results. Analog to the layer selection/settings in the menu we want to provide a button that opens a modal with information about the layer. As is the case in the current production version.
This change adds that button and refactors/moves the modal used in the menu in order to avoid having a dependency between the search and the menu components.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2015-search-info-button/index.html)
> BGDIINF_SB-2015: Added info-button to search results

- tests/e2e/specs/layers.spec.js
During the update to Vue3 a bug was fixed that prevented unchecking a layer via the topic menu.
This adds an e2e test to check that the bug has been fixed and the layers can be toggled via the topic menu.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2134-e2e-toggle-layer-topicmenu/index.html)
> BGDIINF_SB-2134: Added e2e test for layer toggling from topic menu

- src/api/icon.api.js
- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/styling/DrawingStyleIconSelector.vue
- src/modules/drawing/lib/DrawingManager.js
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/store/modules/drawing.store.js
- src/utils/featureAnchor.js
- tests/e2e/support/drawing.js
Until now we used hard-coded anchors to position the icons on the map.
The backend service has been updated to provide an anchor for each icon and this change updates the code to make use of this information.
This PR also includes the fix for the missing anchors.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2154-icon-anchor-from-backend/index.html)
> BGDIINF_SB-2154: Use icon anchors from backend

- buildspec.yml
- vue.config.js
Removed old hack for branch name resolution. This hack did not work with
PR from fork as well as by some PR from dependabot.
Use the newest Codebuild variable instead and make sure that the branch
name used in docker tag don't contains `/` by replacing them to `_`
(`/` is not allowed in docker tag name). For this replacement we need
bash so make sure that Codebuild use bash instead of the default hash.
Also based on the AWS Codebuild documentation
(https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html)
don't use `CODEBUILD_` environment variable prefix which is reserved for
internal use by CodeBuild.
[Test link](https://web-mapviewer.dev.bgdi.ch/bug-bgdiinf_sb-2163-ci-branch/index.html)
> BGDIINF_SB-2163: Fixed CI branch name resolution

- src/modules/i18n/components/LangSwitchToolbar.vue
- src/modules/store/modules/layers.store.js
- tests/e2e/specs/layers.spec.js
- tests/e2e/support/commands.js
During the update to Vue3 a bug was fixed that reverted the configuration to its initial state and prevented the displayed language in the active layers and topic menu to change when the user switched the language in the settings.
The test changes the layer configuration after the initial load and checks if the configuration persists after changing the language.
This commit also introduces a new fake request so we can wait until the layers have been configured (@layers-configured).
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2133-e2e-change-language/index.html)
> BGDIINF_SB-2133: Added e2e test for language switch

- src/api/features.api.js
- src/api/files.api.js
- src/api/height.api.js
- src/api/icon.api.js
- src/api/layers/layers.api.js
- src/api/profile.api.js
- src/api/qrcode.api.js
- src/api/search.api.js
- src/api/what3words.api.js
- src/modules/i18n/components/LangSwitchToolbar.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/store/modules/geolocation.store.js
- src/modules/store/modules/layers.store.js
- src/modules/store/modules/topics.store.js
- src/modules/store/plugins/click-on-map-management.plugin.js
- src/modules/store/plugins/geolocation-management.plugin.js
- src/modules/store/plugins/load-layersconfig-on-lang-change.js
- src/router/appLoadingManagement.routerPlugin.js
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/utils/coordinateUtils.js
- src/utils/logging.js
Probably due to a change of the log function we have calls to `log.error` which doesn't exist.
This modifies the calls to work with the current implementation of the log function.
It also modifies the function's default handling to include/preserve the fist parameter passed to the function.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2161-log-function/index.html)
> BGDIINF_SB-2161: Fixed calls to non-existant error function

- package-lock.json
- package.json
- src/main.js
- src/modules/map/components/MapFooter.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/OpenLayersMousePosition.vue
- src/utils/PopoverButton.vue
As Vue3 comes with its own teleport feature we want to get rid of the portal-vue plugin. However, because the destination has to be mounted before the teleport and the order is on a first-come basis, this isn't a drop-in replacement.
This change adds a delay (through nextTick) before the teleports are attempted and to guarantee the correct order I added dedicated destinations for each teleport.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2119-replace-portals-with-teleports/index.html)
> BGDIINF_SB-2119: Replaced portal-vue with Vue teleport

- src/modules/map/components/MapFooter.vue
- src/modules/map/components/openlayers/VisibleLayersCopyrights.vue
- src/modules/menu/MenuModule.vue
We wanted transparent header, footer, and copyright notice.
The header and copyright already had the transparency so this change
only adds it to the footer. While I was at it I changed the existing
transparency to use SCSS variables and rgba() function.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2014-footer-transparency/index.html)
> BGDIINF_SB-2014: Added transparency to footer

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/ProfilePopup.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/VisibleLayersCopyrights.vue
The problem with the force-click in the test had already been addressed via a z-index. But that hides the copyright notice if the profile is present (minimized or not).
This change positions the copyright notice above the profile so that it is always in the bottom right-hand corner of the visible part of the map. That not only makes Cypress happy but also copyright holders.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2170-copyright-position/index.html)
> BGDIINF_SB-2170: Changed layer copyright position

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/DrawingToolboxButton.vue
- src/setup-fontawesome.js
- src/utils/ButtonWithIcon.vue
We currently use a plus icon for the text-add button which doesn't
communicate the purpose of the button as the other buttons from the
drawing toolbox also add things.
This changes the icon from a "+" to a "T".
More information about the choice can be found in the Jira ticket.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2132-drawing-text-icon/index.html)
> BGDIINF_SB-2132: Changed text-add icon (drawing)

- src/modules/map/components/footer/MapFooterMousePosition.vue
- src/utils/coordinateUtils.js
- src/utils/militaryGridProjection.js
- tests/e2e/specs/mouseposition.spec.js
This adjusts the format of the mouse position as displayed in the
footer to match the format of mf-geoadmin3.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2013-mouse-position-formats/index.html)
> BGDIINF_SB-2013: Updated mouse position coordinate formats

- src/modules/map/components/LocationPopup.vue
Currently, the content of the position overlay is not selectable.
This seems to have been broken in OpenLayers 4.1 and since then we need to add an extra class to make the content selectable again.
I added the class and a comment and the content is now selectable.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2212-position-selectable-content/index.html)
> BGDIINF_SB-2212: Made position content selectable

- package-lock.json
- package.json
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/search/SearchBar.vue
- src/modules/menu/components/search/SearchResultCategory.vue
- src/modules/menu/components/search/SearchResultList.vue
- src/modules/menu/components/search/SearchResultListEntry.vue
- tests/e2e/specs/search/search-results.spec.js
- tests/e2e/support/commands.js
This adds listeners to the search input and the list items to
enable navigating / controlling the search input and results.
* <kbd>ArrowDown</kbd> on **input** leads to first result.
* <kbd>Tab</kbd> on **input** leads to first result.
* <kbd>Escape</kbd> on **input or results** closes results and gives input focus.
* <kbd>Tab</kbd> on **result** leads to next category / exists the results.
* <kbd>ArrowUp</kbd> on **result** leads to previous result in category.
* <kbd>ArrowDown</kbd> on **result** leads to next result in category.
* <kbd>Home</kbd> on **result** leads to first result in category.
* <kbd>End</kbd> on **result** leads to last result in category.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2016-search-results-keyboard-navigation/index.html)
> BGDIINF_SB-2016: Added keyboard navigation to search results

- src/api/what3words.api.js
- src/modules/map/components/LocationPopup.vue
We had a mix-up with the coordinate values which resulted in positions around Somalia. And one had to manually copy/paste the words from the pop-up to the website to see the result.
This fixes (turns around) the coordinate values and adds a link to the three words that leads to the website.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2227-w3w-position-and-link/index.html)
> BGDIINF_SB-2227: Fixed w3w coords and added link

- package-lock.json
- package.json
- src/modules/infobox/components/TooltipBox.vue
- src/utils/ModalWithBackdrop.vue
- src/utils/print.js
As this will be much more reliable with future browser changes. The current in house code wasn't working anymore on the latest Chrome version anyway.
[Test link](https://web-mapviewer.dev.bgdi.ch/replace_print_by_lib/index.html)
> Replacing in-house print code with lib

- src/modules/map/components/LocationPopup.vue
- tests/e2e/specs/mouseposition.spec.js
The link to share the current position points to the center of the
map. This is because the link uses the current URL as-is instead
of the ClickInfo position.
This replaces lat/lon when generating the URL so that the marker
is at the expected position when opening the link.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2226-share-link-clickinfo/index.html)
> BGDIINF_SB-2226: Fixed position of share link

- src/modules/map/components/LocationPopup.vue
During the review of BGDIINF_SB-2226 Brice noticed that the QR code was missing the crosshair and that the link wouldn't update when clicking on a different spot on the map.
With this update the QR code uses the same link as the "share link" which also fixed the reactivity problem.
And while I was at it I also removed a redundant WGS84 format and did some minor refactoring.
PS: The actual change is the use of `this.shareLinkUrl` on line 221.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2237-share-link-qr-code/index.html)
> BGDIINF_SB-2237: Updated QR code link

- src/modules/map/components/footer/MapFooter.vue
- src/modules/map/components/footer/MapFooterMousePosition.vue
- src/modules/map/components/footer/MapFooterProjection.vue
- tests/e2e/specs/mouseposition.spec.js
As we don't have a mouse (hover) on mobile devices
we can hide the mouse position in the footer.
This makes that change and includes some improvements
to the footer's CSS to make it more flexible to cope
with the disappearing mouse position and map scale.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2236-hide-mouse-position/index.html)
> BGDIINF_SB-2236: Hid mouse position on mobile

- src/modules/menu/components/header/HeaderSwissConfederationText.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/header/SwissFlag.vue
- src/modules/store/modules/app.store.js
- src/modules/store/modules/drawing.store.js
- src/modules/store/modules/layers.store.js
- src/utils/legacyLayerParamUtils.js
- tests/e2e/specs/layers.spec.js
- tests/e2e/support/commands.js
- tests/e2e/support/drawing.js
- vue.config.js
Until now we had some fake requests that we intercepted
in order to be able to wait for certain events.
This removes those requests and replaces the waiting with
the Cypress plugin waitUntil. This also removes the warning
about this being a test site. The warning obscured a button
and we should test for what we deploy in production.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2232-dont-tell-cypress/index.html)
> BGDIINF_SB-2232: Removed fake tell-cypress requests

- src/api/features.api.js
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/infobox/InfoboxModule.vue
- src/modules/infobox/components/HighlightedFeatureList.vue
- src/modules/infobox/components/TooltipBox.vue
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
- src/modules/map/store/map.store.js
- src/modules/store/index.js
- src/modules/store/modules/feature.store.js
- src/modules/store/modules/ui.store.js
- src/modules/store/plugins/click-on-map-management.plugin.js
- src/modules/store/plugins/screen-size-management.plugin.js
- src/utils/EventEmitter.class.js
- src/views/MapView.vue
Use this new popover in the LocationPopup component
Use this new popover to show highlighted features on the map (with absolute positioning on the coordinates of the feature)
Add in this popover for features a button (in header) that enables the user to place the tooltip at the bottom of the app (with a grid system that gets wider as the screen gets bigger)
Switch to this footer tooltip when on mobile (and back to floating tooltip if going back to desktop)
Removing the usage of the swipe tray (needs more work if we want to use it)
[Test link](https://web-mapviewer.dev.bgdi.ch/feat-jira-bgdiinf_sb-2159_highlighted_feature_overhaul/index.html)
> BGDIINF_SB-2159: add a new popover OL component

- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/footer/MapFooterBackgroundSelector.vue
- tests/e2e/specs/mouseposition.spec.js
While the underlying link did update properly the QR code generation wasn't triggered.
This fixes that by watching the current route for changes and adds an e2e test to make sure this doesn't happen anymore.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2237-update-on-url-change/index.html)
> BGDIINF_SB-2237: Fixed missing update on URL change

- package-lock.json
- package.json
- src/api/files.api.js
- tests/e2e/specs/drawing/line-polygon.spec.js
- tests/e2e/specs/drawing/marker-text.spec.js
- tests/e2e/support/drawing.js
- tests/e2e/support/multipart.js
To enable the migration of the service-kml it was requested that
we send the drawings gzipped (i.e. as KMZ).
This commit introduces pako (as pure JS library) to compress the
KML before sending it to the backend.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2105-send-as-kmz/index.html)
> BGDIINF_SB-2105: Send drawings as KMZ (gzipped)

- src/modules/menu/components/search/SearchBar.vue
- src/modules/menu/components/search/SearchResultCategory.vue
- src/modules/menu/components/search/SearchResultList.vue
- src/modules/menu/components/search/SearchResultListEntry.vue
This updates the search result styling to be more in line with the
implementation in mf-geoadmin3. This is not 100% identical but as
close as it gets with our current base styles.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-1389-search-results-styling/index.html)
> BGDIINF_SB-1389: Updated search result styling

- buildspec.yml
- scripts/deploy.js
- vue.config.js
This rename was done to match our nomenclature guidelines.
Note this should not be merge before https://github.com/geoadmin/infra-terraform-bgdi-dev/pull/28 and https://github.com/geoadmin/infra-terraform-bgdi/pull/21 have been applied. Then the service needs to be redeployed.
[Test link](https://web-mapviewer.dev.bgdi.ch/feat-bgdiinf_sb-2223-webviewer-s3-renaming/index.html)
> BGDIINF_SB-2223: renaming web-mapviewer bucket

- src/modules/menu/components/search/SearchBar.vue
We currently have different x-mark icons for the search and the selected layers.
This changes the icon for the search in order to give the application a more consistent look.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2273-clear-search-icon/index.html)
> BGDIINF_SB-2273: Changed clear icon for search

- src/modules/menu/components/header/HeaderMenuButton.vue
This changes the color of the menu button on mobile when the menu is open to further indicate the toggled state.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2272-invert-menu-button/index.html)
> BGDIINF_SB-2272: Inverted menu button on mobile

- src/modules/menu/components/BlackBackdrop.vue
- src/modules/menu/components/LayerLegendPopup.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- src/modules/menu/components/topics/MenuTopicTreeItem.vue
- tests/e2e/specs/topics.spec.js
As with the info-button for the selected layers (settings) and the
search results we now also have an info-button for the available layers.
Plus, the usual minor refactoring.
This time function assignments, async/await, and some renaming.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2268-layer-info-button/index.html)
> BGDIINF_SB-2268: Added info-button to layers

- src/App.vue
- src/modules/menu/components/header/SwissFlag.vue
- src/scss/variables-admin.scss
- src/scss/webmapviewer-bootstrap-theme.scss
- src/utils/ModalWithBackdrop.vue
Outlines, while useful, can be rather ugly. That's why we decided
we want to remove them where possible.
This change introduces the dynamic outlines from the Swiss Style
Guide (based on outline.js) that only show when using the keyboard.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2266-dynamic-outlines/index.html)
> BGDIINF_SB-2266: Added dynamic focus outlines

- src/modules/menu/components/LayerLegendPopup.vue
In order to get back to the mf-geoadmin3 look I removed the SCSS
scoping and added some minor adjustments to the existing styles.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2270-legend-header-styles/index.html)
> BGDIINF_SB-2270: Updated styles for layer legends

- src/modules/map/store/map.store.js
- src/modules/menu/components/search/SearchResultCategory.vue
- src/modules/menu/components/search/SearchResultList.vue
- src/modules/menu/components/search/SearchResultListEntry.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- src/modules/menu/components/topics/MenuTopicTreeItem.vue
- src/modules/menu/store/search.store.js
- src/modules/store/modules/layers.store.js
- tests/e2e/specs/search/search-results.spec.js
- tests/e2e/specs/topics.spec.js
In line with mf-geoadmin3 this adds a preview on hover to the search
results. The layers use the same functionality as the topic list and
the locations use the pinnedLocation that was already present.
This also includes some refactoring of the layer preview code and
adds the e2e tests for both the topic list and search results.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-1388-search-layer-preview/index.html)
> BGDIINF_SB-1388: Added preview for search results

- src/App.vue
- src/config.js
- src/modules/infobox/InfoboxModule.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/menu/MenuModule.vue
- src/modules/store/modules/ui.store.js
- src/modules/store/plugins/screen-size-management.plugin.js
- src/utils/debounce.js
- tests/e2e/specs/drawing/delete.spec.js
- tests/e2e/specs/drawing/drawing-layer.spec.js
- tests/e2e/specs/drawing/export.spec.js
- tests/e2e/specs/drawing/kml.spec.js
- tests/e2e/specs/drawing/line-polygon.spec.js
- tests/e2e/specs/drawing/marker-text.spec.js
- tests/e2e/specs/header.spec.js
- tests/e2e/specs/layers.spec.js
- tests/e2e/specs/topics.spec.js
- tests/e2e/support/drawing.js
To show more of the map we close the menu on smaller viewports.
It opens the menu (desktop mode) when window gets bigger than 768px
and closes the menu when the window gets smaller than 768px.
[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2263-uimodes-tablet/index.html)
> BGDIINF_SB-2263: Added trigger to open/close menu

- src/modules/drawing/components/DrawingSelectInteraction.vue
Listening to the add events from the selected features triggered
the listener too often.
By listening to the select event of the interaction we get each
event once.
[Test link](https://web-mapviewer.dev.bgdi.ch/develop-refactor-drawing-cursor/index.html)
> Changed the event to prevent too many triggers

- src/config.js
- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingModifyInteraction.vue
- src/modules/drawing/components/DrawingSelectInteraction.vue
- src/modules/drawing/components/DrawingTooltip.vue
- src/modules/drawing/lib/drawingUtils.js
This fixes the drawing tooltip (especially for lines/polygons) and
updates the tolerances of the different interactions so that they
match visually. At least as good as it gets.
[Test link](https://web-mapviewer.dev.bgdi.ch/develop-refactor-drawing-cursor/index.html)
> Fixed drawing tooltip and tolerances

- src/modules/infobox/components/SelectedFeatureList.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
- src/scss/variables.scss
- tests/e2e/specs/drawing/line-polygon.spec.js
To fix this test I reduced the overlay width and more importantly
added an auto-pan option to the overlay to make sure it is positioned
properly.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2360-e2e-line-polygon/index.html)
> BGDIINF_SB-2360: Updated width and added auto-pan

- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/store/modules/map.store.js
- src/store/plugins/click-on-map-management.plugin.js
- src/utils/coordinateUtils.js
- tests/e2e/specs/mouseposition.spec.js
Currently, when someone tries to open the location pop-up on iOS
Safari the pop-up directly closes again. This is because the browser
sends a click event in addition to the context-menu event.
As there is nothing we can do against this event, I added a check
to the "singleclick" event to see if the last event was a context-
menu and if it was on the same position.
[Test link](https://sys-map.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2323-ios-safari-longpress/index.html)
> BGDIINF_SB-2323: Added condition to ignore faultily event

- src/modules/map/components/footer/MapFooterAppCopyright.vue
Painted the links as they are on map.geo.admin.ch in the footer (no underlining, black, but underlining when hover).
Added a link to the CMS (geo.admin.ch) as on mf-geoadmin3
[Test link](https://sys-map.dev.bgdi.ch/feat-2264-footer-link-adapt-color/index.html)
> BGDIINF_SB-2264: footer link adapted color and added link to CMS

- src/store/plugins/drawing-layer-management.plugin.js
KML layers can be added in two places. This lead to the problem
that a KML layer added by URL was added to the layer list both
times.
This adds a check to limit the insertions to one.
[Test link](https://web-mapviewer.dev.bgdi.ch/bugfix-jira-bgdiinf_sb-2256-kml-layer-twice/index.html)
> BGDIINF_SB-2256: Fixed KML layer being added twice

- vite.config.js
So that Vite build will output code that can be placed anywhere in a bucket (even in a branch folder) and still function properly. Otherwise a base of `/` is used and then only the root of the bucket is a valid place to deploy the code.
[Test link](https://sys-map.dev.bgdi.ch/feat-use-relative-path-with-vite/index.html)
> Use a relative base path while building

- src/modules/drawing/components/ProfilePopupPlot.vue
- src/modules/drawing/lib/ProfileChart.js
The source link of the plot was split into two links: swissalti3d and dhm25
[Test link](https://sys-map.dev.bgdi.ch/feat-2396-plot-title-should-have-two-links/index.html)
> Feat 2396 plot title should have two links

- src/modules/infobox/components/FeatureProfile.vue
profileInfo in ProfilePopupPlot.vue in now not anymore a null object,
but an object with "0" properties, so that its corresponding dom
elements are already drawn when the component is created
[Test link](https://sys-map.dev.bgdi.ch/feat-2403-maxheight-of-tooltipbox-wrongly-calculated/index.html)
> BGDIINF_SB-2403: Fixed wrong calculation of maxheight in TooltipBox for the ProfilePopupPlot

- src/modules/drawing/lib/ProfileChart.js
- src/modules/infobox/components/FeatureProfile.vue
replaces https://github.com/geoadmin/web-mapviewer/pull/218 (rebased on `develop`)
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2405-x-y-axis-profile/index.html)
> BGDIINF_SB-2405: Added the profilechart axis labels and added translation in the tooltip

- README.md
- src/api/icon.api.js
- src/api/qrcode.api.js
Unfortunately the `Origin` header cannot be set by the application (Some browser like Chrome doesn't allow it) and this header is omitted on same origin use case. Therefore we need to change the backend, see https://github.com/geoadmin/service-icons/pull/56.
Did anyway some clean up here.
[Test link](https://sys-map.dev.bgdi.ch/bug-bgdiinf_sb-2420-icons-cors/index.html)
> BGDIINF_SB-2420: icons api origin header

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingMeasureInteraction.vue
- src/modules/drawing/components/drawingInteraction.mixin.js
- src/modules/drawing/lib/MeasureManager.js
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/store/modules/drawing.store.js
- src/utils/MeasureManager.js
- tests/e2e-cypress/fixtures/service-kml/lonelyMarker.kml
- tests/e2e-cypress/integration/drawing/kml.cy.js
- tests/e2e-cypress/integration/drawing/measureOverlays.cy.js
- tests/e2e-cypress/support/drawing.js
The bug was due to a call to the measure manager in the drawing module, in which it was undefined. Tof fix it, the measure manager was moved to the Drawing Layer, so that it can also be called when adding a saved KML Layer. It was also added in the map KML Layer.
[Test link](https://sys-map.dev.bgdi.ch/bugfix-2410-drawing-should-be-editable-when-reopened/index.html)
> Bugfix 2410 drawing should be editable when reopened

- src/modules/menu/components/menu/MenuSection.vue
- src/modules/menu/components/share/MenuShareSection.vue
- src/modules/menu/components/share/MenuShareShortLinkInput.vue
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/share.store.js
- tests/e2e-cypress/integration/shareShortLink.cy.js
Issue : the short link generation call was made every time there was a change in the url, causing a lot of unnecessary calls to the underlying service, beginning the first time a short link was generated and never stopping afterwards.
Fix : Whenever there is a change, if there is an existing short link, this will reset its state to null and close the share menu should it be open. Meaning the only calls made to the shortLink service should be for links people actually want to share.
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2431-close-share-menu-on-map-movement/index.html)
> Feature: BGDIINF_SB-2431: close share menu on map movement

- src/modules/menu/components/search/SearchBar.vue
Now focuses on search bar at app startup
[Test link](https://sys-map.dev.bgdi.ch/feat-2435-focus-on-search-bar-at-startup/index.html)
> Focus on search bar at app startup

- adr/2022_05_09_mobile_click_behavior.md
This is an ADR based on the JIRA ticket.
In order to enable users on mobile to also have access to the location popup, we have to think of a way to have 3 features on 2 gestures (touch and long touch).
The solution is to always run an "identify" request on short touch, and if nothing is found toggle the fullscreen mode. This frees the long click so that we can use it to show the location popup on mobile too.
[Test link](https://sys-map.dev.bgdi.ch/feature-jira-bgdiinf_sb-2235-mobile-click-behavior/index.html)
> BGDIINF_SB-2235: Added first draft for new ADR

- .env
- .env.integration
As we have finished our migration of most (if not all) our backends to Frankfurt, and thus to the new sys-... URL naming convention, old URLs starts to be decommissioned. We then have to change the last one that was still pointing to the old backend's DNS entry.
[Test link](https://sys-map.dev.bgdi.ch/backends_url_after_migration/index.html)
> Changes API base URL

- src/modules/drawing/lib/ProfileChart.js
- src/modules/drawing/lib/__tests__/profileChart.spec.js
- src/modules/infobox/components/FeatureProfile.vue
- src/views/MapView.vue
An overlay (circle) that shows the corresponding position on the map when hovering over the profile graph was added.
In addition, an infinite looop bug was fixed that sometimes happend when moving the mouse over the profile graph. I also used this opportunity to make the calculations of the height more precise.
[Test link](https://sys-map.dev.bgdi.ch/feat-2406-preview-position-on-map-when-moving-mouse-on-profile-graph/index.html)
> Feat 2406 preview position on map when moving mouse on profile graph

- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
Somehow during Vue3 migration, this part of the template was removed, making the aggregate layers invisible (as they weren't added to the template anymore)
A good test layer is `ch.bfs.gebaeude_wohnungs_register`, under zoom level 13.5 it is a WMTS, but closer to the ground it is a WMS
[Test link](https://sys-map.dev.bgdi.ch/fix_aggregate_layers/index.html)
> Fix aggregate layers not showing up anymore

- index.html
- src/App.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/toolboxRight/CompassButton.vue
- src/views/LoadingView.vue
- src/views/MapView.vue
This is the second PR for the feat 2434 ticket.
- The map can now also be rotated by clicking on Ctrl (but the default alt+shift still works)
- The compass is now updated in real time when rotating the map. To be able to do this, the menu had to be put inside the openlayers map, so that it can register openlayers events, as using the store for real time updates of the map rotation would be way too slow.
[Test link](https://sys-map.dev.bgdi.ch/feat-2434-show-compass-on-map-rotate/index.html)
> Feat 2434 show compass on map rotate second PR

- src/modules/drawing/lib/drawingUtils.js
- tests/e2e-cypress/integration/drawing/profile.cy.js
Fixed an issue where the profile was not showing up after drawing a closed polygon. Also added some cypress tests to check for this bug in the future.
[Test link](https://sys-map.dev.bgdi.ch/bugfix-2539-profile-issue-with-closed-polygon/index.html)
> Bugfix 2539 profile issue with closed polygon

- src/modules/map/components/footer/MapFooter.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/BlackBackdrop.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/menu/MenuSection.vue
- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/search/SearchBar.vue
- src/modules/menu/components/share/MenuShareSection.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- src/scss/variables.scss
- src/utils/LoadingBar.vue
- src/utils/LoadingScreen.vue
- src/utils/ModalWithBackdrop.vue
- src/views/MapView.vue
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/integration/menuTray.cy.js
- tests/e2e-cypress/support/commands.js
- Menu size is now limited by the size of the viewport and the different opened subsections receive automatically one part of the total height. This is done with a combination of css flexbox and css grid.
- Opening the settings or share sections (i.e. nonscrollable menu sections) automatically closes all other sections and if a non-scrollable menu section is open, no other menu sections can be open at the same time. Useful in particular for small screens where the menu may be cut otherwise.
- This PR also fixed some issues with the z-indexes.
- It did not fix an issue when shrinking the window from desktop to tablet size, which was instead moved to ticket [BGDIINF_SB-2521](https://jira.swisstopo.ch/browse/BGDIINF_SB-2521).
[Test link](https://sys-map.dev.bgdi.ch/feat-2271-limit-menu-height …
> Feat 2271 limit menu height

- src/config.js
- src/modules/map/components/footer/MapFooter.vue
- src/modules/map/components/footer/MapFooterBackgroundSelector.vue
- src/scss/media-query.mixin.scss
As on mf-geoadmin3, remove the footer when on mobile, only show layer attributions, and the scale (if applicable)
[Test link](https://sys-map.dev.bgdi.ch/feat-2437-remove-footer-on-smaller-devices/index.html)
> Feat 2437 remove footer on smaller devices

- src/api/features.api.js
- src/api/height.api.js
- src/api/layers/AbstractLayer.class.js
- src/api/layers/WMTSLayer.class.js
- src/api/search.api.js
- src/api/what3words.api.js
- src/config.js
- src/modules/drawing/lib/__tests__/drawingUtils.spec.js
- src/modules/drawing/lib/drawingUtils.js
- src/modules/drawing/lib/export-utils.js
- src/modules/drawing/lib/style.js
- src/modules/infobox/components/FeatureProfile.vue
- src/modules/infobox/components/styling/SelectedFeatureProfile.vue
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
- src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
- src/modules/menu/components/search/SearchBar.vue
- src/store/modules/position.store.js
- src/store/plugins/geolocation-management.plugin.js
- src/utils/MeasureManager.js
- src/utils/coordinateUtils.js
- src/utils/setupProj4.js
- tests/e2e-cypress/integration/legacyParamImport.cy.js
- tests/e2e-cypress/integration/mouseposition.cy.js
- tests/e2e-cypress/integration/search/search-results.cy.js
In order to fix our "white border" issue, I've switched the default projection system we use to request tiles from our backend to LV95. I've also declared a proper TileGrid for WMTS layers, which should cut the white part that was present on the side of tiles (OpenLayers will not require tiles outside of the extent, plus seems to crop images to fit this extent). This way we should be ready to place the pixelkarte-farbe map on top of a vector tile layer, in order to achieve world wide coverage without compromising on details over Switzerland.
[Test link](https://sys-map.dev.bgdi.ch/use_lv95_for_internal_layers/index.html)
> Use of LV95 as projection for internal layers

- src/modules/drawing/components/DrawingHeader.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/DrawingToolboxButton.vue
- src/modules/menu/MenuModule.vue
- src/scss/variables.scss
- src/setup-fontawesome.js
- src/utils/ButtonWithIcon.vue
- tests/e2e-cypress/integration/drawing/drawing-layer.cy.js
The desktop and tablet UI of the drawing mode now is similar to what we have on "mf-geoadmin3".
I found it confusing for the buttons to switch from red to grey after selecting them like we discussed, as grey is also used when hovering. Also I think that a selected drawing mode should be marked by a single color and not two. That's why for now I left the red marking. 
[Test link](https://sys-map.dev.bgdi.ch/feat-2600-change-drawing-toolbox-ui-for-desktop/index.html)
> Desktop UI of drawing mode now looks similar to "mf-geoadmin3"

- src/modules/map/components/footer/MapFooterBackgroundSelector.vue
So that it catches more the eye, even when you are using a gray BG map (otherwise it blends too much with the map and it's difficult to see there's a button there)
[Test link](https://sys-map.dev.bgdi.ch/add_contrast_to_bg_text/index.html)
> Add contrast to the main BG selector button on desktop

- src/modules/map/components/openlayers/OpenLayersMarker.vue
- src/modules/menu/components/share/MenuShareSection.vue
- src/store/modules/share.store.js
- tests/e2e-cypress/integration/shareShortLink.cy.js
If the user has activated his geolocation, the generated share link (shortlink) will point to his current position with a marker. Geolocation URL param is also removed from the generated shortlink, so that the person opening the link is not placed where he currently stands, but where the person that has generated the link was.
Quick note on static image handling : I had to fix how images were imported in OpenLayersMarker.vue,. Seems like it went through without us noticing, but since Vite migration, static assets can't be imported through a require anymore, but through an import.
[Test link](https://sys-map.dev.bgdi.ch/feat_bgdiinf_sb-2009_sharelink_with_position/index.html)
> BGDIINF_SB-2009: share geolocation position when creating shortlink

- src/modules/menu/components/search/SearchResultList.vue
Adding a small border and shadow box over the search result to separate them from the map. Used the old viewer style for the colors
[Test link](https://sys-map.dev.bgdi.ch/feature_bgdiinf_sb-2211-shadowbox-over-search-result/index.html)
Warning : I messed up when naming the branch. I was checking another ticket and thought its number was for this issue. I changed the PR title.
> BGDIINF_SB-2615 : adding a shadowbox over the search result

- buildspec.yml
- src/modules/infobox/components/styling/DrawingStyleColorSelector.vue
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
- src/scss/webmapviewer-bootstrap-theme.scss
- src/utils/PopoverButton.vue
This PR depends on #268.
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2508-drawing-marker-icons/index.html)
NOTE: There is still a bug on iphone with the stroke of icons. When the icon selection is close, everything works as intended but when it is opened and we change the color, the icon stroke won't but correctly updated (changing from black to white depending on the color). To fix the stroke the use as to close the icon selection and reopen it. I could not find any solution to this bug and it seems that only iphone is affected. Tested on following devices
- Ubuntu Chrome and Firefox : OK
- Android tablet: OK
- **Iphone 11 IOS 16.1 Safari, Chrome, Firefox: NOK**
- Windows Edge: OK
> BGDIINF_SB-2508: Added feedback in drawing marker icon selection

- package-lock.json
- package.json
- src/modules/map/components/footer/MapFooterAppVersion.vue
- vite.config.ts
Unfortunately we cannot make use of the `version` field in `package.json` because it is static which means that we would need to modify it during a PR merge before tagging. They are already tools and github action for such use case, the issue is that they won't work with branch protection as we have.
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2657-versioning/index.html)
> BGDIINF_SB-2657: Added dynamic app versioning based on git tag

- vite.config.ts
The git hash was always appended to the version even if the version was from
a clean tag (not dirty and with extra commit).
By using semverString instead of raw, this solve the issue, but we need to
prepend the `v` prefix.
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2657-versioning/index.html)
> BGDIINF_SB-2657: Fixed versioning

- src/api/features.api.js
- src/modules/drawing/components/DrawingModifyInteraction.vue
- src/modules/drawing/components/drawingInteraction.mixin.js
- src/modules/drawing/lib/drawingUtils.js
- src/modules/infobox/components/FeatureProfile.vue
- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
- src/store/modules/features.store.js
- src/utils/coordinateUtils.js
- src/utils/geodesicManager.js
- tests/e2e-cypress/integration/drawing/geodesicDrawing.cy.js
When drawing a line or a measurement, we use a geodesic line. However the profile
backend did a flat filling to have at least 200 points. This lead to a missmatch
of a few pixels when drawing a line across switzerland.
To solve the issue we use the geodesic points as coordinate to pass to the
profile backend, this way the filling is done by the frontend instead of the
backend.
[Test link](https://sys-map.dev.bgdi.ch/bug-bgdiinf_sb-2608-profile/index.html)
> BGDIINF_SB-2608: Fixed missmatch between profile and geodesic line

- buildspec.yml
- package.json
- vite-plugins/generate-build-info.js
- vite.config.ts
This allow a better deployment approach on S3. We can copy first the versioned
assets directory (containing the images but also the javascript and css code)
into S3 without disturbing the current version, once it is copied, we
can copy the public files from the root and finally the index.html.
This procedure reduce the risk of downtime.
I tried to put also the public files in a versioned directory but this is quite complex and require also to implement parsing and changes in the index.html. So I left them at the root to keep it simple and out of the box.
[Test link](https://sys-map.dev.bgdi.ch/feat-bgdiinf_sb-2671-dist-version/index.html)
> BGDIINF_SB-2671: Put assets in version directory during build

- src/modules/menu/components/menu/MenuSettings.vue
From Jira Issue : https://jira.swisstopo.ch/browse/BGDIINF_SB-2651
For testing purpose, we had a layout switch button that allowed to change from desktop to mobile. Now that the responsive design is efficient, we no longer need it.
[Test link](https://sys-map.dev.bgdi.ch/feat_bgdiinf_sb-2651-remove-layout-switch-button/index.html)
> Feature : Removing layout switch button

- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/menu/MenuModule.vue
- src/store/modules/map.store.js
- src/store/plugins/click-on-map-management.plugin.js
- tests/e2e-cypress/integration/infobox.cy.js
- tests/e2e-cypress/integration/mouseposition.cy.js
- tests/e2e-cypress/integration/search/search-results.cy.js
- tests/e2e-cypress/support/commands.js
Reworked click on mobile device. Implementation is as stated in the ticked, but with one small modification. If one needs to right click or long click to display the location popup only depends on the input device (mouse or touch screen) and not on the the ui mode (desktop or phone ui). On the other hand, if fullscreen mode can be activated or not only depends on the ui mode and not on the input device.
@pakb Can you please test the if long click to display the location popup works on IOS? I have read that safari may not implement correctly the oncontextmenu event. I have already a fix ready, but only want to add it if it is really necessary.
[Test link](https://sys-map.dev.bgdi.ch/feat-2235-rework-click-on-mobile-device/index.html)
> Feat 2235 rework click on mobile device

- vite-plugins/generate-build-info.js
so that the CI can still decipher which branch it is running on, and window users can still build the project
[Test link](https://sys-map.dev.bgdi.ch/feat-replace-unix-specific-script/index.html)
> Replace UNIX specific script in build pipeline

- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
- src/modules/map/components/openlayers/utils/addLayerToMap-mixins.js
Do not set the z-index anymore by reordering the layers in the layers array, but by setting the zIndex property of the layer, so the z indicies can be set to anything without having to fear to throw an index out of bounds exception.
This new way of definining the z indices has also the advantage that the z indices do not need to follow a strict chronological order anymore. But I haven't tried to simplify this code for the moment.
[Test link](https://sys-map.dev.bgdi.ch/bugfix-2660-index-out-of-bounds-in-addlayertomap/index.html)
> BGDIINF_SB-2660: Fixed index out of bounds exceptions when adding layers

- src/modules/drawing/DrawingModule.vue
and thus going under the base layer while drawing
[Test link](https://sys-map.dev.bgdi.ch/bugfix-bgdiinf_sb-2660_fix_drawing_layer_zindex/index.html)
> BGDIINF_SB-2660 : fix drawing layer not having a zIndex

- tests/e2e-cypress/integration/mouseposition.cy.js
This test did sometimes not pass without a useful info of the failure reason.
Hopefully with this changes we can have a better understanding why this test
is sometimes failing.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-mouseposition-e2e/index.html)
> Improved mouse position e2e tests

- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/LocationPopupCopyInput.vue
- src/modules/map/components/LocationPopupCopySlot.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
Various bugfixes and improvements, see commits message for more details.
- Added border to position css triangle, needed on light background to add more contrast
- Fixed some error handling
- Do not display qrcode on mobile display
- Fixed long What3Words which pushed the copy button on a new line (see printscreen below)
Now the Whats3word is truncated with ellipsis, but you can still copy the whole address with the copy button. The position label space has been also reduced to let more space for the values. This reduced the risk of what3words truncate which now happens quite rarely.
Here below is an example of a truncate what3words
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2662-position-popup/index.html)
> BGDIINF_SB-2662: Various bugfixes on position popup

- src/api/features.api.js
- src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/utils/styleFromLiterals.js
- src/modules/menu/components/search/SearchResultCategory.vue
- src/utils/__tests__/legacyKmlUtils.spec.js
Some GeoJSON layers were not displayed correctly. Styling with a geometry type
of `point` where not displayed due to a wrong string comparison (`'point' === 'Point'`)
Also sometimes we could have a crash due to a non existing layer object which
was due to the fact that when hovering a search result a layer is created and
asynchronously the layer style was loaded, meanwhile when the hover is gone
the layer is destroyed which can happen before the layer style load from backend.
Updated some missing event in emit list to prevents vue warning.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2683-geojson/index.html)
> BGDIINF_SB-2683: Fixed GeoJSON layers

- src/modules/infobox/components/FeatureList.vue
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
Change the style of html popup to match mf-geoadmin3:
Was before:
And now is:
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2683-popover/index.html)
> BGDIINF_SB-2683: Improved html popover style

- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/infobox/InfoboxModule.vue
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
In infobox for html popup we don't want any padding while we need padding for
other infobox elements (drawing infos,...).
In the drawing popover the button margin was applied to all div elements instead
of just the buttons. This has been fixed.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2683-popover-new/index.html)
> BGDIINF_SB-2683: Fixed padding in infobox and popover

- src/modules/infobox/components/FeatureElevationProfilePlot.vue
When resizing the windows or on mobile when switching between portrait
and landscape, the method updateElevationProfilePlot() crashed because it is
executed within a promise and due to timing the refs.profilePlot might be null.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-elevation-profile-crash/index.html)
> Fixed elevation profile crash on windows resize

- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
Prevention of doubling of a WMS layer at the opposite site of the globe:
In order to prevent a WMS layer from appearing twice, once in CH and once close to New Zealand, pretty much the same fix as for WMTS was applied.
See: https://github.com/geoadmin/web-mapviewer/commit/c689f9a650c546c6e52a91fc2086d7cbbf48faa2
[Test link](https://sys-map.dev.bgdi.ch/preview/fix_bgdiinf_sb-2682_no_more_doubling_of_wms_layers_on_other_side_of_globe/index.html)
> Fix_BGDIINF_SB-2682 no more doubling of wms layers on other side of globe

- src/config.js
- src/modules/map/MapModule.vue
- src/modules/map/components/WarningRibbon.vue
- src/modules/map/components/footer/MapFooterAppVersion.vue
- src/modules/menu/components/header/HeaderSwissConfederationText.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/header/SwissFlag.vue
- src/scss/variables.scss
- src/store/modules/ui.store.js
- tests/e2e-cypress/integration/footer.cy.js
- tests/e2e-cypress/integration/ribbon.cy.js
Display a warning ribbon like: https://test.map.geo.admin.ch/
The test link won't work as the ribbon is only shown if `DEV_SITE_WARNING` is set to False and the hostname is matching `WARNING_RIBBON_HOSTNAMES`. Build locally and run `npm run preview`  (production preview)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2678_warning_banners/index.html)
> BGDIINF_SB-2678 Made the test banner dynamic based on hostname

- src/modules/drawing/DrawingModule.vue
- tests/e2e-cypress/integration/drawing/kml.cy.js
When closing the drawing menu without creating any drawing an empty kml was
created and added to the menu in the map displayed.
TODO:
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2668-empty-drawing/index.html)
> BGDIINF_SB-2668: Fixed empty drawing being saved and displayed in menu

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/lib/export-utils.js
Now if the loading of the KML failed in the drawing mode, we remove the
kml layer as it is not selectable and we print an error message. The loading
of the kml to translate it to a drawing will be automatically retried. In case
of error we also display an error message at the same place as for saving error.
Those errors message are also now displayed in red.
Also renamed the savingStatus to drawingState which refer more to a drawing state
to make the code clearer as it is also used to check if any modification on
the drawing has been done.
Improved the error handling and user experience in case of network failure.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2729-save-drawing/index.html)
> BGDIINF_SB-2729: Fixed save KML drawing error handling - from post review of #326

- src/modules/map/components/openlayers/OpenLayersPopover.vue
Due to the popover arrow we could not anymore move the kml element in drawing
mode.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2737-move-drawing-element/index.html)
> BGDIINF_SB-2737, BGDIINF_SB-2729: Fixed kml drawing element move

- src/store/plugins/click-on-map-management.plugin.js
- tests/e2e-cypress/integration/mouseposition.cy.js
If a location popup was displayed and then we were entering the drawing mode,
the location popup was not cleared and stayed in drawing mode.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2738-location-popup/index.html)
> BGDIINF_SB-2738: Fixed location popup in drawing mode

- src/config.js
- src/modules/map/components/footer/MapFooterBackgroundSelector.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/OpenLayersVectorLayer.vue
- src/store/plugins/load-layersconfig-on-lang-change.js
- tests/e2e-cypress/integration/layers.cy.js
There's an issue because our style.json doesn't define any boundary or extent with the embedded WMTS, and tiles are requested outside of Switzerland (resulting in many HTTP 404 responses). Same with the PBF tiles, they are not more detailed outside of Switzerland, looking a bit weird without any satellite imagery on top.
[Test link with SwissImage BG selected](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2305_vector_imagery_bg_layer/index.html#/map?bgLayer=ch.swisstopo.leichte-basiskarte-imagery_world.vt)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2305_vector_imagery_bg_layer/index.html)
> BGDIINF_SB-2305 : replace SwissImage WMTS layer with VectorTile

- src/App.vue
- src/config.js
- src/main.js
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/modules/map/components/LocationPopupCopySlot.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/modules/menu/components/menu/MenuTray.vue
- src/scss/tippy-theme.scss
- src/utils/PopoverButton.vue
The popover button uses tippy and its style has been broken due to the import
of the tippy css. Tippy css can only be imported globally to work. So in order
to not broke the popover button styling. I created a new tippy theme for it.
Also fixed the location popup tippy language change, before when the language
setting changed the tippy language was not updated.
Also use the light-border theme as default for tooltips.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2736-tippy/index.html)
[Test link with legacy drawing](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2736-tippy/index.html#/map?lang=it&lat=46.74122&lon=7.812521&z=7.617&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&layers=ch.astra.wanderland-sperrungen_umleitungen,f;ch.swisstopo.swisstlm3d-wanderwege,f;ch.b …
> BGDIINF_SB-2736: Fixed tippy PovoverButtons (drawing styling and time selector)

- src/api/features.api.js
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/utils/legacyKmlUtils.js
On initial load of legacy drawing, it was not visible. To make it visible we
had to toggle the visible flag.
This was a race condition between the icons backend and the kml backend. In
order to display legacy drawings we need to have the icons sets information
from the icons backend. In our case the kml was loaded and added to openlayer
before the icons backend answered.
Now we update the drawing features on changes from the icons backend.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2728-legacy-drawing/index.html)
> BGDIINF_SB-2728: Fixed legacy drawing initial load

- src/api/layers/AbstractLayer.class.js
- src/api/layers/GeoAdminAggregateLayer.class.js
- src/api/layers/KMLLayer.class.js
- src/api/layers/LayerTimeConfig.class.js
- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingToolbox.vue
Because the layers object are saved into the store, they are made reactive and
also cannot be changed outside a mutation. However there is some cases where
we want to change a copy outside a mutation in order to update the layer config
in the store. We do this with the clone() method. However this method did
not deeply cloned the objects.
In order to avoid using external library like lodash to do correct deep clone,
the clone method is overwritten in each subclass when needed.
This fix a future issue for the kml drawing admin id that needs to be removed
when exiting the drawing menu.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2733-drawing-admin-id-part-1/index.html)
[Test link with legacy drawing](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2733-drawing-admin-i …
> BGDIINF_SB-2733: Fixed layer cloning

- adr/2021_03_16_url_param_structure.md
- src/api/layers/KMLLayer.class.js
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/utils/legacyLayerParamUtils.js
- tests/e2e-cypress/integration/legacyParamImport.cy.js
- tests/e2e-cypress/support/commands.js
The admin id in url is camel case `adminId` not lower case.
Also updated the ADR with more examples.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2746-legacy-url/index.html)
> BGDIINF_SB-2746: Fixed legacy url parsing for adminId

- src/modules/infobox/InfoboxModule.vue
- src/modules/infobox/components/FeatureCombo.vue
- src/modules/infobox/components/FeatureEdit.vue
- src/modules/infobox/components/FeatureElevationProfile.vue
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/store/modules/map.store.js
- src/store/plugins/click-on-map-management.plugin.js
Issue : user made kmls were not selectable outside the drawing mode
Fix : We made them selectable, and applied a read only property on them to hide the edition buttons, even if they were not usable outside the drawing mode.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix_bgdiinf_sb-2709-drawings-not-interactive-out-of-drawing-mode/index.html)
> BGDIINF_SB-2709 bugfix : drawings not interactive out of drawing mode

- package-lock.json
- package.json
- src/config.js
- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/map/components/openlayers/OpenLayersVectorLayer.vue
- src/store/plugins/load-layersconfig-on-lang-change.js
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/integration/mouseposition.cy.js
Reverts default ECH BG layer to given value (from topics) and add light base map behind `pixelkarte-farbe`, instead of switching to light base map by default.
Light base map is now added as an option in the BG selection wheel, and if chosen will be rendered in full (no exclusion over Switzerland).
The exclusion of data over Switzerland with LightBaseMap still occurs if it is used behind `pixelkarte-farbe`
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2744_switch_vt_layer_usage/index.html)
> BGDIINF_SB-2744: Switch VectorTile background layer usage

- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
Before
After
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-empty-layer-display/index.html)
> Add some padding to the empty active layer list

- tests/e2e-cypress/integration/drawing/marker-text.cy.js
- tests/e2e-cypress/support/commands.js
- tests/e2e-cypress/support/drawing.js
The icons API is called also outside of the drawing module, so make the intercept
global on navigating the page. This avoid calling the backend.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-cypress-icons/index.html)
> Add icons API intercept in cypress

- src/App.vue
- src/api/search.api.js
- src/config.js
- src/modules/i18n/components/LangButton.vue
- src/modules/i18n/components/LangSwitchToolbar.vue
- src/modules/i18n/index.js
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/header/HeaderSwissConfederationText.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/header/SwissFlag.vue
- src/modules/menu/components/menu/MenuSettings.vue
- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/search/SearchBar.vue
- src/modules/menu/components/search/SearchResultCategory.vue
- src/modules/menu/components/search/SearchResultList.vue
- src/modules/menu/components/search/SearchResultListEntry.vue
- src/scss/media-query.mixin.scss
- src/scss/variables-admin.scss
- src/scss/webmapviewer-bootstrap-theme.scss
- src/store/modules/search.store.js
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/integration/search/search-results.cy.js
- tests/e2e-cypress/support/commands.js
Now in desktop mode the language toolbar is on top right corner using button
link.
Clean up some old css and made the header more reactive using bootstrap instead
of custom css rules.
Also improved search bar look and feel.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2751-language-menu/index.html)
> BGDIINF_SB-2751: Moved the language toolbar in desktop mode

- src/modules/i18n/components/LangButton.vue
The selected language color did not changed.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2751-lang-selected/index.html)
> BGDIINF_SB-2751: Fixed selected language button color

- tests/e2e-cypress/integration/drawing/kml.cy.js
- tests/e2e-cypress/integration/drawing/line-polygon.cy.js
- tests/e2e-cypress/integration/drawing/marker-text.cy.js
Sometimes for an unknown reason we have to set `{force: true}` on click() in
cypress otherwise cypress return an errors saying that the component is not
visible also it is visible.
Now we make sure before the click({force: true}) that the component is visible.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2182-e2e/index.html)
> BGDIINF_SB-2182: Fixed E2E tests issue with `click({force: true})`

- src/scss/media-query.mixin.scss
The language toolbar from the header did not disapeared on IOS devices which
also prevent displaying the menu button.
Some devices like IOS and gnome web browser doesn't support `or` in css media
queries (`or` is an alias for `,` which has been introduced by Media Queries Level 4)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2751-lang-menu-iphone/index.html)
> BGDIINF_SB-2751: Fixed language menu on IOS devices

- src/modules/menu/MenuModule.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/header/SwissFlag.vue
- src/scss/variables.scss
Wrap Swiss flag in div to better center it, this way its position centered in the space it is given
replaces #374 
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-2784_responsive_swiss_flag/index.html)
> BGDIINF_SB-2784 : fix Swiss flag position on smaller devices

- src/modules/map/components/footer/MapFooterAttribution.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/store/modules/position.store.js
whenever we show the lightbasemap layer behind pixelkarte-farbe, with the new extent detection we were not going through the standard layer pipeline, so we also need to add an exception in the attribution management for this case
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-2783_lightbasemap_copyrights/index.html)
> BGDIINF_SB-2783 : add back light base map copyrights

- src/modules/map/components/WarningRibbon.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
When going in fullscreen mode, the banner now does not appear cut anymore.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-bgdiinf_sb-2790-extend-test-banner-to-cover-screen-under-head/index.html)
> BGDIINF_SB-2790: Test banner now covers screen under the header

- src/modules/menu/MenuModule.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/store/plugins/menu-search-interaction.plugin.js
- In desktop mode, do not hide the menu anymore when showing search results, but still do that in phone mode.
- To make both the menu and the search results visible at the same time, above the size lg, the search bar starts after the menu tray so that the search results do not overlap with the menu.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2793-open-menu-back-after-search-results-hidden/index.html)
> BGDIINF_SB-2793: leave menu open when searching

- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/store/modules/layers.store.js
- src/store/plugins/topic-change-management.plugin.js
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/integration/topics.cy.js
There was a discrepancy between mf-geoadmin3 layer ordering (in the menu and URL) and web-mapviewer way of handling them. In the URL, layers should be ordered from bottom to top, and on the side menu from top to bottom (layer "on top" of the layer stack is the top layer). Topics were an issue as they list their layers to activate in the opposite order (top -> bottom) so I've inverted those layer before importing them.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2792-layer_ordering/index.html)
> BGDIINF_SB-2792 : fix layer ordering

- src/modules/map/components/footer/MapFooterBackgroundSelector.vue
- src/scss/variables-admin.scss
- src/store/plugins/load-layersconfig-on-lang-change.js
- src/store/plugins/topic-change-management.plugin.js
It would be nice to have the original icons to be able to quicly reconstruct the `backgrounds.jpeg` and `backgrounds_mobile.jpeg` file (without quality loss). Left untouched for now.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2788_background_layer/index.html)
> feat_BGDIINF_SB-2788: removing pixelkarte grau background layer

- src/modules/menu/components/search/SearchResultCategory.vue
- src/modules/menu/components/search/SearchResultList.vue
- src/store/modules/search.store.js
- tests/e2e-cypress/integration/search/search-results.cy.js
- Search results use full width on phone
- Search results take more screen real estate
- Do not blink when typing search terms
[Test link](https://sys-map.dev.bgdi.ch/preview/bgdiinf_sb-2789-search-results-full-width-on-phone/index.html)
> BGDIINF_SB-2789: search results full width on phone

- src/router/legacyPermalinkManagement.routerPlugin.js
- tests/e2e-cypress/integration/legacyParamImport.cy.js
Issue : Upon receiving legacy parameters, the application would encode them on reception (which is an expected behavior), then create a new query with those adapted parameters, which would encode them again (For example, a space would become `%20`, then `%2520`).
Fix : We decode the URI parameters before storing them in the new query Parameters, ensuring they won't be encoded twice.
[Test link](https://sys-map.dev.bgdi.ch/preview/bgdiinf_sb-2820-swisssearch-legacy-compatibility/index.html)
> BGDIINF_SB-2820 : legacy parameters double encoded

- src/modules/infobox/components/styling/FeatureStyleEdit.vue
The text boxes of the drawing features are now read only again outside of the drawing mode.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-bgdiinf_sb-2816-drawing-feature-text-box-not-readonly/index.html)
> BGDIINF_SB-2816: drawing feature text boxes read only

- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
Text in the tooltips of features was previously not selectable. This
commit fixes this. The classname map-popover-overlay did not exist.
Removing this classname activates instead the default class name
ol-selectable and ol-overlay-container which makes the text in the
overlay selectable. (The overlay is a child of the openlayersmap which
deactivates selection)
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-bgdiinf_sb-2829-cant-copy-from-tooltip/index.html)
> BGDIINF_SB-2829: Text in tooltips is now selectable

- src/modules/map/components/footer/MapFooter.vue
- src/scss/variables.scss
It makes sense for the menu to be above the infobox in phone mode, as in phone mode the menu is fullscreen and so opens on top of everything else. In desktop mode on the contrary, the menu is open most of the time so a user should never be forced to close the menu just to see a popup. Thats why we leave the popup on top of the menu in desktop mode.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2785-scroll-not-possible-in-catalog-when-tooltip-open-mobile/index.html)
> BGDIINF_SB-2785: Infobox does not hide menu anymore in phone mode

- src/config.js
- src/modules/map/components/openlayers/OpenLayersMap.vue
Adding a configuration variable VIEW_MIN_RESOLUTION to limit the zoom in in the map's view to a reasonable value
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2866_limit_view_min_zoom/index.html)
> feat_BGDIINF_SB-2866 limit zoom value

- src/api/layers/AbstractLayer.class.js
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
Issue : Some layers have no legend, and upon clicking the legend button, the legend popup shows up and looks like it's perpetually loading content.
Fix : We added a `hasLegend` getter in the abstractLayer class, which is then called to decide wheter we show the legend button or not.
Currently, we consider KML and external layers has having no legend. A refinement might be needed further down in the line to ensure layers with legends show the legend icon, but this is sufficient for now.
[Test link](https://sys-map.dev.bgdi.ch/preview/bgdiinf_sb-2859-remomve-legend-icon-when-no-legend/index.html)
> BGDIINF_SB-2859: Removing legend button

- src/modules/map/components/LocationPopup.vue
- src/utils/numberUtils.js
- tests/e2e-cypress/integration/mouseposition.cy.js
Issue : When displaying longitude and latitude, when the last figure of a number was 0, we would display numbers with a different significant number after the decimal.
Fix : We now use the "toFixed" native js function to have a fixed amount of significant numbers after the decimal.
[Test link](https://sys-map.dev.bgdi.ch/preview/bgdiinf_sb-2609-round-position/index.html)
> BGDIINF_SB-2609: consistent rounding

- src/modules/map/components/cesium/CesiumMap.vue
@pakb two small fixes for cesium:
- use `RequestScheduler` to increase the throttling limits, I've only put the wmts and (new) terrain. We can update the list later
- use `CesiumTerrainProvider.fromUrl`, `url` option is deprecated
[Test link](https://sys-map.dev.bgdi.ch/preview/cesium_fixes/index.html)
> Cesium fixes

- package-lock.json
- package.json
- src/modules/map/components/cesium/CesiumMap.vue
- vite.config.ts
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2981-add-cesium-compass/index.html)
> BGDIINF_SB-2981: Add cesium-compass widget

- .env.development
- .env.integration
- .env.production
- src/config.js
- src/modules/map/components/cesium/constants.js
- DEV: https://sys-3d.dev.bgdi.ch/ch.swisstopo.terrain.3d/v1/
- INT: https://sys-3d.int.bgdi.ch/ch.swisstopo.terrain.3d/v1/
- PROD (not yet): https://3d.geo.admin.ch/ch.swisstopo.terrain.3d/v1/
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2949-using-bgdi-terrain-dev/index.html)
> BGDIINF_SB-2949: using bgdi buckets serving the terrain.

- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/utils/cameraUtils.js
- src/router/storeSync/CameraParamConfig.class.js
- src/router/storeSync/__tests__/CameraParamConfig.class.spec.js
- src/store/index.js
- src/store/modules/position.store.js
- src/store/plugins/sync-camera-lonlatzoom.js
- tests/e2e-cypress/integration/3d/navigation.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3007-camera_to_store/index.html)
> BGDIINF_SB-3007: Send cesium camera changes to the store

- package-lock.json
- package.json
This version applies the minimum distance to terrain 
[Test link](https://sys-map.dev.bgdi.ch/preview/bgdiinf_sb-3019_update_cesium-compass/index.html)
> Update cesium-compass to 0.5.0

- src/api/__tests__/search.api.spec.js
- src/api/search.api.js
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/menu/components/search/SearchBar.vue
- src/modules/menu/components/search/SearchResultCategory.vue
- src/modules/menu/components/search/SearchResultList.vue
- src/modules/menu/components/search/SearchResultListEntry.vue
- src/scss/variables.scss
- src/store/modules/map.store.js
- tests/e2e-cypress/integration/search/search-results.cy.js
Issue : When selecting a search option, the pin would then disappear, only remaining on preview.
Fix : The pin clear used to be done when the search selection was no longer selected. It's now called upon selecting a new search item, right before asking to pin the new location
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2927-add-marker-after-address-selection/index.html)
> BGDIINF_SB-2927 : keep pin on search

- package-lock.json
- package.json
- src/modules/map/components/cesium/CesiumGeoJSONLayer.vue
- src/modules/map/components/cesium/CesiumInternalLayer.vue
- src/modules/map/components/cesium/CesiumKMLLayer.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/constants.js
- src/modules/map/components/cesium/utils/addImageryLayer-mixins.js
- src/modules/map/components/cesium/utils/addLayerToViewer-mixins.js
- src/modules/map/components/cesium/utils/addPrimitiveLayer-mixins.js
- src/modules/map/components/cesium/utils/geoJsonUtils.js
- src/modules/map/components/cesium/utils/primitiveLayerUtils.js
- tests/e2e-cypress/fixtures/geojson-style.fixture.json
- tests/e2e-cypress/fixtures/geojson.fixture.json
- tests/e2e-cypress/fixtures/layers.fixture.json
- tests/e2e-cypress/integration/3d/layers.cy.js
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/support/commands.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2980_add_3d_geojson_component/index.html)
> BGDIINF_SB-2980: add GeoJSON and KML layer components for 3d

- src/modules/infobox/InfoboxModule.vue
- src/modules/map/components/MapPopover.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumPopover.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- tests/e2e-cypress/integration/infobox.cy.js
- tests/e2e-cypress/support/commands.js
and also when going from 3D to 2D, the selected features stay selected, and the popup now shows directly at OL or Cesium startup
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-3060_persist_selected_feature_when_going_3d/index.html)
> BGDIINF_SB-3060 : persistence of selected feature when going 3D

- package-lock.json
- package.json
- src/api/layers/AbstractLayer.class.js
- src/api/layers/ExternalGroupOfLayers.class.js
- src/api/layers/GeoAdminWMTSLayer.class.js
- src/api/layers/LayerTypes.enum.js
- src/modules/map/components/footer/MapFooterAttributionList.vue
- src/modules/map/components/footer/MapFooterBackgroundSelector.vue
- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- src/router/storeSync/storeSync.config.js
- src/store/modules/__tests__/layers.store.spec.js
- src/store/modules/layers.store.js
- tests/e2e-cypress/integration/infobox.cy.js
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/integration/topics.cy.js
In the process of calculating the z-index for group of layers, I've found some functionalities that were lacking precision or weren't well test covered or documented.
This includes changes in the layer module :
- Storing the background layer directly as a config object (instead of ID)
- Enabling the setting of the background layer, and visibility of layer, through the layer ID or the config object
- Reworking of addLayer to make sure it creates a clone of any given config object (the one in the args, or the one found in the config) so that the config stays pristine
I've also removed an unnecessary wait in the infobox Cypress test, that was sometime failing for unknown reasons on my local machine (might be also the case on the CI like on https://github.com/geoadmin/web-mapviewer/pull/441) …
> BGDIINF_SB-3105 : layer's z-index rewrite

- src/modules/map/components/cesium/CesiumMap.vue
and not where the camera is positioned, otherwise the view (top-down at the position of the camera) doesn't correspond at all with what the user was seeing in 3D
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-3061_keep_camera_target_when_going_2d/index.html)
> BGDIINF_SB-3061 : keep where the camera is looking at when going back 2D

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingExporter.vue
- src/modules/drawing/lib/export-utils.js
The `<coordinate>` element in KML must be in WGS84 based on the specification.
During export the coordinates where re-projected from WebMercator even if another
projection was used.
> BGDIINF_SB-2890: Fixed KML coordinates format during exports

- src/modules/menu/components/share/MenuShareEmbed.vue
Now the iframe copy input is bigger on its own line which is easier for
the user to see its content.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2430-share-menu-2/index.html)
> BGDIINF_SB-2430: Improved again share embed menu

- src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
When editing a drawing component (marker text or adding a text element)
the viewer crash because the feature watch deep was fired when no
layer was set.
To avoid we only watch on the geometry and make sure that we do have a geometry.
> BGDIINF_SB-2890: Fixed crash when editing a drawing component

- src/api/height.api.js
- src/api/search.api.js
- src/modules/map/components/LocationPopup.vue
- src/store/modules/search.store.js
they now "talk" only in LV95 with the backend, and re-project as needed the output to the required mapping projection
> BGDIINF_SB-2890 : rework how Height and Search API handle projections

- src/modules/drawing/DrawingModule.vue
When selecting a drawing feature outside the drawing mode (to see the details
and descriptions) and then entering the drawing mode, the feature stayed selected
but was not initialized properly to allow edition. This means that we could
edit it, but the changes were not reported to openlayer and thus not saved
on the kml, which means that the changes were lost when exiting the drawing mode.
A simple solution to this issue, is to simply deselect everything on entering
the drawing mode. This also make sense in user point of view.
> BGDIINF_SB-2890: Fixed drawing feature edit

- src/modules/menu/components/menu/MenuTray.vue
- src/router/storeSync/LayerParamConfig.class.js
Until we are on PROD we should not be allowed to edit KML that has been created
by the old viewer, this means that in this case we should not move to the drawing
menu automatically.
[Test link with legacy drawing](https://sys-map.dev.bgdi.ch/preview/bug-legacy-drawing-protection/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=&adminId=5Ual-X6ZQoKc-XOMxkw9yw)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-legacy-drawing-protection/index.html)
> BGDIINF_SB-2685: Fixed legacy KML protection

- src/modules/menu/components/menu/MenuTray.vue
Drawing while in 3d mode is not supported.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2890-drawing-buttons-2/index.html)
> BGDIINF_SB-2890: Disable drawing menu when in 3D mode

- src/api/features.api.js
- src/api/profile/profile.api.js
- src/modules/drawing/components/DrawingLineInteraction.vue
- src/modules/drawing/components/DrawingMeasureInteraction.vue
- src/modules/drawing/lib/drawingUtils.js
- src/modules/drawing/lib/export-utils.js
- src/modules/drawing/lib/style.js
- src/modules/infobox/FeatureElevationProfilePlotCesiumBridge.vue
- src/modules/infobox/FeatureElevationProfilePlotOpenLayersBridge.vue
- src/modules/infobox/components/FeatureElevationProfile.vue
- src/modules/infobox/components/styling/SelectedFeatureProfile.vue
- src/store/plugins/reproject-everything-on-projection-change.plugin.js
- src/utils/__tests__/geodesicManager.spec.js
- src/utils/geodesicManager.js
- tests/e2e-cypress/integration/drawing/geodesicDrawing.cy.js
Fixed the profile tracking when hovering the profile, the point is tracked on the map. This has been brocken when passing to lv95.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2890-profile-tracking/index.html)
> BGDIINF_SB-2890: Fixed elevation profile tracking in lv95

- src/modules/map/components/cesium/CesiumPopover.vue
- src/modules/menu/components/toolboxRight/Toggle3dButton.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3146_fix_drawing_crash/index.html)
> BGDIINF_SB-3146 : Fix: 3D drawing crash on camera move, disable 3D toggle button when draw

- src/modules/infobox/components/ImportContent.vue
- src/utils/file.js
Now the import tool should work regardless of the projection used.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3071-import-url-lv95/index.html)
> BGDIINF_SB-3071, BGDIINF_SB-2890: Update import tool to work with lv95 default projection

- src/store/plugins/geolocation-management.plugin.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-geolocation/index.html)
> BGDIINF_SB-2890: Made the geolocation working with any projection

- src/api/what3words.api.js
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
- src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
- src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/map/components/openlayers/OpenLayersMouseTracker.vue
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
The reprojection for what3words was always done by taking webmercator.
The location popup used only lv95 as projection which was wrong for webmercator
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2890-default-projection/index.html)
> BGDIINF_SB-2890: Fixed what3words in popup location

- src/modules/infobox/components/styling/FeatureStyleEdit.vue
BGDIINF_SB-2854
Issue : Are and length of polygons drawn were not shown
Fix : We now check if the polygon are closed. If they are, we calculate both area and perimeter. If not, we only calculate the perimeter. We then show them in the popup.
Still to do :
Font Awesome Icon for filled area is not loading properly, I need to check this
[Test link](https://sys-map.dev.bgdi.ch/preview/bgdiinf_sb-2854-calculat_area_closed_polygons/index.html)
> BGDIINF_SB-2854 feature : Show area and length of drawings

- src/modules/infobox/components/ImportContentResultList.vue
In the import tool in the result list clicking on a selected result would deselect
it. From a user perspective this don't make sense to unselect because we can
anyway only select one and it is kind of annoying when clicking twice on a
entry.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-import-tool/index.html)
> Fix result selection bug in import tool

- src/modules/map/components/footer/MapFooterAttributionList.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
Both map doesn't fit at all together and it doesn't make sense to use them
as a background.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2890-background/index.html)
> BGDIINF_SB-2890: Removed lightbasemap under pixelkarte in webmercartor

- tests/e2e-cypress/integration/geolocation.cy.js
The map default projection is now LV95 therefore test should be either adapted to use lv95 or set the mercator projection.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2890-geolocation-e2e/index.html)
> BGDIINF_SB-2890: Fixed goelocation e2e tests

- src/modules/menu/MenuModule.vue
- src/modules/menu/components/debug/DebugToolbar.vue
- src/modules/menu/components/debug/ToggleProjectionButton.vue
only shown when we are not on a productive host
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2890_debug_toolbar/index.html)
> BGDIINF_SB-2890 : move projection toggle into a debug toolbar

- src/api/what3words.api.js
- src/main.js
- src/modules/drawing/lib/__tests__/drawingUtils.spec.js
- src/store/modules/position.store.js
- src/store/modules/search.store.js
- src/utils/coordinates/__test__/CoordinateSystem.class.spec.js
- src/utils/coordinates/__test__/coordinateExtractors.spec.js
- src/utils/coordinates/__test__/coordinateUtils.spec.js
- src/utils/coordinates/coordinateExtractors.js
- src/utils/coordinates/coordinateSystems.js
- src/utils/coordinates/coordinateUtils.js
- tests/e2e-cypress/integration/3d/navigation.cy.js
- tests/e2e-cypress/integration/3d/transitionTo3d.cy.js
- tests/e2e-cypress/integration/drawing/kml.cy.js
- tests/e2e-cypress/integration/mouseposition.cy.js
- tests/e2e-cypress/integration/search/coordinates-search.cy.js
- tests/e2e-cypress/integration/search/search-results.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-2890-coordinate-search/index.html)
> BGDIINF_SB-2890 : fix coordinate search

- tests/e2e-cypress/integration/mouseposition.cy.js
The WGS84 output cannot be rounded as it is formatted by openlayer with a fixed
size of digit to 5.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2890-mouseposition-e2e/index.html)
> BGDIINF_SB-2890: Fixed mouse position tests

- src/router/legacyPermalinkManagement.routerPlugin.js
- tests/e2e-cypress/integration/geolocation.cy.js
- tests/e2e-cypress/integration/legacyParamImport.cy.js
The legacy parameter coordinates were not correctly reprojected. This was
due to the fact that the reprojection happened in a loop several times instead
of once.
This has been solved by reorganizing a bit the code.
Also corrected a test case that did not make sense with the new lv95 default
projection. Now all legacyParamImport.cy.js test are passing.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-2890-legacy-param-e2e/index.html)
> BGDIINF_SB-2890: Fixed legacy parameters coordinates

- src/api/features.api.js
- src/modules/menu/MenuModule.vue
- src/store/plugins/reproject-selected-features-on-projection-change.plugin.js
- src/utils/coordinates/coordinateUtils.js
- tests/e2e-cypress/integration/infobox.cy.js
Do not request feature to the backend when we change projection, but only reproject on the fly
Feature API file now only requests feature detail in LV95, and transform/reproject the result into the wanted projection (had some issue with Mercator support in some instances)
Move the debug toolbar a bit down, so that it doesn't cover the middle of the map div. It was failing some tests because of that (Cypress thought something was covering a click on the center of the map)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-2890_fix_infobox_test/index.html)
> BGDIINF_SB-2890: fix infobox test

- src/modules/map/components/footer/MapFooterBackgroundSelector.vue
- src/store/plugins/load-layersconfig-on-lang-change.js
- src/store/plugins/topic-change-management.plugin.js
Now the background are the regular old products, pixelkarte-grau and swissimage
in lv95 projection.
Unfortunately I could not easily add the lightbasemap and the world image
as other options in Web Mercator mode because the current BackgroundSelector
cannot be dynamic, it is made of lots of CSS magics with a hardcoded value
in css on how many background is available. So we cannot have a dynamic number
of available background without reworking the bg selector.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3162-lightbasemap/index.html)
> BGDIINF_SB-3162, BGDIINF_SB-3163: Fixed background in lv95

- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/router/index.js
- src/router/storeSync/CrossHairParamConfig.class.js
- src/router/storeSync/storeSync.config.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/position.store.js
- tests/e2e-cypress/integration/crosshair.cy.js
- tests/e2e-cypress/support/commands.js
So that it may be changed while the app has been loaded, and moved too (without requiring a complete reload)
Will need to wait for #470 to be merged, and then adapt the crosshair center on a projection change
This fixes #451
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-3154_dynamic_crosshair/index.html)
> BGDIINF_SB-3154 : make crosshair URL param dynamic

- src/modules/infobox/components/ImportContent.vue
- src/modules/infobox/components/ImportContentResultList.vue
- src/modules/infobox/utils/external-provider-parsers.js
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
- src/modules/menu/components/menu/MenuTray.vue
- tests/e2e-cypress/fixtures/import-tool/wms-geo-admin-get-capabilities.xml
- tests/e2e-cypress/integration/importTool.cy.js
Some WMS layers don't have a `layer.name` but do have a `layer.title`, like for
instance the https://bio.discomap.eea.europa.eu/arcgis/services/Ecosystem/Ecosystems/MapServer/WMSServer
In this case the import took was successful `Loading OK!` but no result
was displayed and no error was found in the error log !
Now we support also layer without name but with a title and in case the
layer has no title and no name, an error log is printed.
Also when no layers could be imported we also throw an error.
- Also added e2e tests
- Added import tool selection/opened feedback in menu (menu input is now red when the tool is opened
- Automatically close the menu when opening the import tool to avoid overlapping in mobile view
- Close other menu section when opening import tool menu
[Test …
> BGDIINF_SB-3168: Fix external layer parsing error (no `layer.name`)

- src/api/layers/ExternalGroupOfLayers.class.js
- src/modules/infobox/utils/external-provider-parsers.js
- src/utils/ModalWithBackdrop.vue
- tests/e2e-cypress/integration/importTool.cy.js
- tests/e2e-cypress/support/commands.js
- tests/e2e-cypress/support/utils.js
When importing a group of external layers the attribution in the map footer was
missing and the disclaimer popup in the active layers was not displayed when clicking
on the disclaimer icon.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-3170-import-attribution/index.html)
> BGDIINF_SB-3170: Fixed group of external layers attributions

- tests/e2e-cypress/integration/search/coordinates-search.cy.js
All possible coordinates formats are already tested in unittest so no need to
test everything here again.
This will speed up e2e tests but also reduce the number of tests result which
are not cheap if we want to run the tests on cypress cloud.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3187-e2e-tests/index.html)
> BGDIINF_SB-3187: Reduce the number of tests for the search bar

- package-lock.json
- package.json
- scripts/check-external-layers-providers.js
While updating libs, I had issues with ogc-parser as it is using very outdated dependencies. After checking the GitHub repo, I saw it was kind of staled, so I replaced it with OpenLayers function. I had to add some browser API equivalent to NodeJS in order to achieve this (see first lines of the file) as this is then used under the hood by OpenLayers to parse XMLs
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_remove_ogc_parser/index.html)
> Remove lib ogc-parser

- README.md
- package.json
keep only those who are used while working locally, or called by the CI
Also updating the doc (it was also a bit outdated, not containing changes that were brought with Vite migration)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_remove_unused_npm_target/index.html)
> Remove unused npm targets

- adr/2021_03_16_url_param_structure.md
This is based on discussion of this tech talk https://ltwiki.adr.admin.ch:8443/display/PB/2023-11-14  and implementation of #536 
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3180-ext-layers-adr/index.html)
> BGDIINF_SB-3180: Updated URL param ADR for the External Layers

- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/MapPopover.vue
- src/modules/map/components/cesium/CesiumMap.vue
I found that most (of not all) Cesium sandcastles (online examples) have this CSS rule to block touch action, it fixes all issues I experienced with panning while on a mobile device!
I also de-activated the location popup (right-click) on mobile, as it wasn't very consistent how to trigger a right click with a touch screen.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_cesium_mobile_nav_improvements/index.html)
> Improve mobile navigation in 3D

- src/config.js
- src/modules/menu/components/menu/MenuTray.vue
Because the advanced tool are not yet ready we remove it on productive
environment.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-remove-advanced-menu/index.html)
> Temporary remove the advanced tool menu on productive environment

- src/App.vue
- src/modules/drawing/components/DrawingTextInteraction.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/DrawingTooltip.vue
- src/modules/i18n/README.md
- src/modules/i18n/index.js
- src/modules/infobox/components/ImportContent.vue
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/modules/infobox/components/styling/DrawingStyleSizeSelector.vue
- src/modules/map/components/LocationPopupCopySlot.vue
- src/modules/map/components/footer/MapFooterAppCopyright.vue
- src/modules/menu/components/LayerLegendPopup.vue
- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/share/MenuShareInputCopyButton.vue
- src/utils/OpenFullAppLink.vue
meaning legacy : false, and that use of `this.$i18n` is not possible anymore, but it needs to go through `useI18n()` (see i18n/README.md)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_i18n_composition_api/index.html)
> Activate support for Composition API with i18n module

- src/api/layers/GeoAdminGeoJsonLayer.class.js
- src/modules/map/components/openlayers/utils/styleFromLiterals.js
- src/store/index.js
- src/store/modules/layers.store.js
- src/store/plugins/external-layers.plugin.js
- src/store/plugins/load-geojson-style-and-data.plugin.js
so that this logic can be shared between Cesium and OL (was implemented twice in each "flavor")
the styleFromLiterals.js file was modifying values received as function args, I changed that because it was triggering store error (as sometimes, these arguments were coming straight from the store, and are thus immutable outside of a store action)
I also changed the store action "updateLayer" so that the payload can be directly a layer (no need to wrap it in an object anymore)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_load_geojson_data_in_store/index.html)
> Load GeoJSON data on addLayer in a store plugin

- src/utils/ModalWithBackdrop.vue
When clicking outside a modal window the windows was not closed. This was due
to the fact that the modal window took the whole screen overlaping the black
backdrop.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-modal-exit/index.html)
> Fixed modal windows exit on click outside

- src/modules/map/components/openlayers/OpenLayersAccuracyCircle.vue
- src/store/plugins/geolocation-management.plugin.js
It was still set as a WebMercator zoom, disregarding the current projection system Also fixing an issue with the accuracy circle component after migration to composition API (wrong store bindings)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-3210_zoom_start_geolocation/index.html)
> BGDIINF_SB-3210 : fix starting geolocation zoom

- src/store/modules/position.store.js
- src/utils/__tests__/numberUtils.spec.js
- src/utils/coordinates/CoordinateSystem.class.js
- src/utils/coordinates/SwissCoordinateSystem.class.js
- src/utils/numberUtils.js
- tests/e2e-cypress/integration/legacyParamImport.cy.js
So that a mobile user won't have a floating/non-matching zoom level after a pinch/zoom on the map.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-3212_constrain_zoom_levels/index.html)
> BGDIINF_SB-3212 : force matching of our custom zoom levels

- src/modules/map/components/common/z-index.composable.js
as its value is "null", this was not taken into account for z-index calculation (it was assumed visible layers wouldn't hold a null value)
I also simplified the z-index calc function, removing the part that was checking in the BG layers first, as they are added to the computed/variable "visibleLayersHoldingAZIndex" anyway
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_zindex_calc_issue_with_void_layer/index.html)
> Fixing error raised when displaying the Void layer

- src/main.js
- src/utils/click-outside.js
This allow to register a click outside event to an element.
This will be used by #571 
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3194-click-oudside/index.html)
> BGDIINF_SB-3194: Added click-outside directive

- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/store/plugins/external-layers.plugin.js
the store plugin was forgotten when the payload of the "addLayer" action/mutation has been changed to only contain the layer (and not an object with other attributes)
Also the ID for the external layer's component wasn't selected correctly.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_external_wmts_not_loading/index.html)
> Fix external WMTS/WMS loading when added through URL params

- .github/workflows/add-testlink-to-pr.yml
When creating a PR based on another PR, a test deployment was already deployed
but no test link in the PR was generated.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-test-link/index.html)
> Also create test link on PR not based on develop branch

- src/api/layers/AbstractLayer.class.js
- src/api/layers/ExternalGroupOfLayers.class.js
- src/api/layers/ExternalLayer.class.js
- src/api/layers/ExternalWMSLayer.class.js
- src/api/layers/ExternalWMTSLayer.class.js
- src/api/layers/LayerTypes.enum.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/WMTSCapabilitiesParser.class.js
- src/api/layers/__tests__/WMSCapabitliesParser.class.spec.js
- src/api/layers/__tests__/WMTSCapabitliesParser.class.spec.js
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/LayerLegendPopup.vue
Now in the external layer catalogue the legends are also displayed if available.
Also adding the info button on the active layers for external layer.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3194-import-tool-ui-legend/index.html)
> BGDIINF_SB-3194: Added support for external layer legend

- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumToolbox.vue
- src/modules/menu/MenuModule.vue
- src/store/plugins/sync-camera-lonlatzoom.js
as the logic is quite different from when we are dealing with a top-down view (2D).
Gathering all "camera" related Cesium tools in one component, and placing them at the bottom center of the 3D view.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-3214_fix_3d_zoom_in_out_buttons/index.html)
> BGDIINF_SB-3214 : add dedicated zoom in/out 3D buttons

- src/api/layers/ExternalGroupOfLayers.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/WMTSCapabilitiesParser.class.js
- src/api/layers/__tests__/WMSCapabitliesParser.class.spec.js
- src/api/layers/__tests__/WMTSCapabitliesParser.class.spec.js
- src/router/storeSync/LayerParamConfig.class.js
- src/store/plugins/external-layers.plugin.js
- tests/e2e-cypress/fixtures/external-wms-getcap.fixture.xml
- tests/e2e-cypress/integration/layers.cy.js
- tests/e2e-cypress/integration/legacyParamImport.cy.js
This reverts commit 6a3ec3d1714e0561b1ed2d13e4a889cc8d797fd5.
Some external provider original URL return a 302 and are not value for the GetMap.
Therefore keep the URL provided by the GetCapabilities as base URL.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-bgdiinf_sb-3194-external-layer/index.html)
> BGDIINF_SB-3194: Fixed external layer

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingHeader.vue
- src/modules/map/MapModule.vue
- src/modules/map/components/common/mouse-click.composable.js
- src/modules/map/components/openlayers/utils/map-views.composable.js
- src/store/modules/map.store.js
- src/store/modules/ui.store.js
- src/store/plugins/2d-to-3d-management.plugin.js
- src/store/plugins/geolocation-management.plugin.js
Also removing/simplifying the geolocation tracking/untracking when the map is dragged. As we now have a central composable that handles all map interaction, this state isMapBeingDragged was not necessary anymore, it could be handle in the mouse click composable.
The zoom level was not set properly when the view (dependent on the projection) was changed in the OL composable.
I also removed the spinner backdrop from the drawing module when it closes, replacing it by a spinner inside the close button (to give the user a feedback something is happening anyway)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_bgdiinf_sb-3211_fix_zoom_after_going_back_2d/index.html)
> BGDIINF_SB-3211: Fix zoom after going back to 2D

- src/modules/menu/components/LayerCatalogueItem.vue
- tests/e2e-cypress/integration/legacyParamImport.cy.js
The checkbox in the geo catalogue and import tool has been change to add/remove
layer in active layers. Previously it did add the layer if it was not in active
layers and was toggling the layer visibility.
In order to keep a clean and intuitive user interface, the layer config is kept
in one place, which means in active layer, where the visibility, opacity and timestamp
can be configured. In the catalogue we can define which layer can be added or removed.
This also allow click on wrong layer to be removed from the same view which was
previously not possible.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-88-import-improvement/index.html)
> PB-88: Import tool/Geo Catalogue checkbox action changed to add/remove layer

- package.json
- src/App.vue
- src/api/layers/ExternalLayer.class.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/menu/components/LayerCatalogue.vue
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/LayerLegendPopup.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/modules/menu/components/advancedTools/ImportCatalogue/ImportCatalogue.vue
- src/scss/main.scss
- src/utils/components/TextSearchMarker.vue
- src/utils/components/TextTruncate.vue
- tests/cypress/support/component.js
- tests/cypress/tests-component/TextSearchMarker.cy.js
- tests/cypress/tests-component/TextTruncate.cy.js
- Placeholder translation updated
- removed the search bar for the geo catalogue, the regular search bar in the header should be use.
- Added color background on text search emphasize
- Added tooltip for truncated text in catalogue
- Truncate and added tooltip for long layer title in active layers
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-73-search-geo-catalogue-2/index.html)
> PB-73: Several UI improvement in import tool

- src/api/__tests__/print.api.spec.js
- src/api/print.api.js
- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/print/MenuPrintSection.vue
- src/store/index.js
- src/store/modules/print.store.js
- tests/cypress/tests-e2e/menuTray.cy.js
Print layouts are loaded the first time the print menu section is opened
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-110_parse_print_capabilities/index.html)
> PB-110 : add print capabilities parsing and menu section

- src/modules/menu/components/LayerCatalogue.vue
- src/modules/menu/components/advancedTools/ImportCatalogue/ImportCatalogue.vue
- src/scss/main.scss
The provider url size changed when the scrollbar appeared. This was quite
disturbing when toggling the provider list, which could trigger the scrollbar
based on the size of the window.
This has been simply fixed by setting a max size of the import tool.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-import-catalogue/index.html)
> Improve import catalogue provider url size

- src/router/legacyPermalinkManagement.routerPlugin.js
- src/store/plugins/2d-to-3d-management.plugin.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
Transferring legacy parameters for 3D maps including:
- `lon`, `lat`, `elevation`, `pitch`, `heading` into camera position
- Set the `3d` to true
- Set the `sr` to WEBMERCATOR
- Convert the `bgLayer` to use the 3D one
Example of old geoadmin: https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissnames3d&layers_visibility=false,false,false,true,false&layers_timestamp=18641231,,,,&layers_opacity=1,1,1,0.8,1&lon=10.14968&lat=45.51136&elevation=215370&heading=317.946&pitch=-45.394
Example of new geoadmin with old parameter: https://sys-map.dev.bgdi.ch/preview/feat-pb-100-manage-3d-parameters/index.html?lang=en&topic=ech&bgLaye …
> PB-100: Manage camera and 3D parameter from the legacy parameters

- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
- src/modules/menu/components/advancedTools/MenuAdvancedToolsListItem.vue
- src/modules/menu/components/share/MenuShareEmbed.vue
- src/modules/menu/components/share/MenuShareSection.vue
- src/modules/menu/components/share/MenuShareSocialNetworks.vue
- src/modules/menu/scss/menu-items.scss
- vite.config.mts
Also did several menu styling improvements
- add the same hover for each menu items
- Improved import maps padding
- Improved import maps caret icon
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-menu-hover/index.html)
> PB-105: Remove menu share spinner and make embed ui similar to import maps

- src/api/files.api.js
- src/api/layers/AbstractLayer.class.js
- src/api/layers/ExternalLayer.class.js
- src/api/layers/KMLLayer.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/WMTSCapabilitiesParser.class.js
- src/modules/drawing/useKmlDataManagement.composable.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/advancedTools/ImportFile/ImportFileLocalTab.vue
- src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
- src/modules/menu/components/advancedTools/ImportFile/utils.js
- src/store/modules/layers.store.js
- src/store/plugins/external-layers.plugin.js
- src/store/plugins/load-kml-data.plugin.js
- src/utils/__tests__/kmlUtils.spec.js
- src/utils/components/ErrorButton.vue
- src/utils/coordinates/__test__/coordinateUtils.spec.js
- src/utils/coordinates/coordinateUtils.js
- src/utils/kmlUtils.js
- tests/cypress/fixtures/import-tool/empty.kml
- tests/cypress/fixtures/import-tool/external-kml-file.kml
- tests/cypress/fixtures/import-tool/line-accross-eu.kml
- tests/cypress/fixtures/import-tool/paris.kml
- tests/cypress/tests-e2e/importTool.cy.js
Now when importing a KML file we automatically zoom to its extent
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-95-kml-zoom-to-extent/index.html)
> PB-95: Add zoom to KML extent in import file

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingSelectInteraction.vue
- src/modules/drawing/components/useDrawingModeInteraction.composable.js
- src/modules/drawing/lib/export-utils.js
- src/utils/components/TextInput.vue
Now the KML are retro compatible with mf-geadmin3, see test link below which import a KML created by web-mapviewer into mf-geoadmin3
- KML file generated by web-mapviewer: https://sys-public.dev.bgdi.ch/api/kml/files/UguLO2B4RqKGqLosIGOsxA
- Link to mf-geoadmin3 using the file above: https://map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML%7C%7Chttps:%2F%2Fsys-public.dev.bgdi.ch%2Fapi%2Fkml%2Ffiles%2FUguLO2B4RqKGqLosIGOsxA&E=2623716.62&N=1232091.54&zoom=4
In theory the KML are aslo compatible with other KML viewer, but for this it requires first PB-264 to be done.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-114-kml/index.html)
> PB-114: Made KML retro compatible with mf-geoadmin3

- package-lock.json
- package.json
- src/modules/menu/components/advancedTools/ImportFile/ImportFileLocalTab.vue
- src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
- src/modules/menu/components/advancedTools/ImportFile/utils.js
- src/store/modules/layers.store.js
- src/utils/__tests__/extentUtils.spec.js
- src/utils/__tests__/gpxUtils.spec.js
- src/utils/__tests__/kmlUtils.spec.js
- src/utils/coordinates/coordinateUtils.js
- src/utils/extentUtils.js
- src/utils/gpxUtils.js
- src/utils/kmlUtils.js
re-using some parts that were made for KML
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-101_gpx-zoom-to-extent/index.html)
> PB-101 : zoom on GPX extent on file added

- src/config.js
- src/modules/drawing/DrawingModule.vue
- src/modules/menu/components/menu/MenuTray.vue
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/utils/kmlUtils.js
- tests/cypress/fixtures/service-icons/set-default.fixture.json
- tests/cypress/fixtures/service-kml/legacy-mf-geoadmin3.kml
- tests/cypress/support/commands.js
- tests/cypress/support/drawing.js
- tests/cypress/tests-e2e/drawing.cy.js
This is not needed anymore as KML are fully backward compatible. This safety
guards was to prevent modifying prod KML on test.map.geo.admin.ch that would
not work on map.geo.admin.ch, but since PB-114 this is not needed anymore.
[Test link with legacy admin ID](https://sys-map.dev.bgdi.ch/preview/bug-267-kml-admin-id/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.astra.wanderland-sperrungen_umleitungen&layers_opacity=1,1,1,0.8,0.8,1&layers_visibility=false,false,false,false,false,true&layers_timestamp=18641231,,,,,&adminId=egfQtn61TpeBnrZSvwVH_w
)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-267-kml-admin-id/index.html)
> PB-267: Removed adminId guard on non prod hosts

- src/modules/drawing/useKmlDataManagement.composable.js
- src/modules/menu/components/advancedTools/ImportFile/utils.js
- src/router/storeSync/LayerParamConfig.class.js
- src/store/index.js
- src/store/modules/layers.store.js
- src/store/plugins/load-gpx-data.plugin.js
- src/store/plugins/load-kml-data.plugin.js
- src/utils/gpxUtils.js
- tests/cypress/fixtures/import-tool/external-gpx-file.gpx
- tests/cypress/tests-e2e/importToolFile.cy.js
Reworking the KML loading pipeline, which is nearly identical to GPX, to also support this new format
Moving the metadata/data loading parts from the import utils to a dedicated store plugin, so that these things can be loaded on app reload when the layer is added through the URL directly
Add e2e test to cover GPX support
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-101_e2e_test_and_url_support/index.html)
> PB-101 : add support for GPX reloading and e2e tests

- src/api/layers/GeoAdminWMSLayer.class.js
- src/api/layers/GeoAdminWMTSLayer.class.js
- src/api/topics.api.js
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/store/modules/layers.store.js
- src/utils/__tests__/legacyLayerParamUtils.spec.js
- src/utils/legacyLayerParamUtils.js
- tests/cypress/support/commands.js
- tests/cypress/support/drawing.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
Issue : When using legacy parameters with timestamps on time enabled layers, those parameters were not taken into account on the new mapviewer.
Fix: A typographical error stopped the timestamps parameters from being populated, and then we never entered the condition to apply those parameters to the layers. Once this was solved, it appeared we were trying to assign value to a protected element outside a mutation, thus we added a new setter to apply these changes to the layers, even if they're not active yet.
[Test link with legacy timeseries parameters](https://sys-map.dev.bgdi.ch/preview/pb-246-bugfix-legacy-timestamps/index.html?topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.swisstopo.swissimage-product&layers_timestamp=19951231,2002&lang=en&layers_opaci …
> PB-246: bugfix legacy timestamps parameters not taken into account

- src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
- tests/cypress/tests-e2e/compareSlider.cy.js
Issue : tooltip was missing from compare Slider menu component
fix : we now have a tooltip. We also use the same method across the advanced menu to ask for translations, rather than a mix of ways.
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-278-bugfix-missing-compare-slider-tooltip/index.html)
> PB-276 : bugfix missing compare slider tooltip

- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- tests/cypress/fixtures/3d/terrain-3d-layer.json
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/3d/layers.cy.js
- tests/cypress/tests-e2e/drawing.cy.js
In the drawing feature, when changing a text the store got updated after every keystroke, and with this a request was sent.
In this PR a debounce function for ~3~ 0.3 seconds after a keystroke was used to delay the update on the store and minimize the amount of requests being sent.
Ismail: I set the delay to 0.3 seconds since 3 seconds is too long.
Example of the delay:
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-203-debounce-drawing-feat-text-edit/index.html)
> PB-203: Debounce edit text dispatch

- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/3d/layers.cy.js
- tests/cypress/tests-e2e/3d/navigation.cy.js
Avoid intercept confusion and also make sure that all tiles are loaded before
continuing cesium tests.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-e2e-3d/index.html)
> Fix cypress e2e 3d tests

- src/api/features.api.js
- src/api/icon.api.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/utils/__tests__/kmlUtils.spec.js
- src/utils/__tests__/legacyKmlUtils.spec.js
- src/utils/featureStyleUtils.js
- src/utils/kmlUtils.js
- tests/cypress/tests-e2e/drawing.cy.js
Now the KML icon size and text size is retro compatible with the old kml adding a new `extra large` size.
The icon scaling is a bit tricky due to a factor to normalize icons to 32 pixel introduced by open layer in version 6.7 (old viewer used an older openlayer version, see https://github.com/openlayers/openlayers/pull/12695).
Relates to #628 
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-266-icon-size/index.html)
> PB-266: Corrected KML icons size

- src/modules/menu/components/advancedTools/ImportCatalogue/ProviderUrl.vue
When changing the language the import external catalog was triggered even if
no url was provided which resulted in errors
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-lang-change/index.html)
> Avoid error log during language change

- adr/2024_01_31_drawing_icon_size.md
- src/api/features/EditableFeature.class.js
- src/api/icon.api.js
- tests/cypress/support/drawing.js
- tests/cypress/tests-e2e/drawing.cy.js
To export a kml, openlayer requires the icon size in order to compute the
scale. If the icon has not yet been loaded when generating the style then
the icon scale would be computed with a default size of 64px.
The last commit tried to solve this issue in cypress test, but unfortunately
waiting on the icon to be loaded did not always solved the race condition.
I could not find a better way to ensure this as settings the size when
generating the icon style.
This solve temporarly the issue, but in the future we should get the size
from the backend with the others icon metadata.
The icon size test did failed time to time. This was due to a race condition.
The icon scale in KML is set by openlayer and uses a scale factor based on the
icon size. Now if the icon has not yet be loaded during the …
> Fix race condition when exporting/saving kml

- src/store/index.js
adding it anyway, the UI to edit its value won't be added to the app on PROD
[Test link](https://sys-map.dev.bgdi.ch/preview/fix_debug_store_module/index.html)
> Fix error on prod when debug store module is absent

- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/layers.store.js
- src/store/plugins/external-layers.plugin.js
- src/store/plugins/load-geojson-style-and-data.plugin.js
- src/store/plugins/load-gpx-data.plugin.js
- src/store/plugins/load-kml-data.plugin.js
- tests/cypress/tests-e2e/layers.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
The external layers were always put at the top during startup even if they
were in the middle of the layers parameter.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-293-ext-layer-order/index.html)
> PB-293: Corrected external layer order at startup and improve a bit performance

- README.md
- src/store/README.md
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-259-performance-doc/index.html)
> PB-259: Added best practices docu

- tests/cypress/tests-e2e/layers.cy.js
Change should to then, trying to fix the issue we have that only happen on the CI e2e tests
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_fix_dragndrop_e2e_test_on_ci/index.html)
> Fix Drag&Drop e2e test on CI

- src/modules/menu/components/menu/MenuTray.vue
- src/modules/menu/components/topics/MenuTopicSection.vue
- src/router/storeSync/storeSync.routerPlugin.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/drawing.cy.js
- tests/cypress/tests-e2e/importToolFile.cy.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
The rendering of catalogue is very costly and store events would re-trigger it
therefore wait that the map has been rendered before rendering the catalogue,
it is anyway not visible at startup until the user click on the menu entry.
It still needs to be always rendered once the application has been started, otherwise
the toggling of the menu would be too slow.
Also differ the rendering and opening of the active layers for the same reason
and also because if the menu contains external layer (e.g. kml, gpx, ...) the
application needs to load its metadata/data before rendering the correct name
in the list. For kml and GPX it would use at startup the default KML or GPX
name until the name has been loading. By defering the active layers list
we avoid having the name changing.
Several other …
> PB-259: Improve startup performance by rendering menu section only when the map is rendered

- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
Due to drag and drop the layer scroll on touch device was not possible anymore as a touch triggered a drag and drop.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-drag-and-drop/index.html)
> Fix active layers scrolling on touch device

- src/store/modules/position.store.js
- src/utils/__tests__/numberUtils.spec.js
- src/utils/numberUtils.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
so that this values do not extend above 360 (or bellow -360). This was resulting in some e2e test flakiness when a 360 deg would sometimes be interpreted as 360, and other times 0. With this change, it will be way more predictable and consistent
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_fix_camera_angle_unwrapped/index.html)
> Small improvement : wrap camera angles

- src/router/storeSync/LayerParamConfig.class.js
- tests/cypress/tests-e2e/layers.cy.js
When changing the config (opacity, visibility) of an external layer (KML, GPX,
WMS or WMTS) and then use the browser history navigation to revert the changes,
it triggered a reload of the layer and set its name back to the default until
the layer has been reloaded.
We can simply avoid this by updating the current layer object instead of
creating a new one.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-external-layer/index.html)
> PB-322: Avoid reloading external layer upon browser history navigation

- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/__tests__/WMSCapabitliesParser.class.spec.js
- src/api/layers/__tests__/wms-geoadmin-sample.xml
- src/utils/__tests__/legacyLayerParamUtils.spec.js
- src/utils/legacyLayerParamUtils.js
In the legacy viewer the layer title was part of the URL and some layer
could contain a coma in its title which broke the layers parsing as the layers
in URL are separated by coma.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-102-legacy-external-layer/index.html)
> PB-102: Fix legacy external layers with coma in layer tilte

- src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
only react to drag and dropping when the title of the layer is handled, and not the settings area anymore
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_fix_layer_drag_drop_block_settings_events/index.html)
> Fix layer drag and drop blocking transparency slider usage

- src/modules/map/components/common/z-index.composable.js
- src/modules/map/components/openlayers/utils/add-layers-to-map.composable.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/importToolFile.cy.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
- tests/cypress/tests-e2e/layers.cy.js
In this case the layer would have been set to layer zIndex to -1 !
Also improve cy.checkOlLayer() command to check layer zIndex
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-305-visible-reorder/index.html)
> PB-305: Fix layer zIndex after re-ordering and visibility toggling

- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/3d/layers.cy.js
- tests/cypress/tests-e2e/compareSlider.cy.js
- tests/cypress/tests-e2e/drawing.cy.js
- tests/cypress/tests-e2e/importToolFile.cy.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
- tests/cypress/tests-e2e/layers.cy.js
- tests/cypress/tests-e2e/mouseposition.cy.js
and waiting on the animation of the menu to finish before giving the caller the control back (should alleviate some race condition we had with menu open/close and action triggered just after the call to the util)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_add_open_close_menu_mobile_test_utils/index.html)
> Replace the single clickOnMenuIfMobile by two open/close utils

- src/api/layers/ExternalWMSLayer.class.js
- src/api/layers/ExternalWMTSLayer.class.js
- src/api/layers/GPXLayer.class.js
- src/api/layers/KMLLayer.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/layers-external.api.js
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/__tests__/layersParamParser.spec.js
- src/router/storeSync/layersParamParser.js
- src/store/modules/layers.store.js
- src/store/plugins/external-layers.plugin.js
- tests/cypress/fixtures/external-wms-getcap-1.fixture.xml
- tests/cypress/fixtures/external-wms-getcap-2.fixture.xml
- tests/cypress/fixtures/external-wmts-getcap-1.fixture.xml
- tests/cypress/fixtures/external-wmts-getcap-2.fixture.xml
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
- tests/cypress/tests-e2e/layers.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
Avoid loading multiple times the WMS/WMTS capabilities and avoid doing multiple
dispatch.
This reduce the startup time especially with multiple layers of the same source
we can gain several seconds.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-259-update-layers/index.html)
> PB-259, PB-329: Improve external WMS/WMTS layers startup performance

- src/modules/map/components/common/z-index.composable.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
The logic has two issues, one is that for group of layers we counted always
one index too much, and that for the on top of all layers we did not took the
group of layers into account.
This solve the issues in the e2e tests for the external layers.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-339-layers-zindex/index.html)
> PB-339: Fix layer z-index computation

- src/modules/infobox/components/styling/FeatureStyleEdit.vue
Apparently the debouncing of the feature title and description in drawing together
with the save drawing debouncing creates a race condition when editing the title
and/or description and closing the drawing mode. In this case the save kml
triggered by the title/description update debounced happens only when the
drawing mode is closed and when the drawing layer has removed all its
feature which result to saving an empty drawing, clearing the existing drawing.
To avoid this we speed up debouncing, this is not a perfect fix but it works
and I could not find a way of correctly cleaning up the debouncing for
the closing drawing menu event.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-drawing-save/index.html)
> PB-341: Fix race condition in drawing e2e tests

- tests/cypress/tests-e2e/geolocation.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
We are adding tests for every official legacy parameter
Only missing now : 
`bod-layer-id` and `showTooltip` which are part of PB-190
`time` which is not yet implemented and will be part of PB-307
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-113-legacy-test-coverage/index.html)
> PB 113: Legacy test coverage

- src/router/appLoadingManagement.routerPlugin.js
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/utils/__tests__/utils.spec.js
- src/utils/components/OpenFullAppLink.vue
- src/utils/utils.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/embed.cy.js
The legacy embed view was at hostname/embed.html. Unfortunately we cannot reroute
here to another path before the #, because the vue router using the createWebHashHistory
can only handle route after the hash. Therefore we have an external redirect
service  that will redirect to /embed.html to ?legacyEmbed.
We use this pseudo legacyEmbed to redirect to #/embed once the other legacy
parameters have been translated.
NOTE: I first tried to set the redirect service directly to #/embed but then it made the startup procedure difficult as we needed to detect if other legacy parameters had to be translated and wait on them first. So for simplicity we use a legacy parameter as redirect
which simplify a lot the startup procedure which is then identical for other legacy parameters.
[Test …
> PB-315: Handle legacy embed view

- src/modules/map/components/CompareSlider.vue
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/CompareSliderParamConfig.class.js
- tests/cypress/tests-e2e/compareSlider.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
In most of the code, we are using camelCase for our parameters and variables
The compare slider was using snake_case.
We are now using camelCase for the compareRatio parameter, and the compareSlider data-cy
[Test link](https://sys-map.dev.bgdi.ch/preview/compare-slider-case-change/index.html)
> Compare Ratio Case Change

- src/modules/map/components/toolbox/FullScreenButton.vue
- src/modules/map/components/toolbox/GeolocButton.vue
- src/modules/map/components/toolbox/TimeSliderButton.vue
- src/modules/map/components/toolbox/Toggle3dButton.vue
- src/modules/map/components/toolbox/ZoomButtons.vue
- src/utils/useTippyTooltip.js
Make more sense to use the tippy default placement in the composable as using
the one needed for the toolbox.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-tooltip/index.html)
> Let the tippy placement default for the composable

- src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
- tests/cypress/tests-e2e/importToolFile.cy.js
In import file when entering enter with an invalid url field, it triggered a
page reload. This was due to the fact that the `loadFile()` was triggered with
an invalid url which triggered a fetch to the current host, reloading the app.
Now we prevent calling loadFile() if the url is not valid.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-294-import/index.html)
> PB-294: Avoid reloading the application when entering ENTER in import file

- src/api/features/EditableFeature.class.js
- src/api/features/LayerFeature.class.js
- src/api/features/SelectableFeature.class.js
- src/api/features/features.api.js
- src/modules/drawing/components/useDrawingModeInteraction.composable.js
- src/store/plugins/reproject-selected-features-on-projection-change.plugin.js
- src/utils/identifyOnVectorLayer.js
- src/utils/kmlUtils.js
moving isDragged to EditableFeatures because it is used only in this context moving extent to base class, as we might want to use it across the board (also with drawing)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-103_arg_constructor_features/index.html)
> PB-103 : arg constructor for SelectableLayers and children

- src/modules/map/components/CompareSlider.vue
Because the layers can be duplicate we need to take the one on top of the open layer
list, not that this list is by default not by zindex sorted.
The compare slice needs also to be done each time any layers from the list
changes its visibility otherwise the compare ratio is not applied to the correct
layer.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-332-compare/index.html)
> PB-332: Fixed compare slider with duplicate layers and also visibility flag bugs

- src/modules/map/components/cesium/CesiumGeoJSONLayer.vue
- src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
- src/store/plugins/load-geojson-style-and-data.plugin.js
- src/utils/geoJsonUtils.js
- src/utils/identifyOnVectorLayer.js
- tests/cypress/fixtures/layers.fixture.json
- tests/cypress/tests-e2e/layers.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-207_geojson_data_autoreload/index.html)
> PB-207 : GeoJSON data autoreload

- src/store/modules/__tests__/layers.store.spec.js
Those tests were testing the deprecated function to compute z-index in the store
that was not anymore used and have been removed.
I tried to unit-test the new z-index composable computation but unit-testing
of such composable is quite complex and I stopped trying to do it after a little
while.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-332-unit-test-zindex/index.html)
> PB-332: Removing zindex unit-tests

- src/api/features/features.api.js
- tests/cypress/fixtures/external-wms-getcap-2.fixture.xml
- tests/cypress/tests-e2e/layers.cy.js
For external WMS that do not support the current projection of the map, but can handle another we support, we fallback to that to build the request instead of failing
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-363_getfeatureinfo_mixed_projection/index.html)
> PB-363 : authorize request in a different projection as the map

- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/LayerParamConfig.class.js
- src/utils/__tests__/legacyLayerParamUtils.spec.js
- src/utils/legacyLayerParamUtils.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/featurePreSelection.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
Translate the {bod-layer-id} parameter from the legacy viewer to the new 'selected features' layer parameter.
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-190-legacy-param-for-bodlayerid/index.html)
> PB-190 : implement legacy support for bod layer id parameter

- src/modules/map/components/common/mouse-click.composable.js
- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
- src/store/modules/map.store.js
instead of using our own grown functions, it was very hard to detect shapes such as image from a marker (whereas OL has that built-in right away)
We will have to rework how Cesium does it too
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-166_vector_feature_selection_with_ol/index.html)
> PB-166 : use OpenLayers to detect vector features

- src/modules/menu/components/advancedTools/ImportFile/ImportFileLocalTab.vue
On the import tool local file, the input had a tabindex but the user could
do nothing with its focus because this field is readonly. Moreover due to the
form, when pressing enter on this input field it reloaded the page.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-import-file-tool/index.html)
> Fix import tool local file tabindex

- .prettierrc
- package-lock.json
- package.json
- src/utils/components/TextInput.vue
- src/utils/kmlUtils.js
- tests/samples/kml/alpen.kml
- tests/samples/kml/atomGeneratorGlacier.kml
- tests/samples/kml/externalContent.kml
- tests/samples/kml/legacy-chsdi3-icon-urls.kml
- tests/samples/kml/print.kml
Some kml out there could still be on legacy version icon url that are not anymore
reachable. mf-geoadmin3 was already dynamically changing those legacy url format
to a new format (which is now with the new viewer also legacy) and would therefore
still support such kml.
Now in the new viewer we also support all type of legacy icon urls and dynamically
change the url to the new format, so that only the new format will be fetched.
NOTE: Some internal openlayer still first try to fetch old urls format but I
could not figure out why.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-347-kml-samples/index.html)
> PB-347: Added support for legacy geoadmin icon url

- src/api/print.api.js
- src/api/shortlink.api.js
- src/modules/map/components/openlayers/utils/usePrint.composable.js
- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
- src/modules/menu/components/print/MenuPrintSection.vue
- src/store/modules/print.store.js
- src/store/modules/share.store.js
- src/store/plugins/loading-bar-management.plugin.js
The print area preview composable was doing the preview, the printing and also coffee. It is now only responsible for the preview area. I also took the opportunity to remove from the store things that weren't making much sense being there, as no one else as the print menu section was using them (and as the menu section is now the one triggering the print job, it's much clearer this way)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_split_print_functions/index.html)
> Move "print" job logic and management out of area composable

- src/router/storeSync/layersParamParser.js
- src/utils/geoJsonUtils.js
The new @features param wasn't checking that it was looping over features with layer, creating error when selecting drawing features
The geometry of a feature came sometimes directly from the store, and was shallow-cloned only by reproject utils. Vuex was then raising an error because reproject attempted to modify something coming from the store. We now deep-clone the geometry before passing it to reproject
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_fix_geom_vuex_and_feature_no_layer/index.html)
> Fix two bugs regarding selected features

- src/modules/map/components/toolbox/TimeSlider.vue
since we are working on the time Slider implementation, we might as refactor it with the composition API
[Test link](https://sys-map.dev.bgdi.ch/preview/compose-api-timeslider/index.html)
> PB-318: refactor time slider to composition API

- src/api/layers/ExternalWMTSLayer.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/WMTSCapabilitiesParser.class.js
- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersMap.vue
- src/modules/menu/components/advancedTools/ImportCatalogue/useCapabilities.js
- src/utils/coordinates/coordinateSystems.js
- tests/cypress/fixtures/external-wms-getcap-2.fixture.xml
- tests/cypress/tests-e2e/layers.cy.js
- WMS projection case sensitivity
- Fixed external layer timeout issue for jura.ch
- Fixed external wmts layer for solotuhrn
- implemented available projections for external WMTS.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-361-external-layer/index.html)
> PB-361: Divers External Layers bug fixes

- src/modules/menu/components/search/SearchResultListEntry.vue
The preview layer was not clear when selecting the layer, which let the layer
on top of the stack until a new layer preview was set. Due to this the user
had the impression that it could not changed its active layer configuration
because the preview was still on top.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-370-preview-layer/index.html)
> PB-370: Clear preview layer on selection

- package-lock.json
- package.json
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-111-upgrade-mapfishprint/index.html)
> PB-111: Update geoblocks/mapfishprint to v0.2.11

- src/api/layers/GPXLayer.class.js
- src/store/plugins/external-layers.plugin.js
- src/store/plugins/load-geojson-style-and-data.plugin.js
- src/store/plugins/load-gpx-data.plugin.js
Some GPX file might not have metadata and it is ok to have it null. Due to this GPX file without metadata could not be loaded correctly. When no metadata was present, even if the file was a local file, the load gpx data plugin was triggered. On a deployment we could see an error on HTTP where the plugin tried to load GPX file on https://sys-map.dev.bgdi.ch/FILE_NAME while on localhost it tried to do on localhost which gave a differant answer.
So this triggered some weird bug. Now we allow GPX without metadata and only trigger the GPX load plugin when no data is present regardless of the metadata
Also make sure to set the layer error in case of GPX load failure
Also Avoid unnecessary store dispatch in layers plugins
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-gpx-local/index.html)
> Fix GPX local file import

- src/api/print.api.js
- src/modules/map/components/openlayers/utils/usePrint.composable.js
Now we set the pdf file name to HOSTNAME_DATETIME.pdf
Also fixed lang parameter that was not sent to print server. This parameter is
used to translate the disclaimer see also PB-383.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-390-file-name-pdf/index.html)
> PB-390, PB-391: Change the pdf print file name and fixed print lang parameter

- src/api/print.api.js
This is needed to avoid having red square for tiles that failed.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-296-print-flag/index.html)
> PB-296: Add failOnError to all layers

- src/api/print.api.js
The dev backend as currently some issues therefore temporarily change it to
int.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-397-tempo-print-int-backend/index.html)
> PB-397: Temporary change print backend from dev to int due to dev backend issue

- src/api/print.api.js
Reverts geoadmin/web-mapviewer#768 due to mapfish print bug https://github.com/mapfish/mapfish-print/issues/3255
[Test link](https://sys-map.dev.bgdi.ch/preview/revert-768-feat-pb-296-print-flag/index.html)
> Revert "PB-296: Add failOnError to all layers"

- src/modules/menu/components/search/SearchBar.vue
- src/modules/menu/components/search/SearchResultList.vue
- tests/cypress/tests-e2e/search/search-results.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-396-make-search-result-dropdown-disappear/index.html)
> PB-396: Make search result dropdown disappear when going to location

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/map/components/openlayers/utils/usePrint.composable.js
- src/modules/menu/components/print/MenuPrintSection.vue
Now provide a success, aborted or failure feedback
NOTE currently the failure feedback can be tested using a KML layer with a measure which is currently failing.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-398-print-error-mgmt/index.html)
> PB-398: Improve print UI user feedback

- src/api/features/SelectableFeature.class.js
- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
Issue : When selecting a drawing feature outside of the drawing mode, an error log would appear in the console explaining there were no coordinates.
Second Issue : when creating a drawing feature, an error log would appear in the console log explaining the same issue
Fix : We use 'getCoordinates()' instead of 'coordinates' in the map interactions composable.
Second Fix : when creating a Feature with no coordinates (undefined), we set them to null in the constructor.
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-404-log-error-on-selecting-drawing-feature/index.html)
> PB-404 bugfix: removing error on drawing selection

- src/modules/menu/components/search/SearchBar.vue
- src/router/storeSync/abstractParamConfig.class.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/layers.store.js
- src/utils/utils.js
- tests/cypress/tests-e2e/search/search-results.cy.js
When clicking on a search bar result make sure to set the focus back on the search bar, so the user can quickly edit the search if needed.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-396-search-focus/index.html)
> PB-396: Updated search bar e2e tests

- src/modules/map/components/openlayers/utils/usePrint.composable.js
- tests/cypress/tests-e2e/print.cy.js
The attribution (copyright) on the pdf was empty.
Also add the background layer attribution if any background.
Fix duplicate print legends. We could duplicate some layers with different opacity, but when printing we need to make sure to have their legend only once.
Added attribution, language and filename tests. Also tested duplicate layer
in print.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-389-print-attributions/index.html)
> PB-389: Fix print attributions and duplicate legends

- src/modules/menu/components/advancedTools/ImportFile/__tests__/utils.spec.js
- src/modules/menu/components/advancedTools/ImportFile/utils.js
Based on the KML standard the kml tags can be with `kml:` prefixed. This
issue has been mentioned on the old viewer. see https://github.com/geoadmin/mf-geoadmin3/issues/5310
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-440-prefixed-kml/index.html)
> PB-440: Allow prefixed KML

- src/api/print.api.js
- src/modules/map/components/openlayers/utils/usePrint.composable.js
- src/store/modules/print.store.js
- src/utils/styleUtils.js
- tests/cypress/fixtures/print/capabilities.json
- tests/cypress/tests-e2e/print.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-360-gpx-print-style/index.html)
**Old Geoadmin:**
**New Geoadmin:**
**Old Geoadmin:**
**New Geoadmin:**
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-360-gpx-print-style/index.html)
> PB-360: Update gpx line style and adjust line stroke width for printing.

- package-lock.json
- package.json
WMS layer based on the WMS specification, prints background in white unless
the query parameter TRANSPARENT is set to true.
Geoadmin layers have a bug and their default behavior is transparent=true instead
of false, see https://jira.swisstopo.ch/browse/PB-439
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-438-print-transparent/index.html)
> PB-438: Fix transparency of external WMS layers in print

- src/modules/map/components/openlayers/utils/styleFromLiterals.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-304-treasurehunt-layer-not-displayed/index.html)
> PB-304: Treasurehunt layer not displayed

- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersGPXLayer.vue
- src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/map/components/openlayers/OpenLayersVectorLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- tests/cypress/tests-e2e/layers.cy.js
Issue : when modyfing the opacity of an external WMS layer and setting it to 0, it would instead revert to its default config value (1 in most cases)
Cause : Opacity of a layer could be set by its parent (parentLayerOpacity). When this was set to 0, the computed check `parentLayerOpacity.value || wmsLayerConfig.value.opacity` would consider the 0 to be a 'false' and use the config value instead.
Fix : We switch the || operator to the ?? operator, which will only use the config value if the parentLayerOpacity is null. We did this change in all layers type to be on the safe side.
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-418-bugfix-transparency-external-layers/index.html)
> PB-418: bugfix opacity in WMS layers

- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/SharePopup.vue
- tests/cypress/tests-e2e/drawing.cy.js
The KML share url did not contained the KML| prefix which then loaded an
empty map (without any layer).
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-463-drawing-share-link/index.html)
> PB-463: Fix KML share url

- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumVectorLayer.vue
- src/modules/map/components/cesium/utils/primitiveLayerUtils.js
this should enhance the look and feel of buildings. Removing config that was set to better place/set shadows, as we won't be using this approach to "color" building facades (too costly performance wise).
Also adding a FPS counter when not on PROD staging.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-475_add_post_processing/index.html)
> PB-475 : Activate a couple post-processing shader in Cesium

- package-lock.json
- package.json
- src/api/print.api.js
- src/utils/__tests__/geodesicManager.spec.js
- src/utils/geodesicManager.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-360-measurement-label/index.html)
Sample Link: https://s.geo.admin.ch/5xjzz9drm7gy
OL view: ![image](https://github.com/geoadmin/web-mapviewer/assets/1421861/1f36b595-bc18-4fda-9c25-d1754d8982d3)
Print result: ![image](https://github.com/geoadmin/web-mapviewer/assets/1421861/9b0792f6-e049-428c-bb04-fb2ba1a3ed77)
Sample link: https://sys-s.dev.bgdi.ch/uv66dijlpvys
OL view:
Print result:
Sample URL: https://s.geo.admin.ch/st54zbvdmieo
OL View:
Print result:
Sample link: https://sys-s.dev.bgdi.ch/k08kma0aqc7s
OL View: 
Print Result:
- On the old geoadmin, the font size in the marker and text become bigger in the print. I am not sure why, I already checked the payload both are using font size = 16
[Test …
> PB-360: measurement label

- src/modules/map/components/toolbox/TimeSlider.vue
- tests/cypress/tests-e2e/timeSlider.cy.js
When closing the timeslider, if it was modified in any way manually by the user, we save the year for all current layers. Also removed the numbers in the tests so that we don't have to re-enumerate each time we make a modification within the tests.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-443-set-year-on-timeslider-close/index.html)
> PB-443: Set year on timeslider close

- src/api/layers/layers.api.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-474-aggregate-layer-not-loaded/index.html)
Test link with aggregate layer: https://sys-s.dev.bgdi.ch/0uj5kdwptahk
Regarding the client side zoom, I guess I still need to wait for the fix merged first (https://github.com/geoadmin/web-mapviewer/pull/810)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-474-aggregate-layer-not-loaded/index.html)
> PB-474: Add missing sublayer to fix missing aggregate layer on the map.

- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
I use a simple approach here to set the zindex to something very high. I have checked the suggested approach in the ticket (using systemLayers), but it's not handling the addition to the map. Is it intended for this kind of use case?
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-448-missing-print-area-layer/index.html)
> PB-448: Make sure print area layer always on top.

- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
- src/modules/menu/MenuModule.vue
- src/modules/menu/components/print/MenuPrintSection.vue
- src/store/modules/print.store.js
- src/store/modules/ui.store.js
- tests/cypress/tests-e2e/print.cy.js
The print scale on mobile was empty. This was due to the fact that we took the menu width in the computation for the scale.
Now we don't take the menu width for the scale computation and we move the print center a bit down due to the header overlapping the map.
Also did some renaming to make the code clearer
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-437-print-scale/index.html)
> PB-437: Fix print scale

- src/modules/map/components/toolbox/TimeSlider.vue
- tests/cypress/tests-e2e/timeSlider.cy.js
Issue : when clicking on the time slider bar, the years would not be saved in the layers when removing the time slider.
Fix : we do it now
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-319-years-not-saved-on-click/index.html)
> PB-319: Bugfix on time slider click not keeping changes when closing the time slider.

- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- tests/cypress/tests-e2e/layers.cy.js
Issue : On all labels for layers, we mention that we're modifying the transparency, when we are currently modifying the opacity.
fix : we reverse the value on the transparency slider, committing `1 - value` to the layer's opacity rather than the value.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-481-reverse-transparency-slider/index.html)
> PB-481: bugfix apply transparency instead of opacity

- src/modules/map/components/toolbox/TimeSlider.vue
- src/scss/main.scss
**RFC**
This could be one possible solution. It only addresses the font and the margin of the time slider though. There could potentially be other things that break with the cesium style. (1)
Another solution could be to re-order the css. For that, we'd have to prematurely load Cesium's `widgets.css` I guess, before our other rules are applied. The drawback would be that there's always cesium style around even if the 3d map isn't used. 
Open for other suggestions.
(1)
Although, when scanning through the `Cesium/Widgets/widgets.css`, the only other global style apart from `input` is `ul`. Everything else is a `.cesium-` prefixed class. So maybe it won't break too much.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-jira-pb-493-time-slider-cutoff/index.html)
> PB-493: Fixed Time slider input cutoff on 3d Maps

- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
Issue : When using the mapviewer on mobile, the time selector button had its text cut out.
Fix : When on mobile view, we no longer enforce a width on the button, letting it fill the space to accommodate its content.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-498-time-selector-cut-on-mobile/index.html)
> PB-498: Fixed time selector css on mobile

- src/modules/map/components/toolbox/TimeSliderButton.vue
The styling, which moved the Time Slider to the right, was on the wrong screen selectors, making it slide underneath the Menu on the left.
Fixed this by moving the styling to a lower screen size selector.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-468-time-slider-underneath-menu/index.html)
> PB-468 Fixed Time-Slider sliding under the menu on smaller screens

- src/modules/menu/scss/topics-image.scss
Issue : When opening the topic change popover, the images would not show anymore. This was due to the relative link in the css being incorrect.
Fix : We change the relative link to reach the correct location.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-502-topic-images-not-showing/index.html)
> PB-502: fix topic images absence

- tests/cypress/support/commands.js
As it was placing coordinate all around the LV95 extent, tests could get really flaky when wanting to show a tooltip (it was sometimes at the edge of the viewport, making it hidden)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-368_fix_coordinate_randomizer/index.html)
> PB-368 : fix e2e test feature coordinate randomizer

- src/modules/map/components/toolbox/TimeSlider.vue
The time band was so wide that the cursor was rendered weirdly when dragged to the very end of the time band:
On suggestion of Brice, I narrowed the band so that the cursor will always have the necessary
space to be displayed properly:
In the process, I also fixed a little display bug, where the arrow wasn't really in the middle of the cursor (or rather, the cursor wasn't centered above the arrow):
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-468-time-slider-arrow-shift/index.html)
> PB-468 Fix arrow shift of time slider on the edges

- src/utils/logging.js
In production build debug and info messages were printed when they shouldn't
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-507-log/index.html)
> PB-507: Fix logging in production build

- src/modules/map/components/openlayers/utils/printConstants.js
- src/modules/map/components/openlayers/utils/usePrint.composable.js
- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
- src/modules/map/components/toolbox/Toggle3dButton.vue
The previous code from the old geoadmin was working by chance and when there is an internal change in the OpenLayers, it breaks. See the further discussion https://github.com/openlayers/openlayers/issues/15820
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-486-rotating-map-print-area/index.html)
> PB-486: Fix print area when map is rotated

- src/api/print.api.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-373-missing-label-on-json-layer/index.html)
- Sample: https://sys-s.dev.bgdi.ch/2et28t3xms6i
- OL Rendering: 
- Print result:
- With PR #843 (correct offset, font)
**Remarks:**
The style of the label (rectangle with text inside) is not easily replicable in MapFish Print (same as the measurement label). So, I guess this is the best that we can do for now.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-373-missing-label-on-json-layer/index.html)
> PB-373: Fix missing label on GeoJSON layer

- package-lock.json
- package.json
- src/router/appLoadingManagement.routerPlugin.js
- src/router/index.js
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/app.store.js
Issue : in some occasions, the router plugins would process the legacy query correctly, but not switch to the map view once it was done, staying stuck in the legacy view forever and not showing anything.
This happened when there was no change to make to the query due to default parameters not being in the URL, but still needing a redirect to the map view.
Fix : If we change the store and the view should change, we ask for a query change too
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-447-broken-legacy-parser/index.html)
> PB-447: legacy parser not switching to map view

- package-lock.json
- package.json
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
- src/utils/layerUtils.js
Now when clicking on play on the time slider the layer is updated and not
removed/added which made a flickering effect.
Also solve the WMS time enabled layer which were not updated upon timestamp changes (via time config or time slider).
NOTE: The time slider flickering effect for 3D mode is not solved with this and cannot be easily solved as apparently Cesium doesn't support to update a layer, or at least I could not find a way.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-518-slider-smooth/index.html)
> PB-518: Fix timeslider flickering and WMS time enabled layer update

- src/api/layers/LayerTimeConfigEntry.class.js
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/cesium/utils/addImageryLayer-mixins.js
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- src/utils/layerUtils.js
WMS time enabled layer were not updated when changing their timestamp. This
was also an issue on 3D.
NOTE that for WMS all timestamps means that no TIME query param must be set.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-451-wms-time-enalbed/index.html)
> PB-451, PB-518: Fix WMS time enabled layer update

- src/api/features/features.api.js
- src/api/layers/ExternalWMSLayer.class.js
- src/api/layers/ExternalWMTSLayer.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
[Test link with External WMS with time config](https://sys-s.dev.bgdi.ch/ay6qfhgvhdo3)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-496-wms-time-external/index.html)
> PB-496: Added External WMS time config support

- src/api/print.api.js
- src/modules/i18n/index.js
- src/store/modules/i18n.store.js
Use the date formatting based on the locale (en => MM/DD/YYYY, H:MM PM/AM, fr-CH => DD.MM.YYYY, HH:MM
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-530-print-date/index.html)
> PB-530: Added print date to the print API spec

- src/api/layers/ExternalLayer.class.js
- src/store/modules/layers.store.js
At startup we never know the projection of the external layers, the projection
is taken from the capabilities that needs to be loaded first. Therefore don't
test projection upon creation and don't do any fallback.
Also fixed an issue when a layer has only one timestamp, the time slider was
displayed but the user could not change the timestamp.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-496-external-layer-projection/index.html)
> PB-496: Fix external layer error and time slider issue

- src/views/MapView.vue
Currently on Cesium changing the year is removing/adding the layer which
is not so nice when using the slider play feature as it result to a flickering
effect.
The way Cesium is configured don't allow us to do layer update. It seems that
we could do it with a state management system but would required a big rewrite
of 3D.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-518-remove-slider-3d/index.html)
> PB-518: Removed time slider on 3D view

- src/api/iframeFeatureEvent.api.js
- src/store/plugins/click-on-map-management.plugin.js
- src/views/EmbedView.vue
using postMessage API to send the feature ID and layer ID of selected features to parent
Can be tested in the this codepen (by changing the URL from test.map.geo.admin.ch to this PR's testlink) [codepen here](https://codepen.io/geoadmin/pen/dyEXVKo)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-506_iframe_feature_selection_event/index.html)
> PB-506 : embed sends information to parent about selected features

- src/store/modules/features.store.js
- src/views/EmbedView.vue
the old viewer also sends feature events when the map is added to an iframe without pointing to its "embed.html" page, so we have to mimic the same behavior. Now sending this postMessage event whenever a layer feature is selected
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-506_send_event_regardless_of_embed/index.html)
> PB-506 : send feature event regardless of embed mode

- src/modules/i18n/locales/en.json
- src/modules/map/components/toolbox/TimeSlider.vue
- src/modules/map/components/toolbox/TimeSliderButton.vue
- src/modules/map/components/toolbox/TimeSliderDropdown.vue
- src/modules/map/components/toolbox/TimeSliderDropdownSearchList.vue
- src/modules/map/components/toolbox/useRangeTippy.js
- tests/cypress/tests-e2e/timeSlider.cy.js
On small screens (but not mobile) show a Dropdown instead of the time slider.
- Add Dropdown on the time slider for small devices such as tablets
- Fix the play button icon
- Refactor the data flow in the time slider
- Prevent from updating layers with invalid year data
- Debounce the store updating
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-501-dropdown-timeslider-on-tablets/index.html)
> PB-501 Show dropdown for year selection in the time slider on tablet screens

- src/modules/map/components/common/mouse-click.composable.js
- src/modules/map/components/common/z-index.composable.js
- src/modules/map/components/openlayers/OpenLayersAccuracyCircle.vue
- src/store/modules/geolocation.store.js
- src/store/plugins/geolocation-management.plugin.js
The geolocation tracking on non touch device was canceled as soon as the mouse
moved on the map, even if not action was undertaken ! Now we use the setCenter
to cancel the tracking, unless the setCenter is triggered by the geolocation.
Also did some improvement using the geolocation API by allowing cached location
and setting a timeout.
Also when re-activating the geolocation we first set the previous location
to make the app more reactive.
Also fixed the geolocation z-index, the geolocaiton marker would have been put behind new layers.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-521-goelocation/index.html)
> PB-521: fix geolocation tracking, zindex and accuracy and several geolocation improvements

- src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
- src/utils/layerUtils.js
Fix supports for 0.1 resolution
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-555_load_resolution_0dot1/index.html)
> PB-555 : fix too many resolutions being filtered out with WMTS layers

- src/utils/kmlUtils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-568_support_empty_kml_coord/index.html)
> PB-568 : guard against empty KML feature coordinate

- src/modules/map/components/cesium/CesiumInternalLayer.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
removing the visible flag being used, we already remove the component altogether when the visibility flag is false, and it hinders aggregate from being displayed (sub-layers have their visibility flag set to false in the config for some reasons...) Also removing the subdomain for WMS, as we are fine landing always on the main URL endpoint (and can be problematic for external layer support)
Note : a good aggregate layer candidate is the RBD layer loaded by default in the displayed map (will be a WMTS for a while and switch to a WMS when closer to the ground)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-228_aggregate_in_3d/index.html)
> PB-228 : add aggregate layer support to 3D

- src/modules/map/components/cesium/CesiumGeoJSONLayer.vue
- src/modules/map/components/cesium/CesiumInternalLayer.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/toolbox/ZoomButtons.vue
- tests/cypress/tests-e2e/legacyParamImport.cy.js
Cesium CSS was altering how our buttons were shown, adding some padding or margins there and there. As we were importing the Cesium CSS file just to place the canvas (and its Cesium generated parent divs) correctly, I've switched to declare this CSS ourselves and remove the import of the Cesium CSS file.
Also removing a couple wrapping divs in the Cesium component that are not useful, as they clutter our "real" DOM with many empty divs
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-543_fix_cesium_css_spillover/index.html)
> PB-543 : fix Cesium CSS spillover

- src/router/storeSync/LayerParamConfig.class.js
External layers (kml, gpx, wmts, wms) at the bottom of the stack where replaced
by default topic layers during startup if the layers came from a legacy link.
This issue was due to a performance  improvement that avoid to recreated layer
object if it was already present, but this performance improvement did not check
if the layer at index was the correct ID.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-574-layers-param/index.html)
> PB-574: Fix layers parameter issue at startup

- src/utils/__tests__/kmlUtils.spec.js
- src/utils/__tests__/legacyKmlUtils.spec.js
- src/utils/kmlUtils.js
- tests/cypress/tests-e2e/print.cy.js
forcing this resulted in KMLs being misrepresented, with colors not matching what was in the KML's data
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-562_wrong_external_kml_style/index.html)
> PB-562 : do not force drawing module's style onto external KMLs

- src/modules/map/components/cesium/CesiumKMLLayer.vue
using stock Cesium classes to load KMLs instead of relying on ol-cesium bridge transforming the Cesium KML component into a composition API component in the process (exit mixins)
Adding a couple tweaks depending on the geometry type :
- disabling depth with terrain testing with labels (always visible) and adding more outline
- clamping icons (billboard) to the terrain, so that they aren't clipped by it
- lowering the default alpah/transparency of polyline/polygon material, to ease the visualization of underlying buildings and other features
- forcing clamping to ground for polyline, meaning a measure line will follow the terrain, always
Note : see JIRA ticket for good KML sample to be tested
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-591_3d_kml_improvments/index.html)
> PB-591 : 3D KML improvements

- src/modules/map/components/cesium/CesiumMap.vue
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/PositionParamConfig.class.js
- src/router/storeSync/ZoomParamConfig.class.js
- src/store/plugins/sync-camera-lonlatzoom.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
Removing 2D position URL params when 3D is active to diminish issues when we load the app directly in 3D. When zoom and/or position are present, the 3D viewer would react to changes in these values. This was creating some race condition issue at startup when a camera position was also described in the URL.
Camera initialization has also been separated from the logic to move the camera after init, so that we have a clearer logical decision (with logging)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-548_camera_after_reload/index.html)
> PB-548 : fix camera position present in URL at startup issue

- src/router/legacyPermalinkManagement.routerPlugin.js
- tests/cypress/tests-e2e/drawing.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
Legacy parameter in LV95 were not set as center resulting to the bottom left corner of LV95 set as projection
Also legacy parameter X/Y can be given either in LV95 or LV03 projection so when given in Lv03 we needed to convert them.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-517-legacy-center/index.html)
> PB517, PB-588: Fixed legacy X/Y parameter in LV03 and LV95

- src/api/lv03Reframe.api.js
- src/modules/map/components/LocationPopupPosition.vue
- src/utils/components/CoordinateCopySlot.vue
- tests/cypress/tests-e2e/mouseposition.cy.js
Using proj4 isn't accurate enough on a geodesic point of view, as the conversion isn't linear. There's a backend service that does the computation in a proper manner, so that's what is being used here when showing a LV03 value in the location popup. Tracking the mouse position while moving the cursor can still be done with a simple matrix transform, it's "good enough"
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-583_use_backend_to_get_lv03/index.html)
> PB-583 : use backend service to get LV03 <> LV95 conversion right

- src/modules/drawing/components/SharePopup.vue
When sharing a drawing, only the KML layer was added to the query params.
On the old viewer the full url param were added to the share url which provide
then the same view as the view the drawer used (e.g zoom level, center, layer
stacking, background, ...)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-607-drawing-share/index.html)
> PB-607: Fix drawing share URL: use full query params in share url

- src/modules/map/components/MapPopover.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
- src/utils/composables/useMovableElement.composable.js
The pointer was not set to `move` on the movable window header. Also clicking
on the window header buttons (close, print, ...) triggered also a move event
which is unwanted.
Made also the use movable composable usable if the component is not mounted
and fixed default params.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-movable-window/index.html)
> Fix tooltip movable window pointer and icon issues

- src/router/legacyPermalinkManagement.routerPlugin.js
- tests/cypress/tests-e2e/drawing.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
they were in the correct order, we broke the testlink generator (and subsequently all shortlinks) when we swap those
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-588_revert_e_n_legacy_changes/index.html)
> PB-588 : revert changes made to E and N in legacy parser

- src/modules/i18n/index.js
- src/store/modules/i18n.store.js
The `-CH` local suffix is not supported by our API backend. The default
language was set to the default browser language which could be de-CH or fr-CH.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-621-default-lang/index.html)
> PB-621: Fixed default lang with `-CH` suffix

- .env.development
- .env.integration
- .env.production
- src/api/__tests__/file-proxy.api.spec.js
- src/api/file-proxy.api.js
- src/config.js
- src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
this should enable Dropbox/Google Drive/name your cloud provider users, for which the provider has explicitly not implemented CORS header, to still be able to import their file on our viewer.
This is a temporary solution to ease the go-live, but we need to think long-term how we want to deal with that (or if we want to stop supporting it)
Send me a PM on Slack to get a valid URL to my dropbox, I've uploaded a sample KML there
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-570_service_proxy_for_kml_and_gpx/index.html)
> PB-570 : use service-proxy for failed KML/GPX URL import

- src/api/layers/GeoAdminLayer.class.js
- src/api/layers/GeoAdminWMSLayer.class.js
- src/api/layers/GeoAdminWMTSLayer.class.js
- src/api/layers/layers.api.js
- src/modules/map/components/cesium/CesiumMap.vue
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/store/modules/cesium.store.js
- src/store/modules/layers.store.js
- src/store/plugins/2d-to-3d-management.plugin.js
- src/store/plugins/load-layersconfig-on-lang-change.js
- tests/cypress/fixtures/layers.fixture.json
- tests/cypress/tests-e2e/footer.cy.js
and improve how we parse WMS layer config, taking into account possible "wmsLayers" property
This means that the BG layer set in the URL stays the same while going 3D, and CesiumMap component looks up for 3D equivalent for any WMS/WMTS (background included) if they are defined.
This should fix the issue we had with `ch.bazl.luftfahrthindernis` in 3D, where the "Last updated" label was on each tile (3D can't load a single tile WMS, so there's a specific 3D config for this one, among others)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-542_proper_3d_layer_selection/index.html)
> PB-542 : take into account "config3d" layers config property

- src/modules/i18n/index.js
- src/store/modules/i18n.store.js
Instead of mapping locale to our i18n, which seems to break lang change after app startup, revert this part and improve the way we detect the default locale from the navigator available locales. This should alleviate the issue with only 'xx-CH' locales present in the browser's setting, while still enabling the lang change after startup
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-621_lang_issue/index.html)
> PB-621 : fix issue where lang can't be changed anymore

- src/api/layers/layers.api.js
Those layers were called using `current` as their timestamp were added to their
config.
For the layer `ch.swisstopo.swissimage-product_1946` this was an issue as it
only supported `1946` as timestamp and not `current`.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-622-wmts-unique-timestamp/index.html)
> PB-622: Fix timed layer with only one timestamps

- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumMouseTracker.vue
- src/store/modules/cesium.store.js
- src/utils/coordinates/CoordinateSystem.class.js
- src/views/MapView.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-494-3d-address-bar/index.html)
> PB-494: Add address bar on 3D map

- src/router/legacyPermalinkManagement.routerPlugin.js
enable users to use URLs withouth `#/map` notation (easy boarding)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-639_prevent_parsing_non_legacy_layers/index.html)
> PB-639 : prevent parsing of non legacy layers URL param

- src/api/files.api.js
KML defined in the layers URL param weren't treated the same way as when we import them through the import file tool.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-570_also_proxy_kml_on_load/index.html)
> PB-570 : also proxy KML loaded at startup

- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
- src/modules/menu/components/settings/HelpLink.vue
Reverts geoadmin/web-mapviewer#911 
It contained also the PR #910 
[Test link](https://sys-map.dev.bgdi.ch/preview/revert-911-bug-pb-546-print-overlay/index.html)
> Revert "PB-546: Put print overlay always on top"

- src/store/modules/layers.store.js
- tests/cypress/tests-e2e/layers.cy.js
When changing the language the timed layer where reset to their default time
parameter.
The issue is that only their current year where updated but not their current
timestamp.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-637-time-layer-config-lang/index.html)
> PB-637: Keep time layer selected year when changing the language

- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
Somehow, probably due to an openlayer update, the print overlay was not anymore
centered on the map on HiDPI and Retina devices (e.g. Iphone, Dell XPS 15, HP ZBook G9).
After some test it turns out that the issue arised only when the DEVICE_PIXEL_RATIO
was not 1. Removing this ratio from the computed print area solved the issue.
This ratio in the print area has been introduced in 2014 in the old mf-geoadmin3
project (see https://github.com/geoadmin/mf-geoadmin3/pull/1359)
in order to solve the same issue observed here on HiDPI and Retina
device. This issue has been probably solved internally in openlayers now.
To test use Iphone and/or our HP zbook G9 without external display.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-546-print-overlay-center/index.html)
> PB-546: Print overlay not centered on high resolution device (e.g. Retina or HiDPI device)

- src/modules/map/components/openlayers/OpenLayersRectangleSelectionFeedback.vue
When using CRTL + selection when we already had a drag selection, an uncaught
exception occurred. Although everything seems to work fine, having uncaught exception
is not so good.
So now in order to avoid this exception we first need to remove the selection
layer in every case before re-adding it if needed.
See 
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-multi-selection/index.html)
> Fix uncaught exception when using drag selection

- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
When panning the map moved faster than the cursor.
This was due to the fact that default openlayer map interactions (like map panning)
were added twice.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-633-panning/index.html)
> PB-633: Fix map panning being too fast

- src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
- tests/cypress/tests-e2e/print.cy.js
Sometimes the initial default print scale was under the header which is not so
nice. This was due to the fact that the map is under the header and that during
the scale computation we took only one header height in consideration but the
print overlay is then center on the whole map, not only on the visible map.
To avoid this issue we take twice the header size now.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-546-print-scale/index.html)
> PB-546: Improved default print scale computed from map size

- src/config.js
- src/modules/infobox/InfoboxModule.vue
- src/modules/map/components/MapPopover.vue
- src/store/modules/ui.store.js
- tests/cypress/tests-e2e/drawing.cy.js
- tests/cypress/tests-e2e/featureSelection.cy.js
- tests/cypress/tests-e2e/infobox.cy.js
- tests/cypress/tests-e2e/legacyParamImport.cy.js
Issue : On mobile, small screen sizes could create issues where the head bar was partially inaccessible. In landscape mode it could appear under the header, which made it impossible to use, and in vertical mode, part of it was behind the right side menu.
Fix :
In landscape mode, we set the height of the tooltip to be the minimum between 350 pixels (previous value) and 60% of the viewport height, which ensure the head bar of the tooltip is never under the header.
In vertical mode, if the width of the screen is smaller than 400 pixels, we enforce the feature info position to be set as 'bottompanel' and we remove the button to set it as a floating tooltip. This is called both when setting the info position and on resize.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-587-tooltip-be …
> PB-587: altering feature info behavior on mobile

- tests/cypress/tests-e2e/layers.cy.js
Since this PR is merged on develop those test are often not passing because
it seems that when trying to open the menu settings a second time it opened
the give feedback view somehow.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-e2e-flaky/index.html)
> Try solve test flakiness introduced by #922

- src/modules/map/components/cesium/CesiumGPXLayer.vue
- src/modules/map/components/cesium/CesiumInternalLayer.vue
- src/modules/map/components/cesium/CesiumMap.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-497-gpx-on-3d/index.html) (can be tested with loading gpx file)
- Load GPX to Cesium with Cesium standard way
- Add style for point to match with the old geoadmin (red circle billboard)
- Handle transparency update
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-497-gpx-on-3d/index.html)
> PB-497: Add GPX on 3D map

- src/modules/infobox/components/FeatureElevationProfilePlot.vue
When resizing the window from small to big the elevation profile was not re-render
properly.
See https://www.chartjs.org/docs/master/configuration/responsive.html#important-note
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-660-profile-size/index.html)
> PB-660: Fix elevation profile resize

- src/modules/map/components/footer/MapFooterAttributionItem.vue
Some attribution are not link and cannot be clicked. In this case they should
be selectable. Previously all attributions were not selectable and they all
had the pointer cursor.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-647-attributions/index.html/#/map?lang=en&center=2660000,1190000&z=1&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&layers=ch.meteoschweiz.messwerte-lufttemperatur-10min)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-647-attributions/index.html)
> PB-647: Fix CSS non link attribution

- src/modules/infobox/components/FeatureDetail.vue
- src/modules/infobox/components/FeatureListCategory.vue
- src/modules/infobox/components/FeatureListCategoryItem.vue
Various issues with the tooltips CSS:
sometimes, features titles were too big
sometimes, the space between the attribute name and the attribute value was too small and hard to read.
sometimes, the alignment between an attribute's name and its value was a bit off, as they were centered on a cell (when the value or the name took more than one line to display)
Fix : We adapt the CSS for those elements, and add a tippy on top of the feature title when it's truncated.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-586-improve-tooltip-css/index.html)
> PB-586 improve tooltip css

- src/modules/infobox/components/FeatureList.vue
- src/store/modules/features.store.js
RFC:
Issue : When changing languages, the tooltip did not update to the chosen language and we had to close it and select the features again to see the change
Cause : The features selection process uses calls to the backend that are language dependant. Upon changing the language, we did not change the selected features, meaning they were still in the store with the old language tooltip within.
Fix : A watcher checks language changes when there is a tooltip and update the selected Features
Still to do : currently, changing the language removes the drawings from the selection. Editable Features Selection seems to behave strangely (I can't seem to retrieve them from the store). I'll investigate this further.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-585-tooltip-translation-not …
> PB-585: make tooltip reactive to language change

- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
as we need to fix or find a solution for this, and it will take too much effort before go-live, we de-activate the opacity slider to convey to the user it doesn't work in 3D.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-662_disable_opacity_slider_gpx_kml_3d/index.html)
> PB-662 : disable opacity slider for KML/GPX on 3D

- src/utils/coordinates/SwissCoordinateSystem.class.js
by misreading our own documentation, we added an extra zoom level on LV95. For unknown reason (maybe to better match our printable product) resolution 1.5 (from Mercator pyramid) is skipped by LV95. Adding it was breaking backward compatibility with URLs that had zoom level greater or equal to 10
[Test link](https://sys-map.dev.bgdi.ch/preview/bug_pb-630_remove_extra_zoom_level/index.html)
> PB-630 : removing extra LV95 zoom level

- src/api/features/features.api.js
- src/router/storeSync/LayerParamConfig.class.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/featureSelection.cy.js
This layer requires to give the coordinate and other params in order to get
the correct feature.
So in the htmlpopup and in the get feature request we pass the coord, imageDisplay
and mapExtent parameter like in the identify request. This was done like this
in the old viewer. No idea why we need those parameters though.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-634-feature-selection/index.html)
[Test Link with legacy feature pre-selection](https://sys-map.dev.bgdi.ch/preview/bug-pb-634-feature-selection/index.html?ch.babs.kulturgueter=9767,9227,9228)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-634-feature-selection/index.html)
> PB-634: Fix feature selection of layer "Moorlandschaften AuLaV"

- src/modules/map/components/toolbox/TimeSlider.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/store/modules/layers.store.js
- tests/cypress/tests-e2e/timeSlider.cy.js
In the timeslider when a layer did not have any matching timestamp from the preview
year, the layer was still displayed. Also the feature selection only work on
the previously configured timestamp (before entering the timeslider).
The first issue has been resolved by filtering visible layers that don't
match the preview year.
The second issue has been solved by directly setting the preview year in the
layer config and not only when unmounting.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-590-time-slider-no-data-quick/index.html)
> PB-590: Quick fix for timeslider preview year for layer without current year entry

- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/modules/menu/components/common/MenuItemCheckBox.vue
- src/modules/menu/scss/menu-items.scss
The content of the button did not always fit (e.g. for "actual"). To solve this
we use the TextTruncate everywhere in the menu entry which handle text truncate
with tippy.
Also make sure that the time selector button are always the same size
This solve the issue below 
[Test link with time enabled layers](https://sys-map.dev.bgdi.ch/preview/bug-year-selector-css/index.html#/map?lang=de&center=2643898.46,1193053.29&z=2&bgLayer=ch.swisstopo.pixelkarte-grau&topic=ech&layers=ch.swisstopo.lubis-luftbilder-dritte-kantone@year=9999;ch.swisstopo.swissimage-product_1946;ch.swisstopo.swissimage-product.metadata@year=2022;ch.swisstopo.swissimage-product_3d@year=9999,f;ch.swisstopo.pixelkarte-farbe-pk25.noscale@year=9999;ch.swisstopo.lubis-luftbilder-dritte-firmen@year=9999;ch.astra.unfaelle-personens …
> Fix time selector button CSS

- src/api/features/features.api.js
- src/router/storeSync/LayerParamConfig.class.js
- src/store/modules/features.store.js
- tests/cypress/fixtures/features/features.fixture.json
- tests/cypress/tests-e2e/featureSelection.cy.js
identify request already provides us with all what we need (feature data), the only thing missing is the HTML popup.
This means getFeature request is now only called when the app is loaded with pre-selected features.
This reduces the number of calls to our backend for an identify on the map (should be a bit faster)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat_pb-669_less_get_feature_requests/index.html)
> PB-669 : separate html popup request from getFeature

- src/api/features/features.api.js
- src/api/layers/LayerTimeConfig.class.js
- src/api/layers/LayerTimeConfigEntry.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/api/layers/layers.api.js
- src/modules/map/components/cesium/CesiumInternalLayer.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
- src/modules/map/components/toolbox/TimeSlider.vue
- src/modules/map/components/toolbox/TimeSliderButton.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/__tests__/layersParamParser.spec.js
- src/router/storeSync/layersParamParser.js
- src/store/modules/layers.store.js
- src/utils/kmlUtils.js
- src/utils/layerUtils.js
- src/utils/legacyLayerParamUtils.js
- tests/cypress/tests-e2e/featureSelection.cy.js
- tests/cypress/tests-e2e/timeSlider.cy.js
Try to make the code cleaner, more robust and easier to understand (not sure
I achieved this though).
One major changes is that for the `"all"` hack, now in the url we don't use anymore
`@year=9999` but `@year=all` (legacy timestamp with `9999` are still working and are
translated to `@year=all`)
Also added support for `@year=none` when a layer as no data for timeslider
preview year.
I also tried to document the layer attributes and all special cases
I aslo created a ticket PB-680 to do more clean up concerning the `"all"` hack
in future.
[Test link with all different time enable layers using legacy link - map.geo.admin.ch](https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.lubis-luftbilder-dritte-kantone,ch.swisstopo.swissimage-product_194 …
> PB-675: Clean up TimeSlider code

- src/App.vue
- src/modules/map/components/toolbox/GeolocButton.vue
- src/store/modules/ui.store.js
- src/store/plugins/geolocation-management.plugin.js
- src/utils/components/ErrorWindow.vue
- tests/cypress/tests-e2e/geolocation.cy.js
Now the geolocation error is not anymore in a window.alert() but in an error
overlay on the top right corner that can be close.
Now it looks like this 
[Test link](https://sys-map.int.bgdi.ch/preview/bug-geoloc/index.html)
> Improve geolocation error management by removing the alert() - #patch

- src/utils/__tests__/utils.spec.js
- src/utils/utils.js
If you access the viewer using /index.html, then in the share embed the URL
for the iframe didn't used #/embed but still #/map view
This was because we return if the path was not the root `/`
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-703-iframe-embed/index.html)
> PB-703: Fix /index.html share embed - #patch

- src/store/plugins/click-on-map-management.plugin.js
The old viewer had always shown tooltip when showing the app in embed mode. With our app we changed that a bit, and that breaks a lot of our customer's integrations (through iframe).
Revert that so that the first feature selection in an iFrame shows a tooltip, only the pre-selection of feature should be impacted by the featureInfo URL param (or showTooltip in legacy)
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-707-tooltip-iframe/index.html)
> PB-707 : show tooltip on iframe - #patch

- src/store/modules/layers.store.js
was forgotten when switching to this new approach that time config needs to be synced too (only the time config of the "parent" aka 2d config was changed through the UI)
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-709-3d-config-timestamp/index.html)
> PB-709 : also change 3D specific config timestamp - #patch

- src/modules/map/components/openlayers/utils/styleFromLiterals.js
[Test link](https://sys-map.int.bgdi.ch/preview/fix-713-missing-treasure-hunt-icons/index.html)
> PB-713: revert to use the same logic as in the old geoadmin. - #patch

- src/config.js
some layers, such as ch.swisstopo.pixelkarte-farbe-pk25.noscale, uses the current year as a valid timestamp. Removing the "minus one" to the youngest year of the time slider to be able to show it.
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-717-current-year-in-timeslider/index.html)
> PB-717 : add current year to time slider years - #patch

- src/utils/coordinates/__test__/coordinateExtractors.spec.js
- src/utils/coordinates/coordinateExtractors.js
- tests/cypress/tests-e2e/search/coordinates-search.cy.js
without world-wide coverage, it doesn't really make sense for our users that we do not do the same guessing as the old viewer was doing. So adding it back.
This will need to be discussed/re-thinked when we will be adding world-wide coverage, as an inverted WGS84 is still valid in this context (pointing to something outside CH...)
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-716-inverted-wgs84-in-searchbar/index.html)
> PB-716 : guess WGS84 coordinate order in the searchbar - #patch

- src/modules/i18n/index.js
We always used the first supported language of the application that the browser
also supported instead of choosing the prefer browser langage that app supports
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-720-dft-lang/index.html)
> PB-720: Fix default language detection - #patch

- src/api/topics.api.js
so that 3D config don't get shown in the catalogue (they have the same technical name as the one that should be shown)
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-734-topic-layers-config-mismatch/index.html)
> PB-734 : search all layers with ID before fallback to technical name - #patch

- src/modules/menu/components/print/MenuPrintSection.vue
- src/utils/components/ProgressBar.vue
- tests/cypress/tests-e2e/3d/navigation.cy.js
The progress bar is degressive and it's completion time is set based on the
number of layer to print
[Test link](https://sys-map.int.bgdi.ch/preview/feat-print-progress/index.html)
> PB-726: Added a print progress bar instead of a spinner - #patch

- src/api/layers/AbstractLayer.class.js
- src/api/layers/ExternalLayer.class.js
- src/api/layers/ExternalWMSLayer.class.js
- src/api/layers/GeoAdminLayer.class.js
- src/api/layers/GeoAdminWMSLayer.class.js
- src/api/layers/WMSCapabilitiesParser.class.js
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/layersParamParser.js
- src/store/plugins/external-layers.plugin.js
- src/utils/legacyLayerParamUtils.js
- tests/cypress/tests-e2e/layers.cy.js
One Geoadmin layer had support for a special extra URL query parameter `item=...`
that was passed from URL to the WMS server, see legacy URL example below
https://map.geo.admin.ch/index.html?layers=WMS||s2-sr_v100_2024-05-10t102021||https://wms.geo.admin.ch/?item=2024-05-10t102021||ch.swisstopo.swisseo_s2-sr_v100||1.3.0
To solve this issue that user were used to (even though here we should have
used the well known TIME parameter) I added support for extra WMS param in
our URL syntax using the custom attributes @key=VALUE. So now all custom
attributes @key=VALUE that are not part of the following well defined attributes
- year
- updateDelay
- features
- adminId
Are passed along to the WMS server (for internal GeoAdmin layer and external layers)
[Test Legacy …
> PB-741: Added support for external WMS extra url parameters - #patch

- src/utils/coordinates/__test__/coordinateExtractors.spec.js
- src/utils/coordinates/coordinateExtractors.js
- tests/cypress/tests-e2e/search/coordinates-search.cy.js
now supports most input (inverted or not) with cardinal letters, such as :
- 47° 43.813' N 8° 37.738' E
- N 46° 59.000 E 006° 44.000
- E7.297165 N46.791657 
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-718-wgs84-search-bar/index.html)
> PB-718 : adding cardinal letter support for most WGS84 search input - #patch

- src/scss/variables.module.scss
It was on top of the menu and header which don't make sense in my opinion
and was quite annoying.
It is still on top of the map toolbox but under the background selector.
On the old viewer it was under all elements (menu, header, toolbox, footer,
background selector)
[Test link](https://sys-map.int.bgdi.ch/preview/bug-location-popup-zindex/index.html)
> Put location popup below the menu and header - #patch

- src/modules/menu/MenuModule.vue
- src/modules/menu/components/header/HeaderWithSearch.vue
- src/modules/menu/components/search/SearchBar.vue
- src/modules/menu/components/search/SearchResultList.vue
- tests/cypress/tests-e2e/search/search-results.cy.js
Do not use anymore the on focus event to toggle the results of the search bar.
This was an issue if we wanted to focus the search bar on app startup and that
the swisssearch query param was set, then it would have open the app with the
result open, which was not very nice.
Now I added a dropdown button when the search has result which makes clearer
to the user that there is result even if the results are hidden. The results
are toggle by click event and not anymore by focus event.
Also the ESC button was toggling the results which was not very intuitive and
on the old viewer the ESC button was used to cleared the input, so I reverted
to the old viewer behavior.
Also make sure when the input is cleared that the result is hidden.
[Test …
> PB-751: Focus on search bar when starting the application - #patch

- src/store/plugins/app-readiness.plugin.js
It happened that the URL query watcher could not be called because the app
is not yet ready in the router sync and should therefore be postpone in the
store mutation when app is ready, but in this case the map was ready before
the app was ready and the readiness plugin de-register itself and we never
set the app is ready flag never triggering the initial query watcher.
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-747-app-not-ready/index.html)
> PB-747: Fix race condition in startup - #patch

- src/views/MapView.vue
Some user were complaining that those buttons used to be present but not anymore
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-780-drawing-toolbox/index.html)
> PB-780: Re-added geoloc and timeslider buttons in drawing - #patch

- src/api/file-proxy.api.js
- src/store/plugins/load-gpx-data.plugin.js
- src/utils/legacyLayerParamUtils.js
- tests/cypress/tests-e2e/importToolFile.cy.js
And use service-proxy to get GPX file data
[Test link with legacy GPX](https://sys-map.int.bgdi.ch/preview/fix-pb-783-legacy-gpx/index.html?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.astra.wanderland-sperrungen_umleitungen,GPX%7C%7Chttps:%2F%2Fdrive.google.com%2Fuc%3Fexport%3Ddownload%26id%3D1CB3V6M42ysJttjulzQPygtnAVRzguQhK&layers_opacity=1,1,1,0.8,0.8,1&layers_visibility=false,false,false,false,false,true&layers_timestamp=18641231,,,,,&E=2678974.87&N=1197370.66&zoom=6.3999999999999995)
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-783-legacy-gpx/index.html)
> PB-783 : adding legacy GPX parsing - #patch

- src/api/features/features.api.js
- src/modules/infobox/components/FeatureDetail.vue
- src/modules/infobox/components/FeatureListCategoryItem.vue
- src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
- src/modules/map/components/openlayers/OpenLayersPopover.vue
- src/router/storeSync/LayerParamConfig.class.js
- src/store/modules/features.store.js
We were missing a `coord` param for the HTML popup endpoint (undocumented) so that the HTML endpoint can select features for us instead of giving feature IDs (not optimal, but that's the way it is for now)
Also not requesting geometries (in identify requests) when the layer isn't highligtable, it was returning the extent of the whole layer as geom. Using instead the click coordinate as a geometry (adapting the code to be able to handle no geom)
[Test link with recent earthquakes](https://sys-map.int.bgdi.ch/preview/fix-pb-729-recent-earthquake-tooltip/index.html?layers=ch.bafu.gefahren-aktuelle_erdbeben)
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-729-recent-earthquake-tooltip/index.html)
> PB-729 : fix recent earthquake tooltip - #patch

- src/modules/menu/components/advancedTools/ImportFile/utils.js
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-714-kml-file-with-comments/index.html)
> PB-714: Update regex to allow comments in kml before kml tag - #patch

- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/modules/infobox/components/styling/DrawingStylePopoverButton.vue
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/modules/map/components/MapPopover.vue
- src/utils/components/SimpleWindow.vue
- tests/cypress/tests-e2e/drawing.cy.js
This popover when the style edit was on the tooltip overflow under the header
and when opening the icons selectors then most of the popup was out of the
screen.
Also improved the look and feel of the icons selectors.
Also did some other look and feel improvements
- minimize/maximize popup windows used down/up caret instead of right/down. This sounds more intuitive to me and also follow the same pattern
as the dropdown inputs. The menu items stays with the right/down caret
- Put the description of the drawing style edit on the same lines as the buttons and increased the default size of the text area to make it clearer to the user that it can enter more than one line.
[Test link](https://sys-map.int.bgdi.ch/preview/bug-look-and-feel/index.html)
> Put drawing style edit popover in a more optimal position - #patch

- src/modules/menu/components/search/SearchBar.vue
Some browser extension like 1Password could interpret the search bar as an
normal input field and provided an auto fill. For user with 1Password this was
very annoying as you certainly never wants to have a search input field automatically
filled with user credentials or user personal infos.
To avoid this use the standard search input type and also added some standard
attribute to improve user experience.
[Test link](https://sys-map.int.bgdi.ch/preview/bug-search-bar-role/index.html)
> Avoid wrong interpretation of search bar by browser extension (e.g. 1Password) - #patch

- src/store/plugins/geolocation-management.plugin.js
While using the geolocation you have time to times the `Unknown error` window
that appears. This is due to the fact that the geolocation can return an error,
but  while using the app on the field I noticed that it happens sometimes just
once and then everything seems to work fine. In this case the error windows is
quite annoying as you have to close it and if it happened during the initial
get current position you had to disable and re-enable the geolocation.
So now I improved the error management and do some automatic retries until 3 times
if we are the get current position phase, while in the watcher phase the error
is ignored unless it happens more that 3 times in a row.
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-786-geolocation/index.html)
> PB-786: Fix geolocation error management - #patch

- src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
Issue : At the highest zoom level, the mapviewer would not load the highest possible resolution, but the one right before it.
Cause : When we introduced the max resolution to handle client side zoom, we made a slight error in the slicing, and it caused the possible resolutions client side to be smaller (by 1).
Fix : We slice at the correct place.
Bonus Fix : when trying to print at the 1:500 and 1:1000 scales, since the matrixes were sent as parameter by the viewer, we now request the correct tiles. I will deploy the print with the updated capabilities to int once both PR are merged and when we are confident this works, we can deploy the new print to prod.
[Test link](https://sys-map.int.bgdi.ch/preview/bugfix-pb-395_print-1_500/index.html)
> PB-395: enhancing highest zoom level - #patch

- src/store/modules/layers.store.js
On the old viewer if you would manually import multiple geoadmin drawing (drawing
from our prod backend), going in the drawing menu would copy the drawing
on top of the layer list.
On the old viewer however it would take the top drawing layer even if it is
not visible. However this don't make sense and is disturbing because in this
case if the drawing is invisilbe when opening the drawing mode it is still invisible
until you add the first feature and then the copied feature would sundely appear
making very unintuitive. Therefore now we only looks for visible drawings.
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-802-multiple-drawing/index.html)
> PB-802: Edit the geoadmin drawing on top - #patch

- src/router/legacyPermalinkManagement.routerPlugin.js
- src/router/storeSync/__tests__/abstractParamConfig.class.spec.js
- src/router/storeSync/abstractParamConfig.class.js
- src/store/modules/geolocation.store.js
- src/store/plugins/geolocation-management.plugin.js
If the geolocation was activated at startup using the goelocation query parameter
the application would not re-center to the position. This would break some legacy
links that use this parameter like the swisstopo "you are here" T-shirt.
This was also an issue when entering the parameter in the new query format.
We had several issue here, first the legacy parameter was totally ignored because
URLSearchParams parsed the geolocation to an empty string which was not supported
by our boolean query param.
Another issue was that per default tracking was off unless you explicitely click
on the geolocation button.
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-811-geolocalisation/index.html)
> PB-811: Fix go to position if geolocation is active at startup - #patch

- src/api/iframeFeatureEvent.api.js
- src/modules/menu/components/share/MenuShareEmbed.vue
- src/modules/menu/components/share/MenuShareSection.vue
- src/store/modules/share.store.js
- src/views/EmbedView.vue
- tests/cypress/tests-e2e/shareShortLink.cy.js
Adds new change event triggered to iframe parent. It will be triggered when route query changes, as it is not possible with VueJS to get the current SRC attribute of an iframe (it always returns the value that was set with :src, without updating it...)
This way we can receive the new state of the iframe and update the code snippet accordingly.
Removing shortlink generation for embed code snippet (like old viewer), so that param can then be updated by the user copying it (and less calls to our shortlink backend)
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-704-iframe-preview-update/index.html)
> PB-704 : iframe preview update - #patch

- src/modules/map/components/footer/MapFooter.vue
Make the middle map footer containing the infobox no longer disappear to fix following issues in fullscreen:
- When opening fullscreen while feature info is set to bottom, selecting a feature would not show an infobox
- When pressing the arrow down button on the infobox popover, the infobox would disappear
- Profiles could not be displayed, as they are embedded in the middle footer
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-791-altimeter-profile-fullscreen/index.html)
> PB-791: Do not hide middle footer when in fullscreen - #patch

- src/modules/infobox/components/FeatureAreaInfo.vue
- tests/cypress/tests-e2e/drawing.cy.js
Fixed bug which showed an area of  0 m2 if the area was just above 1000 m2
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-792-measuring-area-rounding-issue/index.html)
> PB-792: Change rounding and decimal places threshold - #patch

- src/utils/logging.js
Reverts geoadmin/web-mapviewer#984
[Test link](https://sys-map.int.bgdi.ch/preview/revert-984-bug-pb-747-logs-2/index.html)
> Revert "PB-747: Enabled logs on PROD to try to understand the blank screen issue" - #patch

- src/utils/ol/format/KML.js
[Test link](https://sys-map.int.bgdi.ch/preview/fix-pb-761-default-text-size-if-text-size-equal-zero/index.html)
> PB-761: Don't override text scale if it is zero - #patch

- secrets.yml
- src/App.vue
- src/modules/i18n/README.md
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/store/modules/ui.store.js
- src/utils/WarningMessage.class.js
- src/utils/components/ErrorWindow.vue
- src/utils/components/SimpleWindow.vue
- src/utils/components/WarningWindow.vue
- src/utils/kmlUtils.js
Because openlayer only provide a synchrone hook function to modify the icon
url we do the proxyfy regardless if the remote server support or not CORS. However
we do run the check asynchronously and if it failed we add a warning window
on top of the screen.
This PR solve issues; PB-803, PB-631 (icon scale is too small has to be increase to see icons), PB-816
[Test link with CORS issue](https://sys-map.int.bgdi.ch/preview/bug-pb--631-cors-kml-icons/index.html#/map?lang=en&center=2604108.64,1189241.41&z=6.839&bgLayer=ch.swisstopo.pixelkarte-grau&topic=ech&layers=KML%7Chttps://www.uvek-gis.admin.ch/BAZL/Karte_AeMC_AME/Aeromedical+Examiner+(AME).kml;KML%7Chttps://www.uvek-gis.admin.ch/BAZL/Karte_AeMC_AME/Aeromedical+Center+(AeMC).kml&featureInfo=bottomPanel)
[Test …
> PB-803, PB-631, PB-175: Use proxy for all non geoadmin KML icon urls - #patch

- src/config.js
- src/utils/gpxUtils.js
so that we diminish, or totally avoid, the coastal paradox we've encounter so far with GPX that contains points close together, following a steep mountain (with the GPS error, that would mean it would jump back and forth on the hill, creating fake height distance, and thus giving a very VERY poor hiking time estimation)
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-800-profile-discrepancy/index.html)
> PB-800 : simplify GPXs geometry - #patch

- src/api/print.api.js
This is a dirty fix while waiting this bug fix is merged https://github.com/geoblocks/mapfishprint/pull/35. The https://github.com/geoadmin/web-mapviewer/pull/1011 contains the proper fix.
The bug:
- customizer.feature skips an empty text annotation feature
To reproduce:
- create an empty text and another drawing item
- print
[Test link](https://sys-map.int.bgdi.ch/preview/pb-790-fix-print-editablefeature-error-empty-annotation/index.html)
> PB-790: Fix failed to print on empty string text drawing. - #minor

- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
- src/store/modules/features.store.js
- src/utils/identifyOnVectorLayer.js
When displaying a GPX track, its title in the profile was undefined. This was
due to the fact that GPX on a ol feature seems to have no ID, but have a name.
Also fixed a crash on 3d view when clicking on the map (preventing any feature identify).
[Test link](https://sys-map.int.bgdi.ch/preview/bug-gpx-profile/index.html)
> PB-866: Fix undefined profile name for GPX track and fix crash in left click on 3D - #patch

- src/utils/ol/format/KML.js
[Test link](https://sys-map.int.bgdi.ch/preview/fix-806-text-label-alignment/index.html)
> PB-806: Use center as the default alignment for text without icon. - #patch

- package-lock.json
- package.json
- src/api/print.api.js
~UPDATE:
**DO NOT MERGE** this PR before a new version of mapfishprint is released that includes the fix.~
This is a better way to fix the issue.
This fix should be updated after https://github.com/geoblocks/mapfishprint/pull/37 is merged and new version is released.
[Test link](https://sys-map.int.bgdi.ch/preview/fix-790-update-mapfishprint-with-replacer/index.html)
> Fix 790 update mapfishprint with replacer - #patch

- src/modules/map/MapModule.vue
- src/modules/map/components/LocationPopup.vue
- src/store/modules/map.store.js
- src/store/plugins/click-on-map-management.plugin.js
Introduce a new store key handle the location popup independently. Previously it uses clickInfo which can be modified and hide locationPopup unintentionally.
[Test link](https://sys-map.int.bgdi.ch/preview/pb-859-info-box-positionpbox-together/index.html)
> Pb 859 info box positionpbox together - #patch

- src/modules/drawing/lib/export-utils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-492-add-description-to-exported-gpx/index.html)
Sample exported GPX file (see the new `desc` tag):
```xml
<gpx xmlns="http://www.topografix.com/GPX/1/1"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" version="1.1" creator="OpenLayers">
<wpt lat="46.854351415606935" lon="7.353402894159358">
<name>With desc</name>
<desc>bla bla</desc>
<type>marker</type>
</wpt>
<rte>
<name></name>
<desc>WIth desc</desc>
<type>linepolygon</type>
<rtept lat="47.29016724654342" lon="7.769117763897004"/>
<rtept lat="46.701234266331284" lon="7.667454407858695"/>
</rte>
<rte>
<type>linepolygon</type>
<rtept lat="47.32555323948249" lon="7.934693728031257"/> …
```
> PB-492: Add description to exported GPX file.

- src/api/print.api.js
- tests/cypress/tests-e2e/print.cy.js
OpenLayers rendering:
Print with conflictResolution = False, and adjusted font size (e.g. previously 16px now 12px)
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-870-missing-kml/index.html)
> PB-807: Do not use conflict resolution in text printing and adjust font size.

- src/modules/i18n/locales/rm.json
- src/modules/map/components/footer/MapFooterAppCopyright.vue
There's no RM version of the page, so we fall back to DE for that link
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-898-fix-rumantsch-footer-link/index.html)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-898-fix-rumantsch-footer-link/index.html)
> PB 898 Fix rumantsch footer link to geo.admin.ch - #patch

- src/utils/coordinates/WebMercatorCoordinateSystem.class.js
we were using values from epsg.io website, but our backends use different values. I found out a project in our geoadmin organization that contained all the required values, so I copied them from there.
This should fix the delta (on the Y axis) that we were experiencing when showing WMS/WMTS data with OpenLayers while showing vector tiles under
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-131-mercator-tile-displacement/index.html)
> PB-131 : fix WebMercator extent/bounds

- src/modules/map/components/cesium/CesiumKMLLayer.vue
KML are well able to set that themselves if they require it, and some use cases need this to be false (flight tracks)
fixes #1016
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-865-no-clamptoground-for-3d-kml/index.html)
> PB-865 : remove forced clampToGround for KML polyline in 3D

- src/config/baseUrl.config.js
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/menu/components/debug/BaseUrlOverrideModal.vue
- src/router/storeSync/BaseUrlOverrideParamConfig.class.js
it was dispatching any time any URL param changed, leading to the part of the code reloading the topic/layers config being called way too often
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-871-too-many-refresh/index.html)
> PB-871 : only dispatch if something has changed

- src/api/lv03Reframe.api.js
- src/modules/map/components/LocationPopupPosition.vue
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/store/modules/position.store.js
- src/store/modules/search.store.js
- src/utils/__tests__/extentUtils.spec.js
- src/utils/coordinates/__test__/coordinateExtractors.spec.js
- src/utils/coordinates/__test__/coordinateUtils.spec.js
- src/utils/coordinates/coordinateExtractors.js
- src/utils/coordinates/coordinateUtils.js
- src/utils/militaryGridProjection.js
- tests/cypress/tests-e2e/search/coordinates-search.cy.js
instead of reprojecting through proj4, which led to poor precision
[Test link with legacy E and N param](https://sys-map.dev.bgdi.ch/preview/fix-pb-843-lv03-reframe/index.html?E=559224&N=101520&crosshair=marker&z=13)
[Same link on PROD](https://map.geo.admin.ch/?E=559224&N=101520&crosshair=marker&z=13)
The difference is about a meter, no more. But for some users, that was a big deal
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-843-lv03-reframe/index.html)
> PB-843 : use LV03 to LV95 reframe services

- src/api/file-proxy.api.js
- src/api/files.api.js
- src/config/baseUrl.config.js
- src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
- src/store/plugins/load-gpx-data.plugin.js
- src/utils/kmlUtils.js
- src/utils/utils.js
- tests/cypress/tests-e2e/importToolFile.cy.js
GPX file used always the service-proxy even if the server supported CORS. Also
on the service-proxy we could see that some requests were made over service-proxy
for internal server like public.geo.admin.ch. This was due to the fact that if
for any reason the initial request failed (network failure) we fallback to the
service proxy. Now in that case we don't fallback anymore.
NOTE unfortunately there is no way for a web application to check for CORS support
see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors
[Test link](https://sys-map.int.bgdi.ch/preview/bug-pb-977-proxy/index.html)
> PB-977: Don't use service-proxy for internal domain and for GPX that support CORS - #patch

- src/api/__tests__/print.api.spec.js
- src/api/print.api.js
- src/config/print.config.js
- src/utils/styleUtils.js
- tests/cypress/tests-e2e/print.cy.js
Issue : When we were sending print requests, the scales of the symbols and texts in kmls were off. For icons, they were too small, and the texts were too big.
Fix : We corrected the scales for icons and labels. Icons used a DPI adaptation of * 90 / 254 which was inherited from the old mapviewer. After some empirical testing, it looks like on the new mapviewer needs a *150 / 254 DPI adaptation Labels were not using the 'scale' parameter for the fonts at all, and they now also use a 150 / 254 DPI adaptation.
It is important to note that the '254' given here is a computed value, as some layers will have smaller resolutions and their DPI will be used in those situations
While testing, try to test with different screens, to ensure the result is consistent at all times.
[Test …
> PB-818: Ensuring scales are respected on print - #minor

- src/App.vue
- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
- src/router/storeSync/CrossHairParamConfig.class.js
- src/store/modules/ui.store.js
- src/store/plugins/geolocation-management.plugin.js
- Issue : currently, there is only one error message existing at the same time, which means if a new error happens, it'll flush out the previous one, with no possibility of seeing it again.
- Fix : We implement a queue, like for warnings, which means if multiple errors happen at the same time, we can check all of them.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-984-implement-error-queue/index.html)
> PB-984: implement an error queue

- src/config/baseUrl.config.js
Some admin.ch hosts like uvek-gis.admin.ch don't support yet CORS, therefore
they still need to go through proxy.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1006-kml-admin.ch/index.html)
> PB-1006: Fixed CORS issue with admin.ch hosts

- src/utils/geodesicManager.js
All geometries were interpreted as polygons, meaning a line was counted back and forth (doubling the length...)
Could not reliably add a Cypress test to grab the tooltip on the map (the one in red) as it is drawn directly in the canvas (no HTML element to grab with a CSS selector...)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-859-doubling-length/index.html)
> PB-1007: fix doubling of length value

- package-lock.json
- package.json
- src/modules/infobox/components/ShowGeometryProfileButton.vue
- src/store/modules/features.store.js
- src/utils/gpxUtils.js
but still simplify the track before sending it to the profile backend.
This should reduce the coastal paradox we had before when sending raw GPX track, while keeping user "happy" as they will se their raw track on the map
Using TurfJS to do the simplification, as it is also using a Ramer-Douglas-Peucker algorithm (same as OpenLayers) and it would be more difficult / add more complexity to the code to reparse all features as OL features there.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-896-gpx-simplify-only-profile/index.html)
> PB-896 : show un-simplified GPX track

- src/api/file-proxy.api.js
- src/api/print.api.js
Issue : Service print can't use service-proxy like the mapviewer, so when external graphics are proxied in the mapviewer to go around CORS issues, those same graphics can't be rendered in print jobs
Fix : we un-proxy the 'externalGraphics' attribute of styles in the print spec, so the original URL is sent to service print.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-1017-unproxify-print-jobs/index.html)
> PB-1017: un-proxy external graphics in print specs

- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
Issue : on some phones, a long press event would also fire a single press event afterwards, causing the application to open both a location popup and an infobox.
Cause : setting the longClickTriggered boolean was not registered while in the longClickTimeout function, most likely due to a scoping issue.
Fix : we set the longClickTriggered boolean in the 'onMapRightClick' event instead. We also added a small parameter in the function to tell if we need to set up the flag or not, as desktop users won't need this.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-960-handle-longpress-event-conflict/index.html)
> PB-960: handle long press events error on some mobiles

- src/api/features/features.api.js
Originally, the ticket is about parsing plain text response from GetFeatureInfo request. Unfortunately, there is no standard on how to do it. For example these two requests have completely different format if we request as plain/text:
- [Semicolon separated](https://public.geo.lu.ch/ogd/services/managed/GRZGEMLU_DS_V1_MP/MapServer/WMSServer?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&LAYERS=0&CRS=EPSG:2056&BBOX=2619150,1195166,2668924,1245527&WIDTH=100&HEIGHT=100&QUERY_LAYERS=0&INFO_FORMAT=text%2Fplain&FEATURE_COUNT=10&LANG=en&TOLERANCE=10&BUFFER=10&FI_POINT_TOLERANCE=10&FI_LINE_TOLERANCE=10&FI_POLYGON_TOLERANCE=10&I=50&J=50)
```
@Gemeinden Kanton Luzern OBJECTID;BFS-Gemeindenummer;Shape; 2;1121;Polygon; 9;1128;Polygon; 18;1151;Polygon; 74;1086;Polygon; 
```
- [Dash section …
> PB-364: Add parser for OGC WMS XML response for GetFeatureInfo.

- src/modules/map/components/common/z-index.composable.js
- src/modules/map/components/footer/MapFooterAttributionList.vue
- src/modules/map/components/footer/backgroundSelector/BackgroundSelector.vue
- src/modules/map/components/footer/backgroundSelector/BackgroundSelectorSquared.vue
- src/modules/map/components/footer/backgroundSelector/BackgroundSelectorWheelRounded.vue
- src/modules/map/components/openlayers/OpenLayersBackgroundLayer.vue
- src/modules/map/components/openlayers/debug/OpenLayersLayerExtents.vue
- src/modules/map/components/openlayers/utils/usePrint.composable.js
- src/router/storeSync/storeSync.config.js
- src/store/modules/__tests__/layers.store.spec.js
- src/store/modules/cesium.store.js
- src/store/modules/layers.store.js
- src/store/plugins/topic-change-management.plugin.js
- src/utils/legacyLayerParamUtils.js
- tests/cypress/tests-e2e/footer.cy.js
- tests/cypress/tests-e2e/layers.cy.js
- tests/cypress/tests-e2e/topics.cy.js
(the reason I am doing this was because I fixed something small when nobody else was around, this is like the extension of that)
Some notes on the fix: the backgroundLayer was copied inside the store. When one changes the language, the attributions would therefore not be updated. One solution would be to listen to language changes and trigger the update (see first commit), but IMO this would diffuse the responsibility of the data further. So I changed the store a bit so the currentLayer comes through a getter, streamlining the data flow.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-912-swisstopo-source/index.html)
> PB-912 Fix language of background layer attribution

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/utils/kmlUtils.js
Issue : Supporting http resources with the mapviewer is being rolled out by late January at the latest. We need to inform people still using them to make the change
Fix : We add a feedback warning specifically saying that there are resources in http, and that the user should change that.
still a draft for now : I need to add the links and ensure translation is correct
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-827-add-warning-http/index.html)
> PB-827: Add warning when using http resources

- src/api/errorQueues.api.js
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
- src/router/storeSync/CameraParamConfig.class.js
- src/router/storeSync/CompareSliderParamConfig.class.js
- src/router/storeSync/CrossHairParamConfig.class.js
- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/PositionParamConfig.class.js
- src/router/storeSync/SearchParamConfig.class.js
- src/router/storeSync/SimpleUrlParamConfig.class.js
- src/router/storeSync/TimeSliderParamConfig.class.js
- src/router/storeSync/ZoomParamConfig.class.js
- src/router/storeSync/abstractParamConfig.class.js
- src/router/storeSync/layersParamParser.js
- src/router/storeSync/storeSync.config.js
- src/router/storeSync/storeSync.routerPlugin.js
- src/store/modules/ui.store.js
- src/store/plugins/geolocation-management.plugin.js
- src/utils/coordinates/coordinateSystems.js
Issue : when modifying the URL directly, users received no feedback about what they did wrong when making mistakes, especially on a productive environment where most logs are deactivated.
Fix : we now give a feedback for every parameter that is wrongfully filled. We also added some extra cases for the layers, where we want to give a feedback on each individual layer, and for the time slider when everything is in order, but there are no layers supporting it.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-984-error-feedback-for-all-url-parameters/index.html)
> PB-984: add error feedback for all URL parameters

- src/api/errorQueues.api.js
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
- src/router/storeSync/abstractParamConfig.class.js
- src/store/modules/ui.store.js
- src/store/plugins/geolocation-management.plugin.js
It was confusing to be able to send a single error/warning while having to use the name in plural when dispatching. Only accepting array of both now (and fixing some places where it was wrongly dispatched before)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-984-couple-fixes-with-warnings/index.html)
> PB-984 : only accept array of warnings/errors when dispatching

- src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
Issue : pressing the left mouse button for a long period of time would cause the location popup to appear
Cause : in openlayers, the singleClick event represents both mouse left clicks and mobiles touchdown events
Fix : We check the pointer type of the original event, ensuring we only handle the cases where this was triggered on a mobile.
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-1003-stop-long-left-click-interaction/index.html)
> PB-1003: no more long mouse left clicks

- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/abstractParamConfig.class.js
Issue: when reloading the page, local layers trigger the error feedback, telling them they made a mistake, when technically they did not do anything wrong.
Fix : we assume local layers errors are due to actualisations / links sharing, and that we should warn the users they're trying to get a local file through the URL, which doesn't work, and gives them a feedback about it in the form of a warning.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-984-removing-external-layer-check/index.html)
> PB-984: quick fix for local layers

- .eslintrc.cjs
- src/modules/drawing/lib/modifyInteraction.js
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/modules/map/components/CompareSlider.vue
- src/modules/map/components/LocationPopup.vue
- src/modules/map/components/toolbox/TimeSliderDropdownSearchList.vue
- src/router/legacyPermalinkManagement.routerPlugin.js
- src/store/modules/layers.store.js
- src/store/modules/ui.store.js
- src/utils/click-outside.js
- src/utils/geoJsonUtils.js
- src/utils/geodesicManager.js
- src/utils/url-router.js
- src/utils/utils.js
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/layers.cy.js
Enable the eslint rule [eqeqeq](https://eslint.org/docs/v8.x/rules/eqeqeq) which enforces the use of triple equals (`===` and `!=`).
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-eqeqeq-rule-in-eslint/index.html)
> Enforced triple eq in condition statements

- src/modules/drawing/DrawingModule.vue
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/utils/kmlUtils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1046-babs-icon/index.html)
> PB-1046: Fallback to default icon set if not found

- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/footer/MapFooterAttributionList.vue
- src/modules/menu/components/LayerCatalogueItem.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/store/modules/layers.store.js
- src/store/modules/search.store.js
- src/store/plugins/external-layers.plugin.js
- src/store/plugins/load-gpx-data.plugin.js
- src/store/plugins/load-kml-data.plugin.js
I also ended up refactoring on how we retrieve a layer. LayerID is not enough since it's possible to have two layers with same layerID but different baseURL.
I am thinking also about same layerID, same baseURL, but different type of layer (e.t. WMTS vs WMS). But perhaps it's even more corner case, that can be addressed later.
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1041-conflict-layer-name/index.html)
> PB-1041: Fix Conflict Layer Name/ID 

- src/router/storeSync/PositionParamConfig.class.js
- src/router/storeSync/storeSync.config.js
- Issue : Swisssearch coordinates in the query were not centering the map on the coordinates.
- Cause : We sometimes end up going twice through the storesync, which meant that, since the store was setting the center default param, and it differed from the query, the center param was overwritten by the default value.
- Fix : To counter this, we set the center through the search before the center parameter itself, preventing him to try to set its default value. We also stop the center from populating the store when there is a swisssearch parameter and no crosshair
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-768-swisssearch-center-in-legacy/index.html)
> PB-768: swisssearch now centers when it's given coordinates in the URL

- src/store/modules/ui.store.js
- src/utils/ErrorMessage.class.js
- src/utils/WarningMessage.class.js
Issue : sometimes, errors and warning might get added multiple times, and as they are new object instances, the set had issue ensuring unicity
Fix : we filter the errors and warnings received, ensuring we only add messages with a different message AND different parameters.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-984-ensure-unicity/index.html)
> PB-984: avoid duplicate errors

- src/modules/menu/components/LayerDescriptionPopup.vue
- src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
- src/modules/menu/components/help/ReportProblemButton.vue
- src/modules/menu/components/help/feedback/FeedbackButton.vue
- src/utils/components/ModalWithBackdrop.vue
- src/utils/components/SimpleWindow.vue
- src/utils/composables/useMovableElement.composable.js
- tests/cypress/tests-e2e/importToolMaps.cy.js
- tests/cypress/tests-e2e/search/search-results.cy.js
- tests/cypress/tests-e2e/topics.cy.js
Update screencast:
I'm not super expert in CSS, so any suggestions are welcome :)
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-985-floating-layer-info/index.html)
> PB-985: Make Layer Info Movable

- tests/cypress/tests-e2e/featureSelection.cy.js
the box selection was happening from the center of the view, and the KML feature that was tested is placed exactly at the center. That lead to tests failing sometimes on the CI.
So I've changed the box-making function to create a box around the center of the view instead.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-875-fix-flaky-test/index.html)
> PB-875 : fix potential flakiness of tests

- src/api/layers/KMLLayer.class.js
- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/useKmlDataManagement.composable.js
- src/store/modules/drawing.store.js
there was some bugs by keeping it only in the toolbox. For instance deleting the drawing and adding new features would not give a correct drawing name.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1116-drawing-name-fix/index.html)
> PB-1116 : move drawing name to store

- tests/cypress/tests-e2e/featureSelection.cy.js
Looks like the KML isn't yet available when the drag select happens, and the CI misses one feature because of that. I added a soft wait on the KML by checking that it is in the OL layer prior to do the dragbox selection
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-875-another-attempt/index.html)
> PB-875 : new attempt at reducing this test flakiness on CI

- src/modules/map/components/toolbox/MapToolbox.vue
- tests/cypress/tests-e2e/embed.cy.js
- tests/cypress/tests-e2e/footer.cy.js
- tests/cypress/tests-e2e/shareShortLink.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-598-hide-zoom-buttons/index.html)
> PB-598: Hide zoom buttons on mobile.

- src/api/layers/AbstractLayer.class.js
- src/store/modules/layers.store.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1120-layer-error-are-not-emptied/index.html)
> PB-1120: Remove error key when the extent is valid.

- src/api/file-proxy.api.js
- src/api/files.api.js
- src/modules/menu/components/advancedTools/ImportFile/parser/CloudOptimizedGeoTIFFParser.class.js
- src/modules/menu/components/advancedTools/ImportFile/parser/FileParser.class.js
- src/modules/menu/components/advancedTools/ImportFile/parser/GPXParser.class.js
- src/modules/menu/components/advancedTools/ImportFile/parser/KMLParser.class.js
- src/modules/menu/components/advancedTools/ImportFile/parser/KMZParser.class.js
- src/modules/menu/components/advancedTools/ImportFile/parser/index.js
- src/store/plugins/load-cog-extent.plugin.js
- src/store/plugins/load-gpx-data.plugin.js
- src/store/plugins/load-kml-kmz-data.plugin.js
- tests/cypress/tests-e2e/print.cy.js
While working on the latest PR for PB-1028 I made some rebase mistake and didn't detect them before merging.
COG files were loaded entirely once again... So here's the fix, with some additional benefits.
I tried to simplify the FileAPI functions, the ones that load files (either through a simple GET or through service-proxy) It wasn't possible, with the addition of COG to the mix, to keep FileParser to decide to load content on its own, so I created a function that get the MIME type (and other relevant info on the file) so that each time we need to load a file, we can decide which way (of loading) we want to go (proxy or not proxy)
I will add a new E2E test for COG in the next PR
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1028-adapt-cog-loading/index.html)
> PB-1028 : fix COG loading after rebase error

- src/modules/map/components/cesium/CesiumBackgroundLayer.vue
- src/modules/map/components/cesium/CesiumMap.vue
- src/modules/map/components/cesium/CesiumVectorLayer.vue
- src/modules/map/components/cesium/CesiumVisibleLayers.vue
- src/modules/map/components/cesium/utils/enhanceLabelStyle.js
- src/modules/map/components/cesium/utils/primitiveLayerUtils.js
- src/modules/map/components/cesium/utils/useAddPrimitiveLayer.composable.js
like with OL, keeping all the logic for each group isolated from the main component
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-955-group-visible-layers/index.html)
> PB-995: group all 3D background and visible layer into one component each

- package-lock.json
- package.json
- src/scss/main.scss
there's a problem with our label layer and version 1.120 and further (flickering black frame when zooming/panning, there's an issue on the Cesium tracker for that here : https://github.com/CesiumGS/cesium/issues/12231 )
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-995-fix-css-import/index.html)
> PB-995: revert Cesium to 1.119 and fix Cesium CSS import warning

- src/api/profile/ElevationProfile.class.js
- src/api/profile/profile.api.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/infobox/components/FeatureElevationProfilePlot.vue
- src/modules/infobox/components/FeatureListCategoryItem.vue
- src/store/modules/features.store.js
- tests/cypress/fixtures/import-tool/external-gpx-file-multi-segment.gpx
- tests/cypress/tests-e2e/importToolFile.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-849-profile-multi-segment-gpx/index.html)
> PB-849: create profile multi segement gpx

- src/modules/map/components/CompareSlider.vue
- src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
- src/modules/menu/components/advancedTools/ImportFile/useImportFile.composable.js
- src/store/modules/ui.store.js
Issue : COGTiffs are rendered as a webGL layer, which has a different graphical context than other OpenLayers layers. This causes the compare slider to not work on them.
Fix : when we deal with a COGtiff layer, we instead use the webgl context tools to make the slice.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1121-support-compare-slider-for-cogtiffs/index.html)
> PB-1121: compare slider support for COGtiffs

- src/api/__tests__/print.api.spec.js
- src/api/print.api.js
- src/config/print.config.js
- src/utils/styleUtils.js
Issue : When sending a print spec, if the scale was too small, it would be sent to the backend in a scientific notation (for example : '1.00045e-11px'), which couldn't be interpreted by the backend.
Fix : We set a new minimal scale value to ensure we always send readable specs, which is enforced as long as the scale is greater than 0.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1140-minimal-scale-for-printing/index.html)
> PB-1140: add a minimal scale for print specs

- src/api/layers/KMLLayer.class.js
- src/api/layers/KmlStyles.enum.js
- src/modules/drawing/components/DrawingSelectInteraction.vue
- src/modules/drawing/components/useDrawingModeInteraction.composable.js
- src/modules/drawing/lib/export-utils.js
- src/modules/drawing/lib/style.js
- src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- src/router/storeSync/LayerParamConfig.class.js
- src/router/storeSync/layersParamParser.js
- src/store/plugins/load-kml-kmz-data.plugin.js
- src/utils/components/DropdownButton.vue
- src/utils/featureStyleUtils.js
- src/utils/kmlUtils.js
- src/utils/layerUtils.js
- src/utils/styleUtils.js
- tests/cypress/tests-e2e/print.cy.js
this enables users to opt-out of the default style (Google Earth like) we apply by default to external KML, and let them go back to the GeoAdmin (all red) style that was previously (on mf-geoadmin3) applied across the board.
adding this choice to the layer URL extra attributes
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-856-add-kml-style-selector/index.html)
> PB-856 : add a style selector for KML in layer settings

- src/utils/__tests__/extentUtils.spec.js
- src/utils/extentUtils.js
- tests/cypress/tests-e2e/importToolFile.cy.js
The KML extent detection was not performing as expected with KML that had only one dimension out of LV95 bounds.
To counteract that, I've reverted the logic in the extent calculation, transforming LV95 bounds into WGS84 to do the matching instead of transforming a potentially big WGS84 extent to LV95 (lead to big math error...)
[Test link with sample file](https://sys-s.dev.bgdi.ch/5tsm1i0pza4b)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1221-kml-extent-false-positive/index.html)
> PB-1221 : partially out of bound KML was ignored entirely

- src/utils/legacyLayerParamUtils.js
When opening the app with a layerId=featureId URL param, the ; was still added to the layers URL param after processing the feature pre-selection. This means the layers URL param was malformed and an error showed up.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1211-more-link-issue/index.html)
> PB-1211 : do not add ; if layer with feature selection is alone

- src/router/storeSync/TimeSliderParamConfig.class.js
- src/router/storeSync/__tests__/layersParamParser.spec.js
- src/router/storeSync/layersParamParser.js
some feature IDs ends with something like "1314.070" and the layer parsing code was transforming them into number, removing the trailing zero from the ID.
This broke many "Link to object" link generated by the backend.
Also fixing an issue with the time slider warning not being wrapped in an array, and generating a crash when its value was not set to something valid
[Test link with "Link to object" params](https://sys-map.dev.bgdi.ch/preview/fix-pb-1222-broken-link-to-object/index.html?ch.vbs.schiessanzeigen=1314.070&time=None&lang=de&topic=ech)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1222-broken-link-to-object/index.html)
> PB-1222 : fix mishandling of feature ID that are "number-like"

- src/modules/menu/components/LayerDescriptionPopup.vue
- src/utils/components/SimpleWindow.vue
and make it resizable too, so that users can adjust the size to their needs
[Test link with 2 large legend layers](https://sys-map.dev.bgdi.ch/preview/fix-pb-1235-layer-legend-too-small/index.html#/map?lang=de&center=2612823.26,1175543.77&z=4.673&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&layers=ch.swisstopo.geologie-tiefengeothermie_projekte;ch.bav.sachplan-infrastruktur-schiene_kraft&featureInfo=default)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1235-layer-legend-too-small/index.html)
> PB-1235 : make legend window adapt to its content

- tests/cypress/tests-e2e/search/search-results.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1189-add-test-layer-feature-search/index.html)
> PB-1189: add layer feature search test

- src/api/layers/ExternalWMTSLayer.class.js
- src/modules/map/components/cesium/CesiumInternalLayer.vue
- src/modules/map/components/cesium/CesiumVisibleLayers.vue
- src/modules/map/components/cesium/CesiumWMTSLayer.vue
- src/modules/map/components/cesium/utils/useAddImageryLayer.composable.js
- src/store/plugins/sync-camera-lonlatzoom.js
- tests/cypress/fixtures/layers.fixture.json
- tests/cypress/tests-e2e/3d/layers.cy.js
transform the Cesium WMTS component to composition API
Adding a composable that can be used for WMS layers when we want to move them to composition API too.
Issues fixed by this commit :
- opacity when a layer as a specific config for 3D (like SWISSIMAGE) by giving the 3D config the same opacity as the 2D equivalent. The opacity of the 3D config was used, but the UI is editing the opacity of the 2D layer.
- error that popped up in the console when switching from 3D to 2D, the camera position is set to null by the unmounted CesiumMap hook and then the sync camera plugin uses the camera value without checking its validity. Adding a little check to remove the error
- External WMTS style wasn't properly applied to the 3D viewer, a good example is to load swissdatacube WMTS with layer …
> PB-995 : Cesium WMTS as composable

- src/router/storeSync/storeSync.config.js
- src/store/modules/layers.store.js
Issue: when the application was already loaded, it was no longer possible to set the background layer to the void layer.
Cause: the url parser validation checked for the 'void' string which is not in the background layers, and the setter only accepted null as a valid option.
Fix : we allowed the 'void' string value in both cases
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1259-change-bglayer-through-url/index.html)
> PB-1259: allow bgLayer modification through URL

- src/router/storeSync/storeSync.config.js
- tests/cypress/tests-e2e/embed.cy.js
Issue: In chrome-based web browsers, the layers would be removed from the preview and the link when opening the embed preview unless the bgLayer was 'void'.
Cause: There might be a need to refactor completely the embed sharing component, but for now, it seems the issue was caused by the bgLayer parameter being handled before the layers. This would cause a situation where the router would trigger a mutation, go to a new URL with no layers, and overwrite what should have been in store. As the default background layer is the void one, we did not go through this when we used the empty background layer.
Fix: by changing the order in which the parameters are handled, we can ensure layers are handled before the background layer, and thus ensure they are kept.
[Test …
> PB-1254: fix embed preview in chrome

- src/modules/menu/MenuModule.vue
- src/modules/menu/components/menu/MenuTray.vue
- tests/cypress/tests-e2e/importToolMaps.cy.js
- tests/cypress/tests-e2e/menuTray.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1181-menu-scrollable/index.html)
> PB-1181: menu scrollable

- src/modules/drawing/DrawingModule.vue
- src/modules/drawing/components/AddVertexButton.vue
- src/modules/drawing/components/AddVertexButtonOverlay.vue
- src/modules/drawing/components/DrawingInteractions.vue
- src/modules/drawing/components/DrawingSelectInteraction.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/useModifyInteraction.composable.js
- tests/cypress/tests-e2e/drawing.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1212-allow-delete-last-point-on-editing-mode/index.html)
> PB-1212: Allow delete last point by button when on line editing mode.

- src/store/modules/search.store.js
- tests/cypress/tests-e2e/search/search-results.cy.js
users were confused that the full address of what they selected in the search result wasn't properly shown in the UI.
This only adds the title of such entries to the search bar, without triggering a new search. This means the search results aren't cleared/emptied when a location is selected.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1246-location-search/index.html)
> PB-1246 : add location search entry title to search bar when selected

- .eslintrc.cjs
- src/config/map.config.js
- src/modules/map/components/cesium/CesiumMap.vue
- vite.config.mts
During the build the cesium static assets were put into the root of the application.
This was an issue for our deployment strategy were we have all assets in a
versioned folder and were we first deploy the versioned folder before deploying
the entry point index.html that point to the versioned folder. This allow for
a pseudo atomic deployment.
So now all the cesium static assets have been placed into VERSION/cesium/ path.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1176-cesium-build/index.html)
> PB-1176: Fix cesium static assets location

- src/store/plugins/geolocation-management.plugin.js
Issue : When activating geolocation for the first time, we do not zoom on the location
Fix : We use the already existing boolean to check if we're on the geolocation first activation. If that's the case, we now zoom at zoom level 8
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1146-zoom-on-location-geolocation/index.html)
> PB-1146: Zoom in on geolocation first activation

- src/modules/infobox/components/FeatureList.vue
- src/modules/map/components/cesium/CesiumInternalLayer.vue
- src/modules/map/components/cesium/CesiumWMSLayer.vue
- src/modules/map/components/cesium/utils/useAddImageryLayer.composable.js
- src/modules/menu/components/LayerCatalogueItem.vue
- tests/cypress/tests-e2e/3d/layers.cy.js
- tests/cypress/tests-e2e/importToolFile.cy.js
fixing an issue with preview layer being kept on the map after added through the catalogue component
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1204-cesium-wms-composable/index.html)
> PB-1204 Cesium WMS as composable and tested with Cypress

- cypress.config.mjs
- src/modules/map/components/CompareSlider.vue
- tests/cypress/tests-e2e/compareSlider.cy.js
and add some perf improvements flags for when the CI runs tests heedlessly
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1150-increase-cypress-memory/index.html)
> PB-1150 : increase Cypress memory

- src/modules/map/components/cesium/CesiumMap.vue
Issue: The compass in the 3d viewer was hidden
Cause: We checked before there was an instance of the component if we could add the scene and the clock to the compass element, meaning it would create an empty compass.
Fix: We wait for the map to be ready before adding the compass
[Test link](https://sys-map.dev.bgdi.ch/preview/hotfix-compass-not-showing/index.html)
> PB-1310: 3D navigation compass was not showing

- src/router/__tests__/legacyPermalinkManagement.routerPlugin.spec.js
- src/router/legacyPermalinkManagement.routerPlugin.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1263-add-handlelegacyparam-function-tests/index.html)
> PB-1263: add handleLegacyParam function tests

- package-lock.json
- package.json
- scripts/check-external-layers-providers.js
- src/api/layers/layers-external.api.js
- src/modules/menu/components/advancedTools/ImportCatalogue/utils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-326-check-external-provider-get-map/index.html)
> PB-326: check external provider get map

- src/config/staging.config.js
- src/setup-fontawesome.js
- src/utils/components/AppVersion.vue
Issue : We want to allow people to be able to reach the github repository of the mapviewer
Fix : We add a small github icon next to the version, and allow people to click on the version or the icon to open the github repository in a new tab.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1031-add-github-link/index.html)
> PB-1031: Add a github link to the version

- src/api/print.api.js
- src/utils/styleUtils.js
Need to be reviewd by @ltkum as this revert his change in https://github.com/geoadmin/web-mapviewer/pull/1015
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1278-icon-offset/index.html)
Sample on 1:500 and 1:5000. Looks good
[Test link](https://sys-map.dev.bgdi.ch/preview/pb-1278-icon-offset/index.html)
> PB-1278: Fix Icon with offset (pin) changes positon

- tests/cypress/tests-e2e/menuTray.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1186-test-mobile-landscape/index.html)
> PB-1186: Add test for landscape mobile from the portrait one and adapt accordingly.

- src/api/features/EditableFeature.class.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
- src/modules/infobox/components/styling/DrawingStylePlacementSelector.vue
- src/modules/infobox/components/styling/FeatureStyleEdit.vue
- src/store/modules/features.store.js
- src/utils/featureStyleUtils.js
- src/utils/kmlUtils.js
- tests/cypress/tests-e2e/drawing.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1297-make-position-of-text-labels-configurable/index.html)
> PB-1297: make position of text labels configurable

- src/modules/drawing/components/DrawingHeader.vue
- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/drawing/components/ShareWarningPopup.vue
- src/modules/drawing/components/useDrawingModeInteraction.composable.js
- src/modules/i18n/locales/de.json
- src/modules/i18n/locales/en.json
- src/modules/i18n/locales/fr.json
- src/modules/i18n/locales/it.json
- src/modules/i18n/locales/rm.json
- src/router/storeSync/LayerParamConfig.class.js
- src/store/modules/drawing.store.js
- src/views/MapView.vue
- tests/cypress/support/drawing.js
- tests/cypress/tests-e2e/drawing.cy.js
- tests/cypress/tests-e2e/reportProblem.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-580-add-warning-leaving-drawing-mode/index.html)
> PB-580: Add warning when drawing could get lost otherwise

- .eslintrc.cjs
- src/api/features/features.api.js
- src/modules/map/components/cesium/utils/highlightUtils.js
- src/store/modules/drawing.store.js
- vite-plugins/vite-plugin-generate-build-info.js
there are from time to time console.log (or console.error) that slips through our review process. To counter that I've activated the ESLint no-console rule on all non-test, non-script files.
[Test link](https://sys-map.dev.bgdi.ch/preview/enforce-no-console/index.html)
> Enforce ESLint no-console rule

- src/modules/drawing/components/DrawingToolbox.vue
- src/modules/menu/components/print/MenuPrintSection.vue
- src/store/modules/ui.store.js
- src/views/MapView.vue
using window.open to trigger a download (of the print results) was triggering the beforeUnload event in MapView.vue's code, and showing the "you'll lose your drawing" warning, while we stay on the page in the end.
Also fixing some usage of the old $t to the new Composition API equivalent
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1355-no-warning-after-print/index.html)
> PB-1355 : don't show drawing lost warning when we open download PDFs

- src/api/print.api.js
Issue : when trying to print imported kmls, we sometimes ran into an issue where there was no offset, and the printing service was not able to interpret a field not being present
Fix : We now add a little line to ensure offsets exists in line when printing
[Test link](https://sys-map.dev.bgdi.ch/preview/bugfix-pb-1358-cant-print-kmls/index.html)
> PB 1358: fix issue with printing imported KMLS

- src/api/print.api.js
Issue : Measures could not be printed anymore
Cause : With the implementation, we had set the graphicYoffset to NaN instead of 0 when there is no offset, meaning the print service could not interpret it
Fix : We ensure the graphicYoffset is set to 0 if non existent.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1358-fix-printing-for-measures/index.html)
> PB 1358: Allow printing measures again

- src/utils/components/SimpleWindow.vue
- tests/cypress/fixtures/legend.fixture.html
- tests/cypress/support/commands.js
- tests/cypress/tests-e2e/topics.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1192-add-test-open-move-legend-panel/index.html)
> PB-1192: add test move and resize legend

- src/config/staging.config.js
- src/utils/components/AppVersion.vue
The github link now leads to the specific release
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1031-add-github-link-to-release/index.html)
> PB-1031: redirect github link to release page

- packages/mapviewer/src/modules/menu/components/header/HeaderLangSelector.vue
- packages/mapviewer/src/modules/menu/components/header/HeaderLink.vue
- packages/mapviewer/src/modules/menu/components/header/HeaderWithSearch.vue
- packages/mapviewer/tests/cypress/tests-e2e/changeLanguage.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1180-test-lang-selection/index.html)
> PB-1180: Add test for changing language in mobile and desktop

- packages/mapviewer/src/modules/map/components/toolbox/MapToolbox.vue
Issue : Some people expressed that removing the zoom buttons on mobile was an issue for them, either regarding the hardware they are using or because of outside issues which stopped them from using the mapviewer correctly.
Fix : We bring the zoom buttons back.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1444-put-back-the-zoom-buttons-on-mobile/index.html)
> PB-1443: re-introduce zoom buttons on mobile

- packages/mapviewer/src/modules/menu/components/LayerDescriptionPopup.vue
- packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
- packages/mapviewer/src/utils/components/SimpleWindow.vue
- packages/mapviewer/tests/cypress/tests-e2e/reportProblem.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/topics.cy.js
The layer legend info window has been smaller on mobile displays, and when displayed, closes the menu so as to not obscure the map behind. 
Here's a preview of the change : 
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1208-layer-legend-popup/index.html)
> PB-1208 : Have layer legend behind the menu on mobile

- packages/mapviewer/src/store/modules/search.store.js
- packages/mapviewer/tests/cypress/tests-e2e/search/search-results.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1209-select-feature-no-info-from-search/index.html)
> PB-1209: Fix no feature tooltip when select feature from search.

- packages/mapviewer/src/modules/menu/components/LayerCatalogueItem.vue
- packages/mapviewer/tests/cypress/tests-e2e/importToolMaps.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/topics.cy.js
Don't render the invisible layer catalogue items. Only render them when the nested navigation is un-collapsed.
This produces quite a performance gain, as many sub-sequent components don't need rendering. This includes `<TextTruncate>`, where each of them creates a ResizeObserver on the DOM. Without this change we have ~1100 resize observers, with the change there are only ~250.
I will investigate those ~250 maybe in another attempt, some of them might be resolved when switching to the new tooltip.
This results in quite the performance gain, mostly noticable in development mode.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-less-text-truncate/index.html)
> Don't render invisible layer catalogue items

- package.json
Updating the NPM version in package.json to 11. This goes in tandem with https://github.com/geoadmin/infra-terraform-bgdi/pull/772.
This is preparatory work for having the possibility to use pnpm alongside npm for a short period of time on the CI. After the pnpm merge, this will probably become irrelevant.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-npm-11/index.html)
> Bump npm version to 11 in package.json

- packages/mapviewer/src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
- packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
we only tested pre-loading KMLs through the URL param in 3d/layers.cy.js, so here's a test that import a KML through the Advanced Tool menu section
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-995-add-import-kml-3d-test/index.html)
> PB-995 : add import KML in 3D test through the import popup

- packages/mapviewer/cypress.config.mjs
- packages/mapviewer/package.json
- packages/mapviewer/vite.config.mts
- pnpm-lock.yaml
- pnpm-workspace.yaml
In another, fresh vue installation I noticed this plugin. I did a little research gra what it is, and it's apparently an integrated vue dev tools. On their website, the [state](https://devtools.vuejs.org/guide/vite-plugin) that this is the preferred way of using the dev tools.
What this does it it renders this little button at the bottom of the page with which one can access the dev tools:
I don't know if this is a good idea or not, let me hear your opinions. The dev tools in my firefox don't work half of the time. 
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-vite-plugin-vue-devtools/index.html)
> Install vite-plugin-vue-devtools

- packages/mapviewer/src/modules/i18n/README.md
- packages/mapviewer/src/modules/i18n/locales/de.json
The anchor in the link to the German version of the help for the feedback form wasn't correct
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1435-feedback-help-link/index.html)
> PB-1435 Fix the german link to the feedback help page anchor

- packages/mapviewer/src/modules/menu/components/header/AdditionalInfoCollapsable.vue
The dropdown wasn't transparent and the text was 1px below the rest of that row
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-news-dropdown-style/index.html)
> Fix the styling of the News Dropdown

- packages/mapviewer/src/router/storeSync/storeSync.config.js
- packages/mapviewer/tests/cypress/tests-e2e/layers.cy.js
- Removed the cypress bypass in the background layer validation.
- At one point, cypress was sending an `undefined` parameter rather than nothing, which caused the validation to crash.
- This is apparently no longer the case, so we can get rid of this exception.
- Added a test to ensure we are having the 'void' layer as a background when requesting the 'void' layer specifically.
remove unused import
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1261-tests-for-bg-layers/index.html)
> PB-1261: add test case for void background

- packages/mapviewer/src/modules/drawing/DrawingModule.vue
- packages/mapviewer/src/modules/drawing/components/useModifyInteraction.composable.js
- packages/mapviewer/tests/cypress/tests-e2e/drawing.cy.js
users on touch devices could trigger a delete by double tapping on the last point they were drawing, which wasn't ideal.
As I've run out of ideas on how to fix this on mobile, I've simply removed the possibility to delete a point on mobile as we lack "gestures" to achieve it.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1004-revert-use-of-right-click/index.html)
> PB-1004 : only use right click to trigger "delete point" action

- packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1456-missing-layer-dropped-back/index.html)
> PB-1456: Fix dropping layer on itself deleting the dragged layer in active layer list.

- packages/mapviewer/src/modules/drawing/DrawingModule.vue
the loading state of a KML layer wasn't managed by the drawing module, meaning that the timing of when the KML data was loaded could lead to no features being present on the drawing layer. Very dangerous because that could make user empty their KMLs if they would edit it in this state
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1548-fix-loading-of-drawing-module-with-adminid/index.html)
> PB-1548 : fix mismanagement of drawing features if coming with adminId

- packages/mapviewer/src/router/storeSync/SearchParamConfig.class.js
- packages/mapviewer/src/store/modules/search.store.js
- packages/mapviewer/src/store/plugins/redo-search-when-needed.plugin.js
- packages/mapviewer/tests/cypress/support/commands.js
- packages/mapviewer/tests/cypress/tests-e2e/search/search-results.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1480-swissearch-crosshair/index.html)
The issue occurs when the swisssearch value is a valid location and also a valid coordinate. An example from the JIRA issue: http://map.geo.admin.ch/?swisssearch=46.5057,6.6278&zoom=8&crosshair=marker. The query is **swisssearch=46.5057,6.6278**. It is a valid coordinate, and when we search the location, it returns a valid object:
```json
{
"fuzzy": "true",
"results": [
{
"attrs": {
"detail": "dorfstrasse 46 5057 reitnau 4281 reitnau ch ag",
"featureId": "3098536_0",
"geom_quadindex": "021131022303023202112",
"geom_st_box2d": "BOX(2646205.076 1233096.405,2646205.076 1233096.405)",
"label": "Dorfstrasse 46 <b>5057 Reitnau</b>",
"lat": 47.247169494628906,
"lon": 8.048954963684082,
"num": 46, …
```
> PB-1480: Fix bug with swissearch and crosshair together

- packages/mapviewer/tests/cypress/tests-e2e/importToolMaps.cy.js
The tests were flaky in the way that they couldn't select the correct elements for testing. With closing the menu and adding some assertions of the elements being visible it seems that we slow down cypress enough so that the selection is correct now
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-importool-tests/index.html)
> Fix flaky importToolMaps tests

- packages/mapviewer/src/modules/drawing/components/AddVertexButtonOverlay.vue
- packages/mapviewer/tests/cypress/tests-e2e/drawing.cy.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1554-relocate-add-point-extension-line-drawing/index.html)
> PB-1554: fix relocate + point extension of lines in drawing mode

- packages/mapviewer/package.json
- packages/mapviewer/vite.config.mts
- vitest.workspace.js
The vitest plugin in vscode suggested using this vitest.workspace setup. This helps with running the unit tests from inside the editor, hence these changes.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-vitest-workspace/index.html)
> Add vitest workspace configuration to make tests work in vscode

- packages/mapviewer/src/api/__tests__/print.api.spec.js
- packages/mapviewer/src/api/print.api.js
- packages/mapviewer/src/modules/map/components/openlayers/utils/usePrint.composable.js
- packages/mapviewer/src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
- packages/mapviewer/src/store/modules/print.store.js
- packages/mapviewer/tests/cypress/tests-e2e/print.cy.js
- This is work mostly done by Ismail Sunni, in a new branch now that a lot modularization has been done.
- limit the print specification sent to the print service to the printed extent
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-878-filter-print-extent/index.html)
> PB-878: limiting the extent of the print

- packages/mapviewer/src/modules/i18n/locales/de.json
- packages/mapviewer/src/modules/i18n/locales/en.json
- packages/mapviewer/src/modules/i18n/locales/fr.json
- packages/mapviewer/src/modules/i18n/locales/it.json
- packages/mapviewer/src/modules/i18n/locales/rm.json
- packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
- packages/mapviewer/src/router/storeSync/NoSimpleZoomParamConfig.class.js
- packages/mapviewer/src/router/storeSync/storeSync.config.js
- packages/mapviewer/src/store/modules/ui.store.js
- packages/mapviewer/src/utils/utils.js
- packages/mapviewer/src/views/EmbedView.vue
- packages/mapviewer/tests/cypress/tests-e2e/embed.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/shareShortLink.cy.js
- pnpm-lock.yaml
If the nosimplezoom = true parameter is added to an embedded URL, the user needs to press ctrl in order to zoom into the map. Here's a preview of the hint : 
[Test link](https://sys-map.dev.bgdi.ch/preview/task-pb-1493-add-iframe-specific-scroll/index.html)
> PB-1493 : Add iframe parameter to scroll / zoom with CTRL

- packages/mapviewer/src/utils/legacyLayerParamUtils.js
- packages/mapviewer/tests/cypress/tests-e2e/legacyParamImport.cy.js
Issue: When parsing a legacy link, KML layers would use the standard style. Those KMLs were most likely designed on the old viewer, where they were rendered with the `geoadmin` style. Users would like their KMLs to still have the same style as they used to.
Fix: When loading a legacy KML layer, we set its style to geoadmin.
Test link with a kml layer : [TEST](https://sys-map.dev.bgdi.ch/preview/fix-pb-1494-use-old-style-on-legacy-links/index.html?layers=KML||https://sys-public.dev.bgdi.ch/api/kml/files/Gz7X_4hAQDyb3_f13UukcA)
same layer on geoadmin : [CURRENT](https://map.geo.admin.ch?layers=KML||https://sys-public.dev.bgdi.ch/api/kml/files/Gz7X_4hAQDyb3_f13UukcA)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1494-use-old-style-on-legacy-links/index.html)
> PB-1494: use geoadmin style on legacy links

- packages/mapviewer/src/modules/i18n/locales/de.json
- packages/mapviewer/src/modules/i18n/locales/en.json
- packages/mapviewer/src/modules/i18n/locales/fr.json
- packages/mapviewer/src/modules/i18n/locales/it.json
- packages/mapviewer/src/modules/i18n/locales/rm.json
- packages/mapviewer/src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
- packages/mapviewer/tests/cypress/tests-e2e/compareSlider.cy.js
- pnpm-lock.yaml
Issue : When pressing 'compare' on a map with no active layers, the user had no feedback letting him know why the slider wasn't showing up.
Fix : Added a hint which is displayed when no layers are active
Here's a preview : 
Note : translation keys are temporary, needs to be confirmed with @Luke252 
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-419-user-feedback-compare-slider/index.html)
> PB-419 : Add feedback indicating absence of layers when pressing 'compare'

- packages/geoadmin-coordinates/src/proj/CoordinateSystem.ts
- packages/geoadmin-coordinates/src/proj/LV03CoordinateSystem.ts
- packages/geoadmin-coordinates/src/proj/LV95CoordinateSystem.ts
- packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/parser/CloudOptimizedGeoTIFFParser.class.js
- packages/mapviewer/src/store/index.js
- packages/mapviewer/src/store/plugins/load-cog-metadata.plugin.js
Some COGs we provide aren't encoded with an EPSG number in the corresponding field, but with a specific number telling us it is a "user defined CRS". In order to be able to detect such COGs, I've added a technical name to both LV95 and LV03, which will be used to detect COGs that are in such format.
[Test link with relevant COG](https://sys-map.dev.bgdi.ch/preview/bug-pb-1605-fix-cog-projection-detection/index.html#/map?layers=COG|https://data.geo.admin.ch/ch.bafu.luftreinhaltung-stickstoffdioxid/luftreinhaltung-stickstoffdioxid_1990/luftreinhaltung-stickstoffdioxid_1990_2056.tif)
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1605-fix-cog-projection-detection/index.html)
> PB-1605 : detect COG projection based on name when no EPSG found

- packages/mapviewer/src/modules/infobox/components/FeatureDetail.vue
Issue : we adapted the CSS for the generic pop up which holds the 3d features info for now , but the styling doesn't please our users who are using the drawings.
Fix : We revert the changes and the 3d pop up will be done when we can get it from the backend :)
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1561-drawing-tooltip-descriptions-readability/index.html)
> PB-1561: revert CSS changes to generic feature pop up windows

- packages/mapviewer/src/modules/infobox/components/FeatureList.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
- packages/mapviewer/tests/cypress/tests-e2e/3d/layers.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/featureSelection.cy.js
Issue : An overflow was causing two scroll bars to appear on Chromium browsers when using the 3D view.
Fix : removed the fluid css condition, and added logic to switch max height depending on aspect ratio of viewport.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1202-double-overflow-3d-tooltip/index.html)
> PB-1202 : Fix overflow issue in 3D feature tooltip view on Chrome

- package.json
- packages/geoadmin-coordinates/package.json
- packages/geoadmin-log/package.json
- packages/geoadmin-numbers/package.json
- packages/geoadmin-tooltip/package.json
Running `pnpm run build:dev:watch` permits the user to modify the geodamin package and updating the build so that the changes have direct effect on the running mapviewer.
Note: I observed that the mapviewer updates the open page too fast, which makes it not load correctly and a reload of the page is sometimes needed.
[Test link](https://sys-map.dev.bgdi.ch/preview/add-build-watch-packages/index.html)
> Add a build dev watch option to geoadmin packages

- packages/geoadmin-coordinates/src/proj/WGS84CoordinateSystem.ts
- packages/mapviewer/src/api/layers/WMSCapabilitiesParser.class.js
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- packages/mapviewer/src/store/index.js
- packages/mapviewer/src/store/modules/layers.store.js
- packages/mapviewer/src/store/plugins/reproject-layers-on-projection-change.plugin.js
- packages/mapviewer/tests/cypress/tests-e2e/3d/layers.cy.js
[Test link with layers of the ticket](https://sys-map.dev.bgdi.ch/preview/fix-pb-1559-external-wms-not-displayed-switching-3d-2d/index.html#/map?lang=de&sr=3857&camera=8.004717,46.7976,397911.2,-90,,&3d&topic=ech&layers=WMS%7Chttps://geo.csd.ch/server/services/DCH000513_01_Planungskooridor_Innertkirchen_Mettlen/MapServer/WMSServer?%7C9,,0.63;WMS%7Chttps://geo.csd.ch/server/services/DCH000513_01_Planungskooridor_Innertkirchen_Mettlen/MapServer/WMSServer?%7C10,,0.65;WMS%7Chttps://geo.csd.ch/server/services/DCH000513_01_Planungskooridor_Innertkirchen_Mettlen/MapServer/WMSServer?%7C11,,0.65;WMS%7Chttps://geo.csd.ch/server/services/DCH000513_01_Planungskooridor_Innertkirchen_Mettlen/MapServer/WMSServer?%7C1;WMS%7Chttps://geo.csd.ch/server/services/DCH000513_01_Planungskooridor_Innertkirchen_Met …
> PB-1559: external WMS not displayed switching from 3D to 2D

- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersCompassButton.vue
Specifying a width on the css class seems to fix it.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1621-center-orientation-arrow/index.html)
> PB-1621 : Fix compass icon alignement

- packages/mapviewer/package.json
- packages/mapviewer/src/api/layers/AbstractLayer.class.js
- packages/mapviewer/src/modules/map/components/CompareSlider.vue
- packages/mapviewer/src/modules/map/components/cesium/CesiumVisibleLayers.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersAccuracyCircle.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersGPXLayer.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersRectangleSelectionFeedback.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersVectorLayer.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersVisibleLayers.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
- packages/mapviewer/src/modules/menu/components/debug/DebugLayerFinder.vue
- packages/mapviewer/src/router/storeSync/LayerParamConfig.class.js
- packages/mapviewer/src/store/modules/__tests__/layers.store.spec.js
- packages/mapviewer/tests/cypress/tests-e2e/compareSlider.cy.js
- packages/mapviewer/tests/cypress/tests-e2e/layers.cy.js
- pnpm-lock.yaml
- pnpm-workspace.yaml
[Test link with layers from the ticket](https://sys-map.dev.bgdi.ch/preview/fix-pb-1602-duplicates-layer-compare/index.html#/map?lang=en&center=2660000,1190000&z=1&topic=ech&compareRatio=0.504&layers=ch.bafu.luftreinhaltung-feinstaub_pm10@year=2020,,1;ch.bafu.luftreinhaltung-feinstaub_pm10@year=2001,,1&bgLayer=ch.swisstopo.pixelkarte-farbe)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1602-duplicates-layer-compare/index.html)
> PB-1602: fix duplicates layer can not be compared

- packages/mapviewer/src/modules/i18n/locales/de.json
- packages/mapviewer/src/modules/i18n/locales/en.json
- packages/mapviewer/src/modules/i18n/locales/fr.json
- packages/mapviewer/src/modules/i18n/locales/it.json
- packages/mapviewer/src/modules/i18n/locales/rm.json
- packages/mapviewer/src/utils/components/FeedbackPopup.vue
- packages/mapviewer/src/views/MapView.vue
Showing a banner informing our users about the current outage
Should be reverted as soon as the outage is over
[Test link](https://sys-map.int.bgdi.ch/preview/wms_outage_banner/index.html)
> Showing a banner informing our users about the current outage - #patch

- packages/mapviewer/src/utils/coordinates/__test__/coordinateExtractors.spec.js
- packages/mapviewer/src/utils/coordinates/coordinateExtractors.js
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1320-support-more-separator-on-search/index.html)
Result from the sample coordinate from the user: ` 692’910 238’550`
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1320-support-more-separator-on-search/index.html)
> PB-1320: Support More Thousand Separator on Search

- packages/mapviewer/src/modules/menu/components/help/MenuHelpSection.vue
- packages/mapviewer/src/router/storeSync/storeSync.config.js
- packages/mapviewer/src/store/modules/i18n.store.js
- packages/mapviewer/tests/cypress/tests-e2e/changeLanguage.cy.js
Issue: some people can't use lowercase letters for the `lang` URL parameter and wanted to be able to use uppercase letters
Fix: we let people input uppercase letters in the `lang` URL parameter and force it to lowercase on our side.
Also: added some tests
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1427-accept-uppercase-lang-param/index.html)
> PB-1427: Support uppercase language parameter

- packages/mapviewer/src/modules/map/components/cesium/CesiumMouseTracker.vue
- packages/mapviewer/src/modules/map/components/common/mouseTrackerUtils.js
- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersMouseTracker.vue
As pointed out by some of our users, the dynamically generated coordinates on the bottom part of the map with the mouse are not precise when dealing with LV03. They are generated without taking into consideration the real deformation between LV95 and LV03, and are calculated based on a simple matrix reprojection to be more dynamic (we are not using the REFRAME service after each mouse move, that would be overkill).
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1670-lv03-circa-for-mouse-track/index.html)
> PB-1670: clarify lack of precision of mouse tracked LV03 coordinates

- packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
adding some retry-ability to the tests so that it behaves better on the CI.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1179-add-retryability-to-tests/index.html)
> PB-1179: fix profile segment test not passing on CI

- package.json
- packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/parser/CloudOptimizedGeoTIFFParser.class.js
- packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/parser/FileParser.class.js
- packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/parser/KMZParser.class.js
we were missing the little endian signature for BigTIFF (which is different than normal TIFFs) to be able to parse a local BigTIFF file.
It was working fine with URLs already because we do not test against little endian signature in this case, and let GeoTIFF.js library do its magic, so nothing to change there.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1579-local-bigtiff-support/index.html)
> PB-1579: add support for local BigTIFF

- packages/mapviewer/src/utils/components/SimpleWindow.vue
- packages/mapviewer/tests/cypress/tests-e2e/reportProblem.cy.js
Some users that use the browser zoom to enlarge the UI have issues with the SimpleWindow component (especially when it's used by the feedback component) because it grows too high, and overflow the header (some even saying the X button of the window was out of screen).
So to fix that, I've limited the height of all simple windows to 2/3 of the height of the screen. This was tested with a browser zoom of 200% and having the "report a problem" window opened.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1697-simple-window-too-big-when-broser-zoom/index.html)
> PB-1697: limiting floating window's height

- packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
less page reload, as it is what causes the flakiness with the import GPX test (the map doesn't trigger the ready event on the CI for some reason)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-ci-test-flakiness/index.html)
> Attempt at reducing CI flakiness

- packages/mapviewer/src/modules/map/components/MapPopover.vue
- packages/mapviewer/src/utils/components/SimpleWindow.vue
- packages/mapviewer/src/utils/composables/useMovableElement.composable.js
Mouse events have been removed in favour of pointer events for better compatibility with mobile devices and touch screens.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1054-tooltip-touch-events/index.html)
> PB-1054 : Remove mouse events from useMovableElement and replace with pointer events

- packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
This is an attempt at catching this sort of problem in the future. As of now, the test passses.
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1491-s3-kml-content-type-parsing/index.html)
> PB-1491 : Add a test to parse an online kml with the wrong content-type

- packages/mapviewer/src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
Also changed the border class to be tailwind-compliant
Here's the result : 
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1680-icon-selector-bug/index.html)
> PB-1680 : Fix icon selector border

- packages/mapviewer/src/config/cesium.config.js
- packages/mapviewer/src/modules/map/components/cesium/CesiumKMLLayer.vue
[Test link](https://sys-map.dev.bgdi.ch/preview/task-pb-1691-pin-position-3d/index.html)
The Marker icon has an offset in 2d space, in order to display it anchored on the tip, which
cause the offset visible in 3d. Our solution is to add a conditional check in 3d
to properly display markers, as all other icons don't have this problem.
Here's the result : 
[Test link](https://sys-map.dev.bgdi.ch/preview/task-pb-1691-pin-position-3d/index.html)
> PB-1691 : Remove pin and highlight position offset in 3D view

- packages/mapviewer/src/modules/i18n/locales/de.json
- packages/mapviewer/src/modules/i18n/locales/en.json
- packages/mapviewer/src/modules/i18n/locales/fr.json
- packages/mapviewer/src/modules/i18n/locales/it.json
- packages/mapviewer/src/modules/i18n/locales/rm.json
- packages/mapviewer/src/modules/menu/components/help/ReportProblemButton.vue
This will be merged after the changes made to the `service-feedback` [backend](https://github.com/geoadmin/service-feedback/pull/45)
[Test link](https://sys-map.dev.bgdi.ch/preview/task-pb-1703-allow-png-report-problem/index.html)
> PB-1703: Add support for .png files in reportProblem window

- packages/mapviewer/src/modules/map/components/cesium/utils/swissnamesStyle.js
This seems to fix the issue of labels being shown despite being behind terrain. Previously, it seems we weren't doing any depth testing for labels (perhaps intentionally?) so I've enabled it back.
Before : 
After : 
[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-1357-hide-3d-labels-behind-terrain/index.html)
> PB-1357 : Enable depth testing for labels

- packages/mapviewer/src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
[Test link with url from ticket](https://sys-map.dev.bgdi.ch/preview/fix-pb-1752-fix-timeslider-wms/index.html#/map?lang=fr&center=2653530.19,1189865.23&z=1.461&topic=ech&layers=ch.swisstopo.pixelkarte-farbe-pk25.noscale@year=1989;ch.swisstopo.pixelkarte-pk25.metadata@year=1989&bgLayer=void&featureInfo=default&timeSlider=1989)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1752-fix-timeslider-wms/index.html)
> PB-1752: fix timeslider wms

- packages/mapviewer/src/config/layers.config.ts
- packages/mapviewer/src/config/regex.config.ts
- packages/mapviewer/src/store/modules/layers.store.js
- packages/mapviewer/src/utils/kmlUtils.js
- packages/mapviewer/tests/cypress/fixtures/external-wms-getcap-1.fixture.xml
- packages/mapviewer/tests/cypress/tests-e2e/importToolMaps.cy.js
Issue: When importing layers from our own services, a disclaimer was visible, saying the sources were provided by a third party.
Fix: We "white list" all sources coming from a "*.map.geo.admin.ch" domain, removing the disclaimer.
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-1699-whitelist-swisstopo-external-layers/index.html)
> PB-1699: White listing internal services used as an external provider

- packages/mapviewer/src/config/baseUrl.config.js
- packages/mapviewer/src/service-workers.ts
trying to stop ServiceWorker from filling up requests to service-print3 downladURL on Firefox.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1816-narrow-cache-definition/index.html)
> PB-1816: narrowing index.html cache definition to current origin only

- packages/mapviewer/src/config/baseUrl.config.js
- packages/mapviewer/src/service-workers.ts
- packages/mapviewer/src/utils/offline/OfflineReadinessStatus.vue
- packages/mapviewer/vite.config.mts
and trying to keep the fix for Firefox print working
Network first means the Service-Worker will attempt to load the resource online regardless of the cache status, and if the network responds it will update the cache with the new answer.
We need a good e2e test coverage (with something like Playwright) to be confident enough to change the strategy back to StaleWhileRevalidate
Giving a full URL to the "Manifest generation function" is a bad idea, and the service worker isn't loading anymore, reverting to relative `index.html` path, and editing the API print regex to match a regex found in the VitePWA documentation
Adding a "BETA" badge to the feature, to have a better "expectation management" and signify that this could have some bugs still.
[Test …
> PB-1827: change service-worker strategy to network first

- packages/mapviewer/src/store/modules/features.store.js
- packages/mapviewer/src/utils/kmlUtils.js
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1828-description-always-displayed/index.html)
> PB-1828: Fix description always shown.

- packages/mapviewer/src/modules/map/components/openlayers/utils/styleFromLiterals.js
fix wrong call to the log function
[Test link with ch.swisstopo.meldungen-karten_geodaten layer](https://sys-map.dev.bgdi.ch/preview/fix-pb-1834-wrong-call-to-log/index.html#/map?lang=en&center=2660000,1190000&z=1&topic=ech&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f;ch.bav.haltestellen-oev,f;ch.swisstopo.swisstlm3d-wanderwege,f;ch.vbs.schiessanzeigen,f;ch.astra.wanderland-sperrungen_umleitungen,f;ch.swisstopo.meldungen-karten_geodaten&bgLayer=ch.swisstopo.pixelkarte-farbe)
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1834-wrong-call-to-log/index.html)
> PB-1834: Layer "Notifications for maps an geodata" not loading

- packages/mapviewer/src/modules/map/components/openlayers/utils/styleFromLiterals.js
- packages/mapviewer/src/service-workers.ts
Issue: When introducing support for offline use of the mapviewer, we introduced a situation where QR code generation wouldn't work as soon as it was used once.
Cause: The service-worker used to cache the mapviewer for local use also cached the URL for the QR code, which was then called by the mapviewer instead of the service in the backend.
Fix: We exclude the QR Code from the caching, as we did with service print
[Test link](https://sys-map.int.bgdi.ch/preview/develop/index.html)
> New Release v1.58.0 - #minor

- packages/mapviewer/src/service-workers.ts
Issue: We currently don't have any unsolved issue, but using the service-worker tends to break api calls, as it already happened with the QRCode and the Print.
Fix: To be on the safe side, we extend the deny list to all API calls, excluding them from the caching system.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1823-extend-service-worker-deny-list/index.html)
> PB-1823: Extend the Service Worker deny list to all API calls

- packages/mapviewer/src/modules/i18n/locales/en.json
- packages/mapviewer/src/modules/i18n/locales/rm.json
- packages/mapviewer/src/store/plugins/geolocation-management.plugin.js
Issue: the terms of use link in the iframe integration menu, in english, returns a 404 since the page doesn't exist
Fix: We link to the german one.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1872-change-iframe-term-of-use-link/index.html)
> PB-1872: term of use in english iframe menu returns a 404

- packages/viewer/tests/cypress/tests-e2e/changeLanguage.cy.js
- packages/viewer/tests/cypress/tests-e2e/compareSlider.cy.js
- packages/viewer/tests/cypress/tests-e2e/crosshair.cy.js
- packages/viewer/tests/cypress/tests-e2e/drawing.cy.js
- packages/viewer/tests/cypress/tests-e2e/featureSelection.cy.js
- packages/viewer/tests/cypress/tests-e2e/footer.cy.js
- packages/viewer/tests/cypress/tests-e2e/geodesicDrawing.cy.js
- packages/viewer/tests/cypress/tests-e2e/geolocation.cy.js
- packages/viewer/tests/cypress/tests-e2e/header.cy.js
- packages/viewer/tests/cypress/tests-e2e/importToolFile.cy.js
- packages/viewer/tests/cypress/tests-e2e/importToolMaps.cy.js
- packages/viewer/tests/cypress/tests-e2e/infobox.cy.js
- packages/viewer/tests/cypress/tests-e2e/layers.cy.js
- packages/viewer/tests/cypress/tests-e2e/legacyParamImport.cy.js
- packages/viewer/tests/cypress/tests-e2e/menuTray.cy.js
- packages/viewer/tests/cypress/tests-e2e/mouseposition.cy.js
- packages/viewer/tests/cypress/tests-e2e/print.cy.js
- packages/viewer/tests/cypress/tests-e2e/search/search-results.cy.js
- packages/viewer/tests/cypress/tests-e2e/shareShortLink.cy.js
- packages/viewer/tests/cypress/tests-e2e/timeCompareSlider.cy.js
- packages/viewer/tests/cypress/tests-e2e/timeSlider.cy.js
- packages/viewer/tests/cypress/tests-e2e/topics.cy.js
- Issue: the `goToMapView` and `goToEmbedView` functions have had their signatures changed to use options as parameters, but tests were not changed to reflect those changes.
- Fix: We changed the signature of all those functions.
[Test link](https://sys-map.dev.bgdi.ch/preview/fix-pb-1383-fix-tests-signatures/index.html)
> PB-1383: change `goToView` signatures in cypress:
